const {test}=require('node:test'),vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../ingilizce/google-login.js'),'utf8');
async function fixture({pending=true,signupOK=true}={}) {
 const elements={},storage=new Map(pending?[['diji_google_pending','1']]:[]),local=new Map();let legacy=0,requests=[],redirect,oauth;
 function element(){return {style:{},hidden:false,disabled:false,checked:false,textContent:'Original',value:'',append(...items){this.children=items},after(item){this.area=item},focus(){},reset(){},reportValidity(){return elements.googleYeniOnay.checked}}}
 for(const id of ['loginForm','mesaj','girisSubtitle','girisBtn','ogrenci','sifre','googleYeniAd','googleYeniSinif','googleYeniSube','googleYeniTelefon','googleYeniEmail','googleYeniKod','googleYeniOnay','googleYeniGonder','googleYeniMesaj'])elements[id]=element();
 const auth={getSession:async()=>({data:{session:{access_token:'test',user:{user_metadata:{full_name:'Yeni Öğrenci'}}}}}),signOut:async()=>{},signInWithOAuth:async x=>{oauth=x;return {}}},win={girisYap:async()=>{legacy++},cikisYap:async()=>{}};
 vm.runInNewContext(source,{document:{getElementById:id=>elements[id],createElement:element},window:win,supabaseClient:{auth},SUPABASE_URL:'https://example.supabase.co',SUPABASE_ANON_KEY:'public',apiURL:'https://example.supabase.co/functions/v1/diji-api',sessionStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},localStorage:{getItem:k=>local.get(k),setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},location:{origin:'https://panel.ogretmencocuk.com',pathname:'/ingilizce/',search:'',replace(p){redirect=p}},history:{replaceState(){}},URL,URLSearchParams,fetch:async(url,opts)=>({json:async()=>{if(url.endsWith('/settings'))return {external:{google:true}};if(!opts)return {hazir:true};const body=JSON.parse(opts.body);requests.push(body);return body.islem==='googleGiris'?{baglantiGerekli:true,mesaj:'Verify account'}:signupOK?{ok:true,kayitOlustu:true,token:'portal-token',rol:'ogrenci',ogrenci:'Yeni Öğrenci'}:{ok:false,mesaj:'Kayıt reddedildi'}}})});
 await new Promise(r=>setImmediate(r));return {elements,win,local,requests,get redirect(){return redirect},get legacy(){return legacy},get oauth(){return oauth}};
}
test('unlinked Google account can select new signup without changing legacy password login',async()=>{const f=await fixture(),area=f.elements.loginForm.area;assert.equal(area.children[1].hidden,false);await area.children[1].onclick();assert.equal(f.elements.loginForm.hidden,true);assert.equal(area.children[2].hidden,false);assert.equal(f.elements.googleYeniAd.value,'Yeni Öğrenci');assert.equal(f.elements.googleYeniEmail.value,'');assert.equal(f.elements.googleYeniOnay.checked,false)});
test('signup posts guardian declaration and enters active portal session',async()=>{const f=await fixture(),area=f.elements.loginForm.area;await area.children[1].onclick();for(const [id,value] of Object.entries({googleYeniSinif:'5',googleYeniSube:'A',googleYeniTelefon:'05551234567',googleYeniEmail:'parent@example.test'}))f.elements[id].value=value;f.elements.googleYeniOnay.checked=true;await area.children[2].onsubmit({preventDefault(){}});assert.equal(f.requests.at(-1).islem,'googleKayit');assert.equal(f.requests.at(-1).kvkkOnay,true);assert.equal(f.local.get('ing_token'),'portal-token');assert.equal(f.redirect,'/ingilizce/')});
test('unchecked declaration sends no signup and rejection creates no portal session',async()=>{const f=await fixture({signupOK:false}),area=f.elements.loginForm.area;await area.children[1].onclick();await area.children[2].onsubmit({preventDefault(){}});assert.equal(f.requests.length,1);f.elements.googleYeniOnay.checked=true;await area.children[2].onsubmit({preventDefault(){}});assert.equal(f.local.has('ing_token'),false);assert.equal(f.elements.googleYeniMesaj.textContent,'Kayıt reddedildi')});
test('cancel restores legacy login and Google uses exact configured return URL',async()=>{const f=await fixture(),area=f.elements.loginForm.area;await area.children[1].onclick();await area.children[3].onclick();assert.equal(f.elements.loginForm.hidden,false);assert.equal(area.children[2].hidden,true);await f.win.girisYap({});assert.equal(f.legacy,1);await area.children[0].onclick();assert.equal(f.oauth.options.redirectTo,'https://panel.ogretmencocuk.com/ingilizce/')});
