const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('ingilizce/game-feedback.js','utf8').split('// Start speech in the click handler:')[1].split('\n').slice(1).join('\n').split("window.addEventListener('online'")[0];
function fixture(voices=[]){const spoken=[],messages=[],timers=[],events={};let active=false;
const synth={getVoices:()=>voices,addEventListener:(n,fn)=>events[n]=fn,cancel(){},resume(){},speak(u){assert(active,'speech must start inside tap');spoken.push(u);}};
const w={speechSynthesis:synth,SpeechSynthesisUtterance:class{constructor(text){this.text=text;}},yoToast:m=>messages.push(m)};
const ctx={window:w,document:{getElementById:()=>null,querySelector:()=>null},voiceGeneration:0,speechTimer:null,clearTimeout(){},setTimeout:fn=>{timers.push(fn);return timers.length;}};vm.createContext(ctx);vm.runInContext(source,ctx);
return {w,spoken,messages,timers,events,tapUtterance(u){active=true;w.speechSynthesis.speak(u);active=false;},tap(text,slow){active=true;w.dmListen(text,slow);active=false;}};}
test('Android tap starts speech synchronously even before voices load',()=>{const f=fixture();f.tap('book',false);assert.equal(f.spoken.length,1);assert.equal(f.spoken[0].lang,'en-US');assert.equal(f.spoken[0].rate,.85);assert.equal(f.spoken[0].volume,1);assert.equal(f.spoken[0].voice,null);});
test('slow button immediately replaces previous speech and suppresses stale errors',()=>{const f=fixture();f.tap('book');const first=f.spoken[0];f.tap('book',true);assert.equal(f.spoken[1].rate,.35);first.onerror({error:'synthesis-failed'});assert.equal(f.messages.length,0);});
test('voices arriving later are selected on next tap with local English preferred',()=>{const voices=[],f=fixture(voices);f.tap('book');voices.push({lang:'en-US',localService:false},{lang:'en-GB',localService:true});f.events.voiceschanged();f.tap('apple');assert.equal(f.spoken[1].voice,voices[1]);assert.equal(f.spoken[1].lang,'en-GB');});
test('blocked or unavailable audio reports recovery and cancellations stay silent',()=>{const f=fixture();f.tap('book');f.spoken[0].onerror({error:'not-allowed'});assert(f.messages.at(-1).includes('tekrar dokun'));f.tap('apple');f.spoken[1].onerror({error:'language-unavailable'});assert(f.messages.at(-1).includes('İngilizce'));const n=f.messages.length;f.spoken[1].onerror({error:'canceled'});assert.equal(f.messages.length,n);});
test('missing browser speech support and stalled engine show useful status',()=>{const f=fixture();f.tap('book');f.timers.at(-1)();assert(f.messages.at(-1).includes('Ses başlamadı'));delete f.w.speechSynthesis;f.tap('apple');assert(f.messages.at(-1).includes('desteklenmiyor'));});

test('cards and lessons using native speech share error recovery and preserve their reading speed',()=>{const f=fixture([{lang:'en-US',localService:true}]),u=new f.w.SpeechSynthesisUtterance('apple');u.lang='en-US';u.rate=.92;let called=false;u.onerror=()=>called=true;f.tapUtterance(u);assert.equal(f.spoken[0],u);assert.equal(u.rate,.92);assert.equal(u.voice.lang,'en-US');u.onerror({error:'synthesis-unavailable'});assert(called);assert(f.messages.at(-1).includes('İngilizce'));});
