begin;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();r jsonb;m uuid;mid uuid;qs jsonb;wrong boolean:=false;v jsonb;
begin
 insert into public.students(id,username,password_hash,status,class_no) values(a,'__dm_test_a','disabled_test_hash','approved',2),(b,'__dm_test_b','disabled_test_hash','approved',2),(c,'__dm_test_c','disabled_test_hash','approved',2);
 insert into public.extra_data(student_id,key_name,value) values(a,'yo','{"altin":1000,"karakter":{"cins":"e","sahip":[]}}'),(b,'yo','{"altin":1000,"karakter":{"cins":"e","sahip":[]}}');
 r:=public.dm_match_action(a,null,'create',jsonb_build_object('target',b,'game','ucus','mode','live'));m:=(r->>'id')::uuid;
 select questions into qs from public.dm_matches where id=m;
 if jsonb_array_length(qs)<>8 or exists(select from jsonb_array_elements(qs) q where not (q->'choices' ? (q->>'answer')) or jsonb_array_length(q->'choices')<>6) then raise exception 'Invalid questions';end if;
 r:=public.dm_match_action(a,m,'ready');if r->>'start' is not null then raise exception 'Started before both ready';end if;
 r:=public.dm_match_action(b,m,'ready');if r->>'start' is null then raise exception 'Live start missing';end if;
 begin perform public.dm_match_action(c,m,'state');raise exception 'UNAUTHORIZED ALLOWED';exception when others then if sqlerrm='UNAUTHORIZED ALLOWED' then raise;end if;end;
 update public.dm_matches set start_a=now()-interval '1 second',start_b=now()-interval '1 second' where id=m;
 r:=public.dm_match_action(a,m,'answer',jsonb_build_object('index',0,'choice',0));if not (r->>'answered')::boolean then raise exception 'Answer missing';end if;
 begin perform public.dm_match_action(a,m,'answer','{"index":0,"choice":1}');raise exception 'DUPLICATE ALLOWED';exception when others then if sqlerrm='DUPLICATE ALLOWED' then raise;end if;end;
 update public.dm_matches set start_a=now()-interval '97 seconds',start_b=now()-interval '97 seconds' where id=m;
 r:=public.dm_match_action(a,m,'state');if r->>'status'<>'finished' then raise exception 'Missing finish';end if;
 perform public.dm_match_action(b,m,'state');if (select count(*) from public.game_scores where extra->>'matchId'=m::text)<>2 then raise exception 'Reward duplicated';end if;
 r:=public.dm_match_action(a,null,'create',jsonb_build_object('target',b,'game','rota','mode','async'));mid:=(r->>'id')::uuid;
 r:=public.dm_match_action(a,mid,'ready');if r->>'start' is null then raise exception 'Async missing start';end if;
 r:=public.dm_match_action(b,mid,'state');if r->>'start' is not null then raise exception 'Async opponent incorrectly started';end if;
 r:=public.dm_social_action(a,b,'message','1');if not exists(select from public.notifications where sender_student_id=a and type='mesaj' and message='Beni takip eder misin? 🌟') then raise exception 'Preset missing';end if;
 begin perform public.dm_social_action(a,b,'message','99');raise exception 'INVALID PRESET ALLOWED';exception when others then if sqlerrm='INVALID PRESET ALLOWED' then raise;end if;end;
 select value into v from public.extra_data where student_id=a and key_name='yo';
 r:=public.dm_social_action(a,b,'gift','a:canta:#ef4444:duz');if (r#>>'{yo,altin}')::numeric<>(v->>'altin')::numeric-100 then raise exception 'Gift price wrong';end if;
 update public.extra_data set value=value where student_id=b and key_name='yo';if not exists(select from public.extra_data where student_id=b and value#>'{karakter,sahip}' ? 'd:a:canta:#ef4444:duz') then raise exception 'Gift missing';end if;
 insert into public.feed_events(student_id,target_student_id,event_type,payload) values(a,b,'takip','{}'),(b,a,'takip','{}');
 perform public.dm_social_action(a,b,'block');if not public.dm_blocked(b,a) then raise exception 'Reverse block missing';end if;
 if exists(select from public.feed_events where student_id in(a,b) and target_student_id in(a,b) and event_type='takip') then raise exception 'Follow cleanup missing';end if;
 if (select status from public.dm_matches where id=mid)<>'cancelled' then raise exception 'Match not cancelled';end if;
 begin perform public.dm_social_action(b,a,'message','0');raise exception 'BLOCK BYPASS';exception when others then if sqlerrm='BLOCK BYPASS' then raise;end if;end;
 begin insert into public.duels(sender_student_id,receiver_student_id) values(b,a);raise exception 'DUEL BLOCK BYPASS';exception when others then if sqlerrm='DUEL BLOCK BYPASS' then raise;end if;end;
 begin insert into public.feed_events(student_id,target_student_id,event_type) values(b,a,'takip');raise exception 'FOLLOW BLOCK BYPASS';exception when others then if sqlerrm='FOLLOW BLOCK BYPASS' then raise;end if;end;
 perform public.dm_social_action(a,b,'unblock');if public.dm_blocked(b,a) then raise exception 'Unblock failed';end if;
 r:=public.dm_duel_action(a,'create',jsonb_build_object('target',b,'game','Tren_Liderlik'));
 select id into mid from public.duels where sender_student_id=a and receiver_student_id=b order by created_at desc limit 1;
 perform public.dm_duel_action(b,'reply',jsonb_build_object('id',mid,'accept',true));
 r:=public.dm_classic_result(a,'Tren_Liderlik',800,20);if r->0->>'status'<>'accepted' then raise exception 'Classic finished too soon';end if;
 r:=public.dm_classic_result(b,'Tren_Liderlik',800,25);if r->0->>'status'<>'finished' or r->0->>'winner'<>'__dm_test_a' then raise exception 'Classic tie speed wrong';end if;
 r:=public.dm_duel_action(b,'list');if not exists(select from jsonb_array_elements(r->'liste') x where x->>'id'=mid::text and (x->>'benPuan')::numeric=800 and (x->>'rakipSure')::numeric=20) then raise exception 'Classic perspective wrong';end if;
 raise notice 'PASS: live sync, shared questions, authorization, answer replay, scoring, reward idempotency, async independence, preset allowlist, gifts, bidirectional blocks';
end $$;
rollback;
