const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{stripTypeScriptTypes}=require('node:module');
const src=fs.readFileSync(__dirname+'/../supabase/functions/diji-api/index.ts','utf8'),Async=Object.getPrototypeOf(async function(){}).constructor;
const block=src.slice(src.indexOf('  if (op === "kayitOl")'),src.indexOf('  if (op === "sifreDegistir")')).replace('ogretmen: any','ogretmen').replace('(payload as any)','payload');
const run=new Async('body','supabase','json','studentByName','denemeSay','denemeYaz','likeKacir','hashPassword','num','temizMetin','onboarding','const op="kayitOl";'+block);
function fixture(fail=false){const mails=[],writes=[];const db={from(t){return {select(){return this},ilike(){return this},eq(){return this},limit:async()=>({data:[]}),insert(p){writes.push(p);return this},single:async()=>({data:fail?null:{id:'new',username:'Yeni Öğrenci',email:'parent@example.test'},error:fail?{}:null})}}};return {mails,writes,call:b=>run(b,db,(data,status=200)=>({data,status}),async()=>null,async()=>0,async()=>{},s=>s,async()=> 'hash',Number,s=>s,{welcome:async s=>mails.push(s)})};}
const valid={ogrenciAdi:'Yeni Öğrenci',sifre:'secret',telefon:'05551234567',email:'parent@example.test',sinif:3,sube:'A',kvkkOnayTarihi:'2026-10-04T00:00:00Z'};
test('password signup waits for email and queues one welcome to guardian',async()=>{const f=fixture(),r=await f.call(valid);assert.equal(r.data.status,'success');assert.equal(f.writes[0].status,'pending');assert.equal(f.writes[0].email_verification_required,true);assert.equal(f.writes[0].email_verified_at,null);assert.equal(f.mails.length,1);assert.equal(f.mails[0].email,valid.email);assert.equal(r.data.token,undefined)});
test('failed account creation and missing declaration send no welcome',async()=>{for(const [f,b] of [[fixture(true),valid],[fixture(),{...valid,kvkkOnayTarihi:''}]]){assert.equal((await f.call(b)).data.status,'error');assert.equal(f.mails.length,0)}});
const queue=stripTypeScriptTypes(src.slice(src.indexOf('async function kuyrukSatiriGonder'),src.indexOf('/* Bekleyen e-postaları')),{mode:'transform'});
function sender(slot){const updates=[],calls=[];const db={rpc:async()=>({data:slot}),from(t){return {update(p){updates.push({t,p});return this},eq(){return this},is(){return this}}}};const fn=new Async('supabase','epostaGonder',queue+'return await kuyrukSatiriGonder(1,{student_id:"new",kind:"dogrulama",to_email:"parent@example.test"});');return {updates,calls,run:()=>fn(db,async()=>{calls.push(1);return {ok:true}})};}
test('daily quota defers without sending or exhausting retries',async()=>{const s=sender(false);assert.equal((await s.run()).ok,false);assert.equal(s.calls.length,0);assert(s.updates[0].p.send_after);assert.equal(s.updates[0].p.attempts,undefined)});
test('successful delayed welcome grants 24 hours from send time',async()=>{const s=sender(true);assert.equal((await s.run()).ok,true);assert.equal(s.calls.length,1);assert.equal(s.updates[0].t,'dm_email_verifications');assert(Date.parse(s.updates[0].p.expires_at)>Date.now()+86390000);assert(s.updates[1].p.sent_at)});
