const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module'),crypto=require('node:crypto').webcrypto;
const code=stripTypeScriptTypes(fs.readFileSync(__dirname+'/../supabase/functions/diji-api/onboarding-api.ts','utf8').replace("import {guestContent} from './guest-content.ts';",'').replace('export function','function'),{mode:'transform'});
function fixture(opts={}){const calls=[],sent=[];const db={rpc:async(name,arg)=>{calls.push({name,arg});return {data:name==='dm_email_issue'?7:name==='dm_email_verify'?{ok:!opts.invalid,mesaj:'verified'}:name==='dm_guest_lesson'?!opts.used:name==='dm_guest_claim'?{ok:!opts.used,mesaj:'used'}:{ok:!opts.expired,expiresAt:'2026-10-04T10:10:00Z',serverNow:'2026-10-04T10:00:00Z'},error:opts.rpcError?{message:'cooldown'}:null}},from(table){return {select(){return this},eq(){return this},order(){return this},limit:async()=>({data:[{english:'cat',turkish:'kedi'}]})}}};const ctx={crypto,guestContent:async()=>({words:[],topics:[],sentences:[]})};vm.createContext(ctx);vm.runInContext(code+';globalThis.factory=onboardingAPI',ctx);const api=ctx.factory({db,json:(data,status=200)=>({data,status}),hash:async s=>require('node:crypto').createHash('sha256').update(s).digest('hex'),studentByName:async()=>opts.missing?null:{id:'actor',username:'Student',email:'parent@example.test',status:'pending',email_verification_required:!opts.legacy,password_hash:'hash'},verifyPassword:async p=>p==='secret',attempts:async()=>opts.rate?5:0,audit:async()=>{},sendQueued:async(id,m)=>sent.push({id,m}),mailShell:(_,x)=>x,escape:x=>String(x).replace(/</g,'&lt;')});return {api,calls,sent,run:(op,b={},method='POST')=>api.handle(new Request('https://test',{method}),op,b)};}
test('welcome uses one combined verification email with 24h link and hash-only RPC',async()=>{const f=fixture();await f.api.welcome({id:'actor',username:'<student>',email:'parent@example.test'});assert.equal(f.sent.length,1);assert.match(f.sent[0].m.html,/Hoş|hoş/);assert.match(f.sent[0].m.html,/&lt;student>/);assert.match(f.sent[0].m.text_body,/hesap-dogrula.html#token=/);const args=f.calls[0].arg;assert.match(args.digest,/^[a-f0-9]{64}$/);assert.equal(args.actor,'actor');});
test('verification requires POST, valid token and never creates login session',async()=>{let f=fixture();assert.equal((await f.run('emailDogrula',{},'GET')).status,405);assert.equal((await f.run('emailDogrula',{token:'bad'})).status,400);assert.equal(f.calls.length,0);f=fixture({invalid:true});assert.equal((await f.run('emailDogrula',{token:'a'.repeat(72)})).status,400);assert.deepEqual(f.calls.map(x=>x.name),['dm_email_verify']);});
test('resend requires password, new pending account and respects attempt and issuance limits',async()=>{for(const opts of [{legacy:true},{missing:true},{rate:true}]){const f=fixture(opts);assert.notEqual((await f.run('emailDogrulamaTekrar',{ogrenci:'Student',sifre:'secret'})).status,200);assert.equal(f.sent.length,0);}const f=fixture();assert.equal((await f.run('emailDogrulamaTekrar',{ogrenci:'Student',sifre:'bad'})).status,400);assert.equal((await f.run('emailDogrulamaTekrar',{ogrenci:'Student',sifre:'secret'})).status,200);assert.equal(f.sent.length,1);});
test('expired guests cannot fetch word bank and valid guests receive only learning content',async()=>{let f=fixture({expired:true});const b={device:'12345678-1234-4234-8234-123456789012',sinif:3,unite:1};assert.equal((await f.run('misafirIcerik',b)).status,410);f=fixture();const r=await f.run('misafirIcerik',b);assert.equal(r.status,200);assert.equal(r.data.words[0].en,'cat');assert.equal((await f.run('misafirIcerik',{...b,sinif:9})).status,400);assert.equal((await f.run('misafirBaslat',{device:'bad'})).status,400);});

test('platform content and claims reject expired guests before data access',async()=>{const f=fixture({expired:true});for(const kind of ['bootstrap','lesson','claim'])assert.equal((await f.run('misafirPlatform',{device:'a'.repeat(36),kind,feature:'hafiza'})).status,410);assert(f.calls.every(c=>c.name==='dm_guest_preview'));});
test('used feature and second topic deny access while bootstrap stays available',async()=>{const f=fixture({used:true});for(const b of [{kind:'claim',feature:'hafiza'},{kind:'lesson',seviye:'A1',kategori:'grammar',konu:'Second'}])assert.equal((await f.run('misafirPlatform',{device:'a'.repeat(36),...b})).status,409);assert.equal((await f.run('misafirPlatform',{device:'a'.repeat(36),kind:'bootstrap'})).status,200);assert.equal((await f.run('misafirPlatform',{device:'a'.repeat(36),kind:'adminWrite'})).status,403);});
