const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{stripTypeScriptTypes}=require('node:module');
const C=require('../ingilizce/progression-catalog.js');
function fixture(level=7){let ctx={level,feed:false,lessons:{A1:true,A2:false,B1:false,B2:false},units:[[1101,1102],[1301],[1501],[1701]],complete:[false,false,false,false],done:[],yo:{karakter:{cins:'k',s:{},sahip:[]}},owned:[]};const db={rpc:async()=>({data:ctx}),from:()=>({select(){return this},eq(){return this},limit:async()=>({data:[{id:'lesson'}]})})};const scope={DijiProgressionCatalog:C,globalThis:null,items:[],Intl,Date,Set,JSON};scope.globalThis=scope;vm.createContext(scope);let src=stripTypeScriptTypes(fs.readFileSync('supabase/functions/diji-api/progression-api.ts','utf8').replace(/^import .*$/gm,''),{mode:'transform'}).replace('export function','function');vm.runInContext(src+';this.factory=progressionAPI',scope);return {api:scope.factory(db,(body,status=200)=>({body,status})),ctx};}
const student={role:'student',student_id:'trusted'};
test('level 7 server denies later games, store, social actions and forged state',async()=>{const {api,ctx}=fixture();for(const op of ['asmacaLiderlikKaydet','dikteLiderlikKaydet','enerjiGonder','hazirMesajGonder','duelloGonder','oyunEslesmeOlustur'])assert.equal((await api.guard(op,{},new URLSearchParams(),student)).status,403,op);assert.equal(await api.guard('hafizaLiderlikKaydet',{},new URLSearchParams(),student),null);assert.equal((await api.guard('akisTumu',{},new URLSearchParams(),student)).status,403);ctx.feed=true;assert.equal(await api.guard('akisTumu',{},new URLSearchParams(),student),null);assert.equal((await api.guard('ekVeriKaydet',{anahtar:'yo',deger:{karakter:{cins:'k',s:{ust:'fake'},sahip:['d:fake']}}},new URLSearchParams(),student)).status,403);});
test('lesson minimum level and previous CEFR completion are both required',async()=>{const {api,ctx}=fixture(9),body={seviye:'A2',kategori:'Grammar',konu:'Topic'};assert.equal((await api.guard('dersKonuDetayGetir',body,new URLSearchParams(),student)).status,403);ctx.lessons.A2=true;assert.equal(await api.guard('dersKonuDetayGetir',body,new URLSearchParams(),student),null);ctx.level=8;assert.equal((await api.guard('dersKonuDetayGetir',body,new URLSearchParams(),student)).status,403);});
test('parkur doors require level, previous door and previous stop',async()=>{const {api,ctx}=fixture(10);assert.equal((await api.guard('buyuSeviyeTamamla',{seviyeNo:1301},new URLSearchParams(),student)).status,403);ctx.complete[0]=true;assert.equal(await api.guard('buyuSeviyeTamamla',{seviyeNo:1301},new URLSearchParams(),student),null);assert.equal((await api.guard('buyuSeviyeTamamla',{seviyeNo:1102},new URLSearchParams(),student)).status,403);ctx.done=[1101];assert.equal(await api.guard('buyuSeviyeTamamla',{seviyeNo:1102},new URLSearchParams(),student),null);});
test('40 level names, next features, joker quotas and shop boundaries',()=>{assert.equal(C.levels.length,40);assert(C.levels.every(x=>x.name&&x.benefits.length));assert.deepEqual([14,15,19,20,29,30,40].map(C.quota),[0,1,1,2,2,3,3]);assert.equal(C.itemLevel({kat:'ust',tip:'tisort',sv:'temel'}),15);assert.equal(C.itemLevel({kat:'ust',tip:'sweat',sv:'ozel'}),25);assert.equal(C.itemLevel({kat:'bas',sv:'temel'}),32);assert.equal(C.itemLevel({parca:[]}),35);assert.equal(C.gates.oyun_yagmur,28);assert.equal(C.gold(40),100);});
test('existing inventory is accepted intact, new ownership uses atomic purchase only',async()=>{const {api,ctx}=fixture(15);ctx.yo.karakter.sahip=['d:owned'];const body={anahtar:'yo',deger:JSON.stringify(ctx.yo)};assert.equal(await api.guard('ekVeriKaydet',body,new URLSearchParams(),student),null);body.deger=JSON.stringify({...ctx.yo,karakter:{...ctx.yo.karakter,sahip:['d:owned','d:forged']}});assert.equal((await api.guard('ekVeriKaydet',body,new URLSearchParams(),student)).status,403);});
test('frontend and both API catalogs remain identical',()=>{const a=fs.readFileSync('ingilizce/progression-catalog.js');for(const dir of ['diji-api','medupro-api'])assert.deepEqual(a,fs.readFileSync('supabase/functions/'+dir+'/progression-catalog.js'));});

test('MeduPro word-mode routes enforce level 10 on the server',async()=>{const {api,ctx}=fixture(2);for(const op of ['konusmaSeviyeIlerlemeGetir','konusmaSeviyeTamamla','konusmaLiderlikKaydet'])assert.equal((await api.guard(op,{},new URLSearchParams(),student)).status,403);ctx.level=10;assert.equal(await api.guard('konusmaSeviyeIlerlemeGetir',{},new URLSearchParams(),student),null);});

test('reward claims reject locked games and anonymous sessions',async()=>{const {api}=fixture(7);assert.equal((await api.handle('seviyeOyunOdulu',{game:'dikte'},new URLSearchParams(),student)).status,403);assert.equal((await api.handle('seviyeOyunOdulu',{game:'ky'},new URLSearchParams(),null)).status,401);});
