const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.DIJI_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage(),errors=[],outside=[],claimed=new Set();
 page.on('pageerror',e=>errors.push(e.message));
 const words=[['cat','kedi'],['dog','köpek'],['book','kitap'],['apple','elma']].map(([en,tr])=>({sinif:3,unite:1,ingilizce:en,turkce:tr}));
 await ctx.addInitScript(()=>{window.Chart=function(){this.destroy=()=>{};this.update=()=>{};};});
 await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='nxfqlutulxqzqgwewssd.supabase.co'){let b=r.request().method()==='POST'?r.request().postDataJSON():{};let d={ok:true,serverNow:new Date().toISOString(),expiresAt:new Date(Date.now()+600000).toISOString()};if(b.kind==='claim'){if(claimed.has(b.feature))d.ok=false;else claimed.add(b.feature);}if(b.kind==='bootstrap')d.data={words,topics:[],sentences:[],cards:[{sinif:3,unite:1,seviye:1,butonAdi:'Seviye 1',disLink:'https://www.vocablitz.com/deck/ogretmencocuk/search?id=26821&view=test'}]};return r.fulfill({contentType:'application/json',body:JSON.stringify(d)});}
 if(u.hostname==='cdn.jsdelivr.net'&&u.pathname.includes('supabase'))return r.fulfill({contentType:'application/javascript',body:'window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})}})};'});
 if(u.hostname==='diji.test'){const f=path.join(__dirname,'..',u.pathname.replace(/^\//,'').replace(/\/$/,'/index.html'));if(fs.existsSync(f))return r.fulfill({path:f});}
 if(/vocablitz|tinytap|baamboozle|eslgamesplus/.test(u.hostname))outside.push(u.hostname);return r.fulfill({contentType:'application/json',body:'[]'});});
 await page.goto('https://diji.test/ingilizce/?misafir=1');await page.locator('#dmGuestBar').waitFor();await page.waitForFunction(()=>window.masterKelimeHavuzu?.length===4&&typeof aktifOgrenciAdi!=='undefined'&&aktifOgrenciAdi==='Misafir'&&globalDataCache?.[0]?.aktiviteKartlari?.length); await page.locator('#dmGuestTip>button').click();
 await page.evaluate(()=>seviyeDisLinkAc(3,1,1)); const frame=page.frameLocator('#seviyeDisLinkIframe');await frame.locator('h2').waitFor();assert.equal(await frame.locator('h2').textContent(),'cat');await frame.locator('[data-flip]').click();assert.match(await frame.locator('#card').textContent(),/kedi/);
 await frame.locator('[data-mode="sec"]').click();await frame.locator('[data-answer="kedi"]').click();assert.match(await frame.locator('#status').textContent(),/Doğru/);
 await frame.locator('[data-mode="yaz"]').click();await frame.locator('#answer').fill('cat');await frame.locator('[data-check]').click();assert.match(await frame.locator('#status').textContent(),/Doğru/);assert.equal(outside.length,0);
 const box=await frame.locator('main').boundingBox();assert(box.width<=390);await page.screenshot({path:'/tmp/diji-original-wordcards.png'});
 await page.evaluate(()=>{disLinkIframeYukle('https://www.tinytap.com/example');document.getElementById('disLinkOverlay').style.display='flex';});assert.match(await page.locator('#disLinkEngelliUyari').first().textContent(),/www.tinytap.com/);assert.equal(await page.locator('#disLinkEngelliUyari a').first().getAttribute('rel'),'noopener noreferrer');assert.equal(outside.length,0);assert.equal(await page.locator('#disLinkIframe').first().getAttribute('src'),'about:blank');
 for(const file of ['kullanim-kosullari.html','telif.html','lisanslar.html']){const tab=await ctx.newPage();await tab.goto('https://diji.test/ingilizce/'+file);assert((await tab.locator('h1').textContent()).length>0);assert.equal(await tab.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),true);await tab.close();}
 assert.equal(errors.length,0,errors.join('\n'));await browser.close();console.log('PASS original wordcards, all three modes, mobile width, zero external game requests, provider disclosure and legal pages');
})().catch(e=>{console.error(e);process.exit(1)});
