-- Schema-only snapshot for local destructive-operation tests. No production rows.
create table public."activities" (
"id" uuid default gen_random_uuid() not null,
"code" text not null,
"display_name" text not null,
"category" text,
"external_link" text,
"teacher_comment" text,
"active" boolean default true not null,
"content" jsonb default '{}'::jsonb not null
);
create table public."activity_categories" (
"id" bigint generated by default as identity not null,
"name" text not null
);
create table public."announcement_reads" (
"id" uuid default gen_random_uuid() not null,
"announcement_id" uuid not null,
"student_id" uuid not null,
"seen_at" timestamp with time zone default now() not null
);
create table public."announcements" (
"id" uuid default gen_random_uuid() not null,
"title" text not null,
"message" text not null,
"image_link" text,
"target_type" text default 'all'::text not null,
"target_list" jsonb default '[]'::jsonb not null,
"display_limit" integer,
"theme" text,
"active" boolean default true not null,
"created_at" timestamp with time zone default now() not null,
"teacher_id" uuid
);
create table public."annual_plans" (
"id" uuid default gen_random_uuid() not null,
"plan_code" text not null,
"title" text,
"total_weeks" integer default 0 not null,
"plan_data" jsonb default '[]'::jsonb not null,
"active" boolean default true not null
);
create table public."assignment_status" (
"assignment_id" bigint not null,
"student_id" uuid not null,
"done_at" timestamp with time zone default now() not null,
"score" integer,
"stars" integer
);
create table public."assignments" (
"id" bigint generated by default as identity not null,
"teacher_id" uuid,
"class_no" integer not null,
"branch" text default ''::text not null,
"kind" text not null,
"title" text not null,
"payload" jsonb default '{}'::jsonb not null,
"due_date" date,
"note" text,
"active" boolean default true not null,
"created_at" timestamp with time zone default now() not null
);
create table public."audit_logs" (
"id" uuid default gen_random_uuid() not null,
"actor_role" text,
"actor_id" uuid,
"operation" text,
"target" text,
"payload" jsonb default '{}'::jsonb not null,
"created_at" timestamp with time zone default now() not null
);
create table public."badges" (
"id" bigint generated by default as identity not null,
"student_name" text,
"name" text not null,
"required_points" numeric default 0,
"emoji" text default '🏅'::text
);
create table public."chat_messages" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid,
"sender_role" text not null,
"message" text not null,
"read_at" timestamp with time zone,
"created_at" timestamp with time zone default now() not null
);
create table public."class_point_actions" (
"id" uuid default gen_random_uuid() not null,
"teacher_id" uuid,
"student_ids" jsonb not null,
"change_amount" numeric(6,2) not null,
"reason" text,
"action_at" timestamp with time zone default now() not null,
"undone_at" timestamp with time zone
);
create table public."duels" (
"id" uuid default gen_random_uuid() not null,
"sender_student_id" uuid,
"receiver_student_id" uuid,
"status" text default 'pending'::text not null,
"sender_payload" jsonb default '{}'::jsonb not null,
"receiver_payload" jsonb default '{}'::jsonb not null,
"created_at" timestamp with time zone default now() not null,
"responded_at" timestamp with time zone
);
create table public."energy_transactions" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"change_amount" integer not null,
"balance_after" integer not null,
"reason" text,
"created_at" timestamp with time zone default now() not null
);
create table public."extra_data" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid,
"key_name" text not null,
"value" jsonb default '{}'::jsonb not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."feature_flags" (
"id" uuid default gen_random_uuid() not null,
"code" text not null,
"name" text,
"target_type" text default 'tumogrenciler'::text not null,
"target_value" text,
"enabled" boolean default false not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."feed_events" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid,
"event_type" text not null,
"target_student_id" uuid,
"payload" jsonb default '{}'::jsonb not null,
"created_at" timestamp with time zone default now() not null
);
create table public."feed_reactions" (
"id" uuid default gen_random_uuid() not null,
"event_id" uuid not null,
"student_id" uuid not null,
"reaction" text not null,
"created_at" timestamp with time zone default now() not null
);
create table public."follow_edges" (
"id" uuid default gen_random_uuid() not null,
"follower_student_id" uuid not null,
"following_student_id" uuid not null,
"created_at" timestamp with time zone default now() not null
);
create table public."game_scores" (
"id" uuid default gen_random_uuid() not null,
"game_key" text not null,
"student_id" uuid,
"student_name" text not null,
"class_no" integer,
"unit_no" integer,
"unit_name" text,
"score" numeric default 0 not null,
"correct_count" integer default 0 not null,
"wrong_count" integer default 0 not null,
"duration_seconds" integer default 0 not null,
"detail" text,
"played_on" date default CURRENT_DATE not null,
"created_at" timestamp with time zone default now() not null,
"extra" jsonb default '{}'::jsonb not null
);
create table public."legacy_import_rows" (
"id" uuid default gen_random_uuid() not null,
"sheet_name" text not null,
"source_row_no" integer not null,
"source_headers" jsonb not null,
"source_row" jsonb not null,
"imported_at" timestamp with time zone default now() not null
);
create table public."legacy_unmapped_rows" (
"id" uuid default gen_random_uuid() not null,
"sheet_name" text not null,
"source_row" integer not null,
"source_row_data" jsonb not null,
"created_at" timestamp with time zone default now()
);
create table public."lesson_progress" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"level" text,
"category" text,
"topic_name" text,
"knew_it" boolean,
"test_success" boolean,
"completed_at" timestamp with time zone default now() not null,
"extra" jsonb default '{}'::jsonb not null
);
create table public."lesson_topics" (
"id" uuid default gen_random_uuid() not null,
"level" text not null,
"category" text not null,
"topic_name" text not null,
"sort_no" integer default 0 not null,
"content" jsonb default '{}'::jsonb not null,
"active" boolean default true not null
);
create table public."level_completions" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"mode" text not null,
"class_no" integer,
"unit_no" integer,
"level_no" integer not null,
"completed_at" timestamp with time zone default now() not null
);
create table public."mail_queue" (
"id" bigint generated by default as identity not null,
"student_id" uuid,
"to_email" text not null,
"subject" text not null,
"html" text,
"text_body" text,
"kind" text default 'bilgi'::text not null,
"report_date" date,
"send_after" timestamp with time zone default now(),
"created_at" timestamp with time zone default now(),
"sent_at" timestamp with time zone,
"attempts" integer default 0,
"error" text
);
create table public."notifications" (
"id" uuid default gen_random_uuid() not null,
"recipient_student_id" uuid,
"sender_student_id" uuid,
"type" text,
"title" text,
"message" text,
"payload" jsonb default '{}'::jsonb not null,
"read_at" timestamp with time zone,
"created_at" timestamp with time zone default now() not null
);
create table public."points_transactions" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"change_amount" numeric(6,2) not null,
"balance_after" numeric(6,2) not null,
"reason" text,
"unique_key" text,
"created_at" timestamp with time zone default now() not null,
"auto_key" text
);
create table public."portal_sessions" (
"id" uuid default gen_random_uuid() not null,
"token_hash" text not null,
"student_id" uuid,
"teacher_id" uuid,
"role" text not null,
"created_at" timestamp with time zone default now() not null,
"expires_at" timestamp with time zone not null,
"last_seen_at" timestamp with time zone default now() not null
);
create table public."reading_results" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid,
"class_label" text,
"words_read" integer default 0 not null,
"duration_seconds" integer default 0 not null,
"wpm" numeric default 0 not null,
"text_title" text,
"created_at" timestamp with time zone default now() not null
);
create table public."sentence_bank" (
"id" bigint generated by default as identity not null,
"class_no" integer not null,
"unit_no" integer not null,
"turkish" text not null,
"english" text not null,
"alternatives" text default ''::text,
"distractors" text default ''::text,
"active" boolean default true,
"created_at" timestamp with time zone default now()
);
create table public."speech_synonyms" (
"id" bigint generated by default as identity not null,
"english" text not null,
"turkish" text,
"alternatives" text not null
);
create table public."student_activities" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"activity_id" uuid,
"assigned_by" uuid,
"status" text default 'assigned'::text not null,
"assigned_at" timestamp with time zone default now() not null,
"completed_at" timestamp with time zone,
"result" jsonb default '{}'::jsonb not null
);
create table public."student_plan_progress" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"plan_id" uuid not null,
"week_no" integer not null,
"completed" boolean default false not null,
"updated_at" timestamp with time zone default now() not null
);
create table public."student_videos" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"video_id" uuid not null,
"watched_at" timestamp with time zone,
"assigned_at" timestamp with time zone default now() not null
);
create table public."student_xp_weekly" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid not null,
"student_name" text not null,
"week_code" text not null,
"total_xp" numeric default 0 not null,
"week_xp" numeric default 0 not null,
"previous_week_xp" numeric default 0 not null,
"gold" numeric default 0 not null,
"freeze_count" integer default 0 not null,
"unlocked_character_count" integer default 0 not null,
"source_updated_at" timestamp with time zone,
"imported_at" timestamp with time zone default now() not null
);
create table public."students" (
"id" uuid default gen_random_uuid() not null,
"username" text not null,
"password_hash" text not null,
"phone" text,
"class_no" integer,
"branch" text,
"email" text,
"status" text default 'pending'::text not null,
"role" text default 'student'::text not null,
"kvkk_approved_at" timestamp with time zone,
"created_at" timestamp with time zone default now() not null,
"updated_at" timestamp with time zone default now() not null,
"last_login_at" timestamp with time zone,
"selected_class" integer,
"total_seconds" integer default 0 not null,
"energy" integer default 10 not null,
"energy_max" integer default 30 not null,
"streak" integer default 0 not null,
"points" numeric(6,2) default 0 not null,
"gold" numeric default 0 not null,
"xp" numeric default 0 not null,
"profile" jsonb default '{}'::jsonb not null,
"energy_updated_at" timestamp with time zone default now(),
"teacher_id" uuid
);
create table public."teacher_reports" (
"id" uuid default gen_random_uuid() not null,
"student_id" uuid,
"report_date" date default CURRENT_DATE not null,
"reading_score" numeric,
"writing_score" numeric,
"vocabulary_score" numeric,
"speaking_score" numeric,
"grammar_score" numeric,
"genel_score" numeric(5,1),
"exam_score" numeric(5,1),
"teacher_id" uuid,
"next_report_date" date,
"book_name" text,
"page_no" integer default 0,
"target" numeric default 40,
"read_count" integer default 0,
"last_attempt" boolean default false,
"homework_feedback" text,
"next_homework" text
);
create table public."teachers" (
"id" uuid default gen_random_uuid() not null,
"username" text not null,
"password_hash" text not null,
"display_name" text default 'Diji-Medu'::text not null,
"active" boolean default true not null,
"created_at" timestamp with time zone default now() not null,
"last_login_at" timestamp with time zone,
"email" text,
"full_name" text,
"school" text,
"invite_code" text,
"is_admin" boolean default false not null,
"game_data" jsonb,
"game_data_at" timestamp with time zone
);
create table public."videos" (
"id" uuid default gen_random_uuid() not null,
"external_row_index" integer,
"title" text,
"category" text,
"url" text,
"description" text,
"active" boolean default true not null,
"content" jsonb default '{}'::jsonb not null
);
create table public."word_bank" (
"id" uuid default gen_random_uuid() not null,
"class_no" integer not null,
"unit_no" integer not null,
"english" text not null,
"turkish" text not null,
"extra" jsonb default '{}'::jsonb not null,
"active" boolean default true not null
);
create table public."word_cards" (
"id" bigint generated by default as identity not null,
"class_no" integer not null,
"unit_no" integer not null,
"level_no" integer not null,
"button_name" text default ''::text,
"external_link" text not null
);
alter table public."feature_flags" add constraint "feature_flags_pkey" PRIMARY KEY (id);
alter table public."teachers" add constraint "teachers_pkey" PRIMARY KEY (id);
alter table public."teachers" add constraint "teachers_username_key" UNIQUE (username);
alter table public."activities" add constraint "activities_pkey" PRIMARY KEY (id);
alter table public."activities" add constraint "activities_code_key" UNIQUE (code);
alter table public."student_activities" add constraint "student_activities_pkey" PRIMARY KEY (id);
alter table public."students" add constraint "students_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'inactive'::text])));
alter table public."students" add constraint "students_role_check" CHECK ((role = ANY (ARRAY['student'::text, 'teacher'::text])));
alter table public."students" add constraint "students_pkey" PRIMARY KEY (id);
alter table public."students" add constraint "students_username_key" UNIQUE (username);
alter table public."portal_sessions" add constraint "portal_sessions_role_check" CHECK ((role = ANY (ARRAY['student'::text, 'teacher'::text])));
alter table public."portal_sessions" add constraint "portal_sessions_pkey" PRIMARY KEY (id);
alter table public."portal_sessions" add constraint "portal_sessions_token_hash_key" UNIQUE (token_hash);
alter table public."word_bank" add constraint "word_bank_pkey" PRIMARY KEY (id);
alter table public."lesson_topics" add constraint "lesson_topics_pkey" PRIMARY KEY (id);
alter table public."lesson_progress" add constraint "lesson_progress_pkey" PRIMARY KEY (id);
alter table public."game_scores" add constraint "game_scores_pkey" PRIMARY KEY (id);
alter table public."energy_transactions" add constraint "energy_transactions_pkey" PRIMARY KEY (id);
alter table public."points_transactions" add constraint "points_transactions_pkey" PRIMARY KEY (id);
alter table public."extra_data" add constraint "extra_data_pkey" PRIMARY KEY (id);
alter table public."extra_data" add constraint "extra_data_student_id_key_name_key" UNIQUE (student_id, key_name);
alter table public."notifications" add constraint "notifications_pkey" PRIMARY KEY (id);
alter table public."announcements" add constraint "announcements_pkey" PRIMARY KEY (id);
alter table public."announcement_reads" add constraint "announcement_reads_pkey" PRIMARY KEY (id);
alter table public."announcement_reads" add constraint "announcement_reads_announcement_id_student_id_key" UNIQUE (announcement_id, student_id);
alter table public."videos" add constraint "videos_pkey" PRIMARY KEY (id);
alter table public."videos" add constraint "videos_external_row_index_key" UNIQUE (external_row_index);
alter table public."student_videos" add constraint "student_videos_pkey" PRIMARY KEY (id);
alter table public."student_videos" add constraint "student_videos_student_id_video_id_key" UNIQUE (student_id, video_id);
alter table public."annual_plans" add constraint "annual_plans_pkey" PRIMARY KEY (id);
alter table public."annual_plans" add constraint "annual_plans_plan_code_key" UNIQUE (plan_code);
alter table public."student_plan_progress" add constraint "student_plan_progress_pkey" PRIMARY KEY (id);
alter table public."student_plan_progress" add constraint "student_plan_progress_student_id_plan_id_week_no_key" UNIQUE (student_id, plan_id, week_no);
alter table public."reading_results" add constraint "reading_results_pkey" PRIMARY KEY (id);
alter table public."teacher_reports" add constraint "teacher_reports_pkey" PRIMARY KEY (id);
alter table public."chat_messages" add constraint "chat_messages_sender_role_check" CHECK ((sender_role = ANY (ARRAY['student'::text, 'teacher'::text])));
alter table public."chat_messages" add constraint "chat_messages_pkey" PRIMARY KEY (id);
alter table public."duels" add constraint "duels_pkey" PRIMARY KEY (id);
alter table public."follow_edges" add constraint "follow_edges_pkey" PRIMARY KEY (id);
alter table public."follow_edges" add constraint "follow_edges_follower_student_id_following_student_id_key" UNIQUE (follower_student_id, following_student_id);
alter table public."feed_events" add constraint "feed_events_pkey" PRIMARY KEY (id);
alter table public."feed_reactions" add constraint "feed_reactions_pkey" PRIMARY KEY (id);
alter table public."feed_reactions" add constraint "feed_reactions_event_id_student_id_key" UNIQUE (event_id, student_id);
alter table public."level_completions" add constraint "level_completions_pkey" PRIMARY KEY (id);
alter table public."level_completions" add constraint "level_completions_student_id_mode_class_no_unit_no_level_no_key" UNIQUE (student_id, mode, class_no, unit_no, level_no);
alter table public."class_point_actions" add constraint "class_point_actions_pkey" PRIMARY KEY (id);
alter table public."audit_logs" add constraint "audit_logs_pkey" PRIMARY KEY (id);
alter table public."legacy_import_rows" add constraint "legacy_import_rows_pkey" PRIMARY KEY (id);
alter table public."legacy_import_rows" add constraint "legacy_import_rows_sheet_name_source_row_no_key" UNIQUE (sheet_name, source_row_no);
alter table public."legacy_unmapped_rows" add constraint "legacy_unmapped_rows_pkey" PRIMARY KEY (id);
alter table public."legacy_unmapped_rows" add constraint "legacy_unmapped_rows_sheet_name_source_row_key" UNIQUE (sheet_name, source_row);
alter table public."student_xp_weekly" add constraint "student_xp_weekly_pkey" PRIMARY KEY (id);
alter table public."student_xp_weekly" add constraint "student_xp_weekly_student_id_week_code_key" UNIQUE (student_id, week_code);
alter table public."word_cards" add constraint "word_cards_pkey" PRIMARY KEY (id);
alter table public."badges" add constraint "badges_pkey" PRIMARY KEY (id);
alter table public."speech_synonyms" add constraint "speech_synonyms_pkey" PRIMARY KEY (id);
alter table public."activity_categories" add constraint "activity_categories_pkey" PRIMARY KEY (id);
alter table public."activity_categories" add constraint "activity_categories_name_key" UNIQUE (name);
alter table public."mail_queue" add constraint "mail_queue_pkey" PRIMARY KEY (id);
alter table public."sentence_bank" add constraint "sentence_bank_pkey" PRIMARY KEY (id);
alter table public."assignments" add constraint "assignments_kind_check" CHECK ((kind = ANY (ARRAY['ders'::text, 'oyun'::text])));
alter table public."assignments" add constraint "assignments_pkey" PRIMARY KEY (id);
alter table public."assignment_status" add constraint "assignment_status_pkey" PRIMARY KEY (assignment_id, student_id);
alter table public."announcement_reads" add constraint "announcement_reads_announcement_id_fkey" FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE;
alter table public."announcement_reads" add constraint "announcement_reads_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."portal_sessions" add constraint "portal_sessions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."portal_sessions" add constraint "portal_sessions_teacher_id_fkey" FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE CASCADE;
alter table public."lesson_progress" add constraint "lesson_progress_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."game_scores" add constraint "game_scores_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL;
alter table public."energy_transactions" add constraint "energy_transactions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."points_transactions" add constraint "points_transactions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."extra_data" add constraint "extra_data_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_recipient_student_id_fkey" FOREIGN KEY (recipient_student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."notifications" add constraint "notifications_sender_student_id_fkey" FOREIGN KEY (sender_student_id) REFERENCES students(id) ON DELETE SET NULL;
alter table public."student_activities" add constraint "student_activities_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."student_activities" add constraint "student_activities_activity_id_fkey" FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE;
alter table public."student_activities" add constraint "student_activities_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES teachers(id) ON DELETE SET NULL;
alter table public."student_videos" add constraint "student_videos_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."student_videos" add constraint "student_videos_video_id_fkey" FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE;
alter table public."student_plan_progress" add constraint "student_plan_progress_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."student_plan_progress" add constraint "student_plan_progress_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES annual_plans(id) ON DELETE CASCADE;
alter table public."reading_results" add constraint "reading_results_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."teacher_reports" add constraint "teacher_reports_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."chat_messages" add constraint "chat_messages_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."duels" add constraint "duels_sender_student_id_fkey" FOREIGN KEY (sender_student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."duels" add constraint "duels_receiver_student_id_fkey" FOREIGN KEY (receiver_student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."follow_edges" add constraint "follow_edges_follower_student_id_fkey" FOREIGN KEY (follower_student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."follow_edges" add constraint "follow_edges_following_student_id_fkey" FOREIGN KEY (following_student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."feed_events" add constraint "feed_events_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."feed_events" add constraint "feed_events_target_student_id_fkey" FOREIGN KEY (target_student_id) REFERENCES students(id) ON DELETE SET NULL;
alter table public."feed_reactions" add constraint "feed_reactions_event_id_fkey" FOREIGN KEY (event_id) REFERENCES feed_events(id) ON DELETE CASCADE;
alter table public."feed_reactions" add constraint "feed_reactions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."level_completions" add constraint "level_completions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."class_point_actions" add constraint "class_point_actions_teacher_id_fkey" FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE SET NULL;
alter table public."student_xp_weekly" add constraint "student_xp_weekly_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
alter table public."assignment_status" add constraint "assignment_status_assignment_id_fkey" FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE CASCADE;
alter table public."students" add constraint "students_teacher_id_fkey" FOREIGN KEY (teacher_id) REFERENCES teachers(id) ON DELETE SET NULL;
