const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module');
function moduleFactory(file,name,db){const ctx={Date,Map,Set};vm.createContext(ctx);const code=stripTypeScriptTypes(fs.readFileSync('supabase/functions/diji-api/'+file,'utf8'),{mode:'transform'}).replace('export function','function');vm.runInContext(code+';this.factory='+name,ctx);return ctx.factory(db,(data,status=200)=>({data,status}),async p=>'pbkdf2$210000$hash$'+p);}
const owner={role:'teacher',teacher_id:'owner',yonetici:true,ogretmenKullanici:'teacher'},teacher={role:'teacher',teacher_id:'other',yonetici:false,ogretmenKullanici:'other'},student={role:'student',student_id:'student'},q=new URLSearchParams();
test('only owner can list or edit, including other administrator denial',async()=>{let calls=0;const db={rpc:()=>{calls++;throw Error('unexpected');},from:()=>{calls++;throw Error('unexpected');}};const api=moduleFactory('admin-students-api.ts','adminStudentsAPI',db);for(const a of [null,student,teacher,{...teacher,yonetici:true}])for(const op of ['yoneticiOgrenciler','yoneticiOgrenciKaydet'])assert.equal((await api.handle(op,{},q,a,'POST')).status,403);assert.equal(calls,0);});
test('teacher creation uses trusted actor, approved RPC and hashes, never returns credentials',async()=>{let args;const db={rpc:async(name,a)=>{assert.equal(name,'teacher_students_create');args=a;return {data:[{username:'test01'}]};}};const api=moduleFactory('admin-students-api.ts','adminStudentsAPI',db);const rows=[{kullanici:'test01',sifre:'secret01',sinif:5,sube:'a'}];assert.equal((await api.handle('ogretmenOgrenciOlustur',{ogrenciler:rows},q,student,'POST')).status,403);assert.equal((await api.handle('ogretmenOgrenciOlustur',{ogrenciler:rows},q,teacher,'GET')).status,405);const r=await api.handle('ogretmenOgrenciOlustur',{ogrenciler:rows,teacher_id:'forged'},q,teacher,'POST');assert.equal(r.status,200);assert.equal(args.p_actor,'other');assert.equal(args.p_rows[0].branch,'A');assert.match(args.p_rows[0].password_hash,/^pbkdf2\$/);assert(!JSON.stringify(r).includes('secret01'));});
test('creation rejects malformed rows, duplicates and excessive batches before RPC',async()=>{let calls=0;const api=moduleFactory('admin-students-api.ts','adminStudentsAPI',{rpc:async()=>{calls++;}});const valid={kullanici:'test01',sifre:'secret01',sinif:5,sube:'A'};for(const rows of [[],[valid,{...valid,kullanici:'TEST01'}],[{...valid,sifre:'x'}],[{...valid,sinif:9}],Array(51).fill(valid)])assert.equal((await api.handle('ogretmenOgrenciOlustur',{ogrenciler:rows},q,teacher,'POST')).status,400);assert.equal(calls,0);});
test('owner patch is restricted and conflict returns refresh instruction',async()=>{let args;const api=moduleFactory('admin-students-api.ts','adminStudentsAPI',{rpc:async(_,a)=>{args=a;return {error:{code:'40001'}};}});const body={id:'12345678-1234-1234-1234-123456789012',kullanici:'newName',okul:'New school',sinif:6,sube:'b',sonGuncelleme:'2026-10-07T11:00:00Z',yeniSifre:'newSecret',points:9000,teacher_id:'forged'};const r=await api.handle('yoneticiOgrenciKaydet',body,q,owner,'POST');assert.equal(r.status,409);assert.equal(args.p_actor,'owner');assert(!('points' in args.p_changes));assert(!('teacher_id' in args.p_changes));assert.equal(args.p_changes.branch,'B');assert(args.p_changes.password_hash);});
test('frozen students blocked across features but personal repair routes stay open',async()=>{const api=moduleFactory('contact-policy-api.ts','contactPolicyAPI',{rpc:async()=>({data:{eksik:true,donuk:true,sonTarih:'2026-10-01T00:00:00Z'}})});for(const op of ['', 'ekonomi','buyuSeviyeTamamla','duelloGonder','dersKonuDetayGetir'])assert.equal((await api.guard(op,student)).status,423);for(const op of ['kisiselBilgilerim','kisiselBilgiGuncelle'])assert.equal(await api.guard(op,student),null);assert.equal(await api.guard('ekonomi',teacher),null);assert.equal((await api.guard('iletisimDurumu',student)).status,200);});
test('frozen state is reread so contact completion unlocks immediately',async()=>{let n=0;const api=moduleFactory('contact-policy-api.ts','contactPolicyAPI',{rpc:async()=>({data:++n===1?{eksik:true,donuk:true}:{eksik:false,donuk:false}})});assert.equal((await api.guard('ekonomi',student)).status,423);assert.equal(await api.guard('ekonomi',student),null);assert.equal(n,2);});
test('contact policy fails closed during a database failure',async()=>{const api=moduleFactory('contact-policy-api.ts','contactPolicyAPI',{rpc:async()=>({error:{code:'503'}})});assert.equal((await api.guard('ekonomi',student)).status,503);assert.equal(await api.guard('kisiselBilgiGuncelle',student),null);});
test('live source enforces policy before root/progression and keeps initial contact setup password-free',()=>{const main=fs.readFileSync('supabase/functions/diji-api/index.ts','utf8');assert(main.indexOf('const contactDeny=')<main.indexOf('const progressionDeny='));assert(main.includes('telDegisti && Boolean(String(s.phone || "").trim())'));assert(main.includes('contacts.invalidate(s.id)'));assert(main.includes('contacts.state(studentId)'));const medu=fs.readFileSync('supabase/functions/medupro-api/index.ts','utf8');assert(medu.indexOf('const contactDeny=')<medu.indexOf('const levelDeny='));});
