const {test}=require('node:test'),assert=require('node:assert/strict'),{fixture}=require('./helpers/word-wheel-fixture.cjs');
const begin={sinif:5,unite:1,mode:2,names:['Ali','Ece']};
test('unit deck is complete, shuffled, isolated; questions only become visible after spin',async()=>{const f=fixture(),r=await f.handle('kelimeCarkiBaslat',begin);assert.equal(r.status,200);assert.equal(r.d.pending,null);assert.equal(r.d.total,11);assert(['apple','bird','book','honest'].every(word=>f.sessions[0].deck.some(w=>w.en===word)));assert.equal(new Set(f.sessions[0].deck.map(w=>w.en)).size,11);assert.equal(new Set(r.d.wheelPoints).size,12);assert(!JSON.stringify(r.d).includes('otherunit'));const s=await f.handle('kelimeCarkiCevir',{runId:r.d.runId});assert(s.d.pending);assert(!('answer'in s.d.pending));const again=await f.handle('kelimeCarkiCevir',{runId:r.d.runId});assert.equal(s.d.pending.slot,again.d.pending.slot);});
test('correct adds and incorrect subtracts wheel points; turns alternate and duplicate answers are idempotent',async()=>{const f=fixture(),r=await f.handle('kelimeCarkiBaslat',begin),runId=r.d.runId;let s=(await f.handle('kelimeCarkiCevir',{runId})).d;let a=(await f.handle('kelimeCarkiCevap',{runId,round:0,answer:f.sessions[0].deck[0].tr,puan:999999})).d;assert.equal(a.players[0].score,s.pending.points);assert.equal(a.turn,1);const repeat=(await f.handle('kelimeCarkiCevap',{runId,round:0,answer:'wrong'})).d;assert.equal(repeat.players[0].score,a.players[0].score);s=(await f.handle('kelimeCarkiCevir',{runId})).d;a=(await f.handle('kelimeCarkiCevap',{runId,round:1,answer:'incorrect'})).d;assert.equal(a.players[1].score,-s.pending.points);assert.equal(a.turn,0);assert(f.tables.every(t=>['word_bank','papi_wheel_sessions'].includes(t)));});
test('finish ignores pending question and freezes exactly the latest totals, including negative scores',async()=>{const f=fixture(),r=await f.handle('kelimeCarkiBaslat',{...begin,mode:1}),runId=r.d.runId;const s=(await f.handle('kelimeCarkiCevir',{runId})).d;await f.handle('kelimeCarkiCevap',{runId,round:0,answer:'incorrect'});await f.handle('kelimeCarkiCevir',{runId});const a=(await f.handle('kelimeCarkiBitir',{runId,puan:999999})).d;assert.equal(a.finished,true);assert.equal(a.index,1);assert.equal(a.pending,null);assert.equal(a.players[0].score,-s.pending.points);const again=(await f.handle('kelimeCarkiBitir',{runId})).d;assert.equal(again.players[0].score,a.players[0].score);const later=(await f.handle('kelimeCarkiCevap',{runId,round:1,answer:'kitap'})).d;assert.equal(later.index,1);});
test('finish before any question records zero; another account cannot access or modify a run',async()=>{const f=fixture(),r=await f.handle('kelimeCarkiBaslat',begin),runId=r.d.runId;assert.equal((await f.handle('kelimeCarkiBitir',{runId},{role:'student',student_id:'other'})).status,404);assert.equal((await f.handle('kelimeCarkiBaslat',begin,null)).status,401);const a=(await f.handle('kelimeCarkiBitir',{runId})).d;assert(a.players.every(x=>x.score===0));assert.equal(a.finished,true);});
test('leaderboard includes completed players with real final scores and excludes unfinished sessions',async()=>{const f=fixture(),r=await f.handle('kelimeCarkiBaslat',begin);await f.handle('kelimeCarkiBitir',{runId:r.d.runId});await f.handle('kelimeCarkiBaslat',begin);const l=(await f.handle('kelimeCarkiSiralama',begin)).d.liste;assert.equal(l.length,2);assert.equal(l[0].puan,0);assert(!('actor_key'in l[0]));});

test('old in-progress games retain original scoring and eight slots after upgrade',async()=>{const f=fixture(),r=await f.handle('kelimeCarkiBaslat',begin),s=f.sessions[0];delete s.state.wheelPoints;s.state.pending={slot:7};const resumed=(await f.handle('kelimeCarkiDurum',{runId:r.d.runId})).d;assert.equal(resumed.wheelPoints.length,8);assert.equal(resumed.pending.points,200);const answered=(await f.handle('kelimeCarkiCevap',{runId:r.d.runId,round:0,answer:s.deck[0].tr})).d;assert.equal(answered.players[0].score,200);});
test('all 64 units have eight valid supplement words and four unique answer choices',async()=>{const f=fixture();for(let sinif=1;sinif<=8;sinif++)for(let unite=1;unite<=8;unite++){const r=await f.handle('kelimeCarkiBaslat',{sinif,unite,mode:1});assert.equal(r.status,200);assert(r.d.total>=8);const deck=f.sessions.at(-1).deck;assert(deck.every(w=>w.en&&w.tr&&w.options.includes(w.tr)&&w.options.length===4&&new Set(w.options).size===4));}});
