(function(){
 'use strict';
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const name=()=>typeof aktifOgrenciAdi!=='undefined'?aktifOgrenciAdi:'',logged=()=>name()&&name().toLowerCase()!=='teacher'&&!!localStorage.getItem('ing_token');
 const presets=['Merhaba! 👋','Beni takip eder misin? 🌟','Birlikte Kelime Uçuşu oynayalım! 🪽','Cümle Rotası düellosuna var mısın? 🧩','Kelime Laboratuvarı oynayalım! 🔬','Risk Balonları için hazır mısın? 🎈','Hafıza Sandığı oynayalım! 🧠','Hız Fırtınası yarışına katıl! 🌪️','Eş Bul oynayalım! 🔗','Kelime Treni düellosu yapalım! 🚂','Harf Avı oynayalım! 🔤','Şifre Kırıcı oynayalım! 🔐','Harika oynadın, tebrikler! 🎉','Rövanş yapalım mı? ⚔️','Bugün birlikte ders çalışalım! 📚'];
 const games={Kelime_Liderlik:['🔬 Kelime Laboratuvarı','kelimeYarismasiAc','ky'],Jeopardy_Liderlik:['🎈 Risk Balonları','jpOyunAc','jp'],Bosluk_Tablosu:['✏️ Eksik Harf','boslukOyunAc','bosluk'],Hafiza_Liderlik:['🧠 Hafıza Sandığı','hafizaOyunAc','hafiza'],Yagmur_Liderlik:['🌪️ Hız Fırtınası','yagmurOyunAc','yagmur'],Asmaca_Liderlik:['🔤 Harf Avı','asmacaOyunAc','asmaca'],KelimeBul_Liderlik:['🔐 Şifre Kırıcı','kelimeBulOyunAc','kelimebul'],Konusma_Liderlik:['🎤 Kelime Modu','kpModuAc','kp'],Eslesme_Liderlik:['🔗 Eş Bul','esOyunAc','eslestirme'],Tren_Liderlik:['🚂 Kelime Treni','trenOyunAc','tren'],Dikte_Liderlik:['🎧 Kulak Dedektifi','dikteAc','dikte'],Cumle_Liderlik:['🧱 Cümle Ustası','cumleAc','cumle'],ucus:['🪽 Kelime Uçuşu',null,'ucus'],rota:['🧩 Cümle Rotası',null,'rota']};
 const toast=m=>{if(typeof yoToast==='function')yoToast(m);else alert(m);};
 async function api(islem,data={}){const r=await fetch(apiURL,{method:'POST',body:JSON.stringify({islem,ogrenci:name(),...data})});const d=await r.json();if(!r.ok||d.ok===false||d.status==='error')throw Error(d.mesaj||d.message||'İşlem tamamlanamadı. Tekrar dene.');return d;}
 function sheet(title,desc){const p=document.createElement('div');p.className='dm-perde';p.innerHTML=`<section class="dm-sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><button class="dm-x" aria-label="Kapat">×</button><header><img class="dm-mascot" src="mascot-help.webp" alt="Diji-Medu papağanı"><h2>${esc(title)}</h2><p>${esc(desc)}</p></header><div class="dm-sheet-body"></div></section>`;document.body.append(p);const prev=document.activeElement;function close(){p.remove();prev?.focus?.();p._close?.();}p.querySelector('.dm-x').onclick=close;p.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const f=[...p.querySelectorAll('button,select,a,input')].filter(x=>!x.disabled&&x.getClientRects().length);if(e.shiftKey&&document.activeElement===f[0]){e.preventDefault();f.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===f.at(-1)){e.preventDefault();f[0]?.focus();}}});p.querySelector('.dm-x').focus();return {p,body:p.querySelector('.dm-sheet-body'),close};}
 function error(box,e){let a=box.querySelector('.dm-error');if(!a){a=document.createElement('p');a.className='dm-error';a.setAttribute('role','alert');box.append(a);}a.textContent=e.message;}
 async function syncYo(){try{const r=await fetch(apiURL+'?islem=ekVeriGetir&ogrenci='+encodeURIComponent(name())+'&anahtar=yo');const d=await r.json();if(d?.deger&&typeof yo!=='undefined'&&yo){Object.assign(yo,JSON.parse(d.deger));localStorage.setItem('ing_yo_'+name(),JSON.stringify(yo));window.yoArayuzTazele?.();window.yoAvatarUygula?.();}}catch(e){}}

 window.dmMeduProAc=function(){
  const show=()=>{const host=document.querySelector('#bzParkur .bz-ic');if(!host)return;let panel=host.querySelector('.dm-pro-panel');if(!panel){panel=document.createElement('section');panel.className='dm-pro-panel';panel.setAttribute('role','tabpanel');panel.innerHTML=`<h2>MeduPro</h2><p>Öğrenmenin üç farklı yolu. Maceranı seç!</p><button class="dm-pro-mode" data-mode="kp" style="--bg:#fff4e7;--edge:#efd3a8;--ink:#88521f"><i>🔤</i><span><b>Kelime Modu</b><small>Dinle, sesli söyle ve kelimelerde ustalaş.</small></span></button><button class="dm-pro-mode" data-mode="sh" style="--bg:#e8fbef;--edge:#bee8ce;--ink:#267344"><i>🦜</i><span><b>Papağanla Sohbet</b><small>Papi ile konuş, İngilizceni geliştir.</small></span></button><button class="dm-pro-mode" data-mode="kk" style="--bg:#eef0ff;--edge:#cfd5f1;--ink:#505a9a"><i>🃏</i><span><b>Kelime Kartları</b><small>Kartları keşfet, öğrendiklerini pekiştir.</small></span></button>`;host.append(panel);panel.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{$('pkSekmeler')?.querySelector('[data-p="'+b.dataset.mode+'"]')?.click();});}
   const sc=host.querySelector('.dm-parkur-scroll');if(sc)sc.hidden=true;panel.hidden=false;host.querySelectorAll('[data-dm-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.dmTab==='pro')));
  };if(document.body.classList.contains('dm-parkur-open'))show();else{window.dunyaAc?.();setTimeout(show,250);}
 };
 document.addEventListener('click',e=>{if(e.target.closest('[data-dm-tab="ba"]')){const host=document.querySelector('#bzParkur .bz-ic');host?.querySelector('.dm-pro-panel')?.remove();const sc=host?.querySelector('.dm-parkur-scroll');if(sc)sc.hidden=false;}});
 const bar=$('pkSekmeler');if(bar){bar.querySelector('[data-p="ba"]').innerHTML='<i>🧙</i>Parkur';const b=document.createElement('button');b.type='button';b.dataset.p='pro';b.setAttribute('role','tab');b.innerHTML='<i>✨</i>MeduPro';b.onclick=window.dmMeduProAc;bar.append(b);}
 window.dmMessageAc=function(target){const s=sheet('Mesaj gönder','Bir hazır mesaj seç. Mesajın arkadaşının ekranında bildirim olarak görünür.');s.body.innerHTML='<div class="dm-message-grid">'+presets.map((t,i)=>`<button data-preset="${i}">${esc(t)}</button>`).join('')+'</div>';s.body.querySelectorAll('button').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('hazirMesajGonder',{alici:target,mesajId:Number(b.dataset.preset)});s.close();toast('Mesajın gönderildi 💬');}catch(e){error(s.body,e);b.disabled=false;}});};
 window.dmGiftAc=async function(target){const s=sheet('Hediye gönder','Enerjiyle destek ol ya da arkadaşının Dolap’ına bir aksesuar ekle.');s.body.textContent='Hediyeler yükleniyor…';try{const d=await api('aksesuarKatalog');s.body.innerHTML=`<button class="dm-primary dm-energy">⚡ 2 enerji gönder</button><p>Aksesuarlar altınla alınır; fiyatı onayladıktan sonra gönderilir.</p><div class="dm-gift-grid">${d.liste.map(i=>`<button data-item="${esc(i.id)}">${i.icon} ${esc(i.name)}<small>${i.price} 🪙</small></button>`).join('')}</div><div class="dm-confirm"></div>`;s.body.querySelector('.dm-energy').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await api('enerjiGonder',{gonderen:name(),alici:target});s.close();toast('Enerji hediyen gönderildi ⚡');}catch(e){error(s.body,e);b.disabled=false;}};s.body.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{const i=d.liste.find(x=>x.id===b.dataset.item),c=s.body.querySelector('.dm-confirm');c.innerHTML=`<div class="dm-gift-confirm"><b>${esc(target)}</b> için ${esc(i.name)} · <b>${i.price} 🪙</b><button class="dm-primary">Satın al ve hediye gönder</button></div>`;c.querySelector('button').onclick=async e=>{const b=e.currentTarget;b.disabled=true;try{await window.yoHemenKaydet?.(true);const d=await api('aksesuarHediye',{alici:target,item:i.id});await syncYo(d.yo);s.close();toast('Aksesuar hediyen gönderildi 🎁');}catch(e){error(c,e);b.disabled=false;}};c.scrollIntoView({block:'nearest'});});}catch(e){s.body.textContent='';error(s.body,e);}};
 const states=new Map();let account='';
 async function status(target){const d=await api('sosyalDurum',{alici:target});states.set(target,d);document.querySelectorAll('.dm-social').forEach(k=>{if(k.dataset.person!==target)return;k.querySelectorAll('button,select').forEach(b=>b.disabled=!!d.blocked);const b=k.querySelector('.dm-block');b.disabled=d.blocked&&!d.mine;b.textContent=d.mine?'Engeli kaldır':d.blocked?'İletişim kapalı':'Engelle';b.dataset.mine=String(!!d.mine);const note=k.querySelector('.dm-blocked-note');note.hidden=!d.blocked;});document.querySelectorAll('.takip-btn').forEach(b=>{if(b.getAttribute('onclick')?.includes(target))b.disabled=!!d.blocked;});return d;}
 const oldVitrin=window.maVitrinHtml;
 if(typeof oldVitrin==='function')window.maVitrinHtml=function(id,mine){let html=oldVitrin.apply(this,arguments);if(mine||id==='ben'||id===name())return html;const tmp=document.createElement('div');tmp.innerHTML=html;tmp.querySelectorAll('.dl-kart,.eg-kart').forEach(x=>x.remove());html=tmp.innerHTML;setTimeout(()=>status(id).catch(e=>toast(e.message)),0);return `<section class="dm-social" data-person="${esc(id)}"><h4>Birlikte daha eğlenceli!</h4><div class="dm-social-actions"><button disabled data-social="message">💬 Mesaj gönder</button><button disabled data-social="gift">🎁 Hediye gönder</button><button disabled class="dm-block" data-social="block">Engelle</button></div><p class="dm-blocked-note" hidden>Takip, mesaj, hediye ve düello gönderimi kapalı.</p><h4 style="margin-top:16px">⚔️ Düelloya çağır</h4><select disabled class="dm-game">${Object.entries(games).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select><select disabled class="dm-mode"><option value="async">24 saat içinde ayrı ayrı oyna</option><option disabled value="live">Aynı anda oyna · yeni oyunlar</option></select><button disabled class="dm-send-duel" data-social="duel">Düello gönder</button><small>İkinizin sonucu birlikte görünür. Eşit puanda kısa süre kazanır. Yeni oyunlar: 8 soru, soru başına 12 saniye, en fazla 1000 puan.</small></section>`+html;};
 document.addEventListener('change',e=>{if(!e.target.matches('.dm-game'))return;const k=e.target.closest('.dm-social'),mode=k.querySelector('.dm-mode');mode.value='async';mode.querySelector('[value="live"]').disabled=!['ucus','rota'].includes(e.target.value);});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-social]');if(!b)return;const k=b.closest('.dm-social'),target=k.dataset.person,act=b.dataset.social;if(act==='message')return window.dmMessageAc(target);if(act==='gift')return window.dmGiftAc(target);b.disabled=true;try{
  if(act==='block'){await api(b.dataset.mine==='true'?'ogrenciEngelKaldir':'ogrenciEngelle',{alici:target});if(typeof maTakip!=='undefined')maTakip.delete(target);await status(target);toast(b.dataset.mine==='true'?'Engelleme etkin.':'Engel kaldırıldı.');window.maCiz?.();}
  else{const game=k.querySelector('.dm-game').value;if(['ucus','rota'].includes(game)){const d=await api('oyunEslesmeOlustur',{alici:target,oyun:game,mod:k.querySelector('.dm-mode').value});toast('Oyun daveti gönderildi!');window.dmMatchAc(d.id);}else{await api('duelloGonder',{gonderen:name(),alici:target,oyun:game});toast('Düello daveti gönderildi ⚔️');}b.textContent='Gönderildi ✓';}
 }catch(e){toast(e.message);}finally{if(act!=='block')b.disabled=false;}});
 window.maTakipDegistir=async function(id,b){if(b)b.disabled=true;try{const st=await status(id);if(st.blocked)throw Error('Bu kişiyle iletişim kapalı.');const d=await api('akisOlayToggle',{hedef:id,tur:'takip'});if(typeof maTakip!=='undefined'){if(d.aktif)maTakip.add(id);else maTakip.delete(id);}if(b){b.classList.toggle('takipte',d.aktif);b.textContent=d.aktif?'✓ Takip ediliyor':'🎈 Takip et';}if(d.aktif)await api('bildirimGonder',{gonderen:name(),alici:id,tur:'takip',metin:'seni takip etmeye başladı'});toast(d.aktif?'Takip ediyorsun 🎈':'Takipten çıktın.');}catch(e){toast(e.message);}finally{if(b)b.disabled=false;}};
 window.duelloOyununuAc=function(game){const f=games[game]?.[1];window.dcTumTamEkranlariKapat?.();if(f&&typeof window[f]==='function')window[f]();else window.dmArenaAc();};
 const oldResult=window.genelSonucEkraniGoster;
 if(typeof oldResult==='function'){window.genelSonucEkraniGoster=function(o){const r=oldResult.apply(this,arguments);const game=Object.keys(games).find(k=>games[k][2]===o?.oyunKey);if(logged()&&game&&games[game][1])api('duelloSonucKaydet',{oyun:game,puan:o.puan,sure:o.sureSaniye}).then(d=>{const a=d.liste?.[0];if(!a)return;let k=$('dmClassicResult');if(k)k.remove();k=document.createElement('div');k.id='dmClassicResult';k.className='dm-help-new';k.innerHTML=`<b>⚔️ Düello sonucu</b><p>Sen: ${a.myResult.puan} puan · ${a.myResult.sure} sn<br>Rakip: ${a.opponentResult?`${a.opponentResult.puan} puan · ${a.opponentResult.sure} sn`:'Henüz tamamlamadı; sonucu Düellolarım’da görünecek.'}</p>`;$('genelSonucOverlay')?.querySelector('.gso-kart')?.append(k);}).catch(e=>toast(e.message));return r;};window.genelSonucEkraniGoster._oc=oldResult._oc;}
 function matchLabel(g){return games[g]?.[0]||g;}
 let activeMatch=null;
 window.dmMatchAc=async function(id){if(activeMatch)activeMatch.close();const s=sheet('İki kişilik karşılaşma','Aynı sorular, aynı kurallar. İyi eğlenceler!');activeMatch=s;let timer,inflight=false,stopped=false,lastKey='',rewardSeen=false;
  s.p._close=()=>{stopped=true;clearTimeout(timer);activeMatch=null;};
  async function poll(action='oyunEslesmeDurum',args={}){if(stopped||inflight)return;inflight=true;try{const d=await api(action,{id,...args});render(d);}catch(e){lastKey='';error(s.body,e);}finally{inflight=false;if(!stopped){clearTimeout(timer);timer=setTimeout(()=>{if(!document.hidden)poll();else timer=setTimeout(()=>poll(),2500);},1200);}}}
  function render(d){s.p.querySelector('h2').textContent=d.game?matchLabel(d.game):'Karşılaşma';if(['cancelled','expired'].includes(d.status)){s.body.innerHTML=`<p>${d.status==='cancelled'?'Bu karşılaşma iptal edildi.':'24 saatlik süre doldu.'}</p>`;stopped=true;return;}
   if(d.myResult){const a=d.myResult,b=d.opponentResult,key=JSON.stringify([a,b]);if(key===lastKey)return;lastKey=key;let winner='Rakibinin tamamlaması bekleniyor.';if(b)winner=a.puan>b.puan||(a.puan===b.puan&&a.sure<b.sure)?'🏆 Kazandın!':a.puan===b.puan&&a.sure===b.sure?'🤝 Berabere!':'🌟 Güzel mücadele! Rövanşa hazır mısın?';s.body.innerHTML=`<div class="dm-match-wait"><img src="mascot-reward.webp" alt="Kutlayan papağan"><h3>${winner}</h3></div><div class="dm-results"><div class="dm-result"><b>Sen</b><strong>${a.puan}</strong><small>${a.dogru}/8 doğru · ${a.sure} sn</small><small>${'⭐'.repeat(a.yildiz)}<br>+${a.reward.gold} 🪙 · +${a.reward.xp} XP</small></div><div class="dm-result rival"><b>${esc(d.opponent)}</b><strong>${b?b.puan:'…'}</strong><small>${b?`${b.dogru}/8 doğru · ${b.sure} sn`:'Henüz tamamlamadı'}</small></div></div><p>İkinizin sonucu Karşılaşmalarım’da saklanır.</p>`;if(!rewardSeen){rewardSeen=true;syncYo();}if(b){stopped=true;return;}return;}
   if(!d.start){const key='wait'+d.ready+d.opponentReady;if(key===lastKey)return;lastKey=key;s.body.innerHTML=`<div class="dm-match-wait"><img src="mascot-welcome.webp" alt="Bekleyen papağan"><h3>${esc(d.opponent)} ile ${d.mode==='live'?'aynı anda':'24 saat içinde'}</h3><p>8 soru · 4 enerji · Her soruya 12 saniye<br>Doğru +100 · Seri bonusları +50 / +50 / +100<br>Eşit puanda daha hızlı oyuncu kazanır.</p><button class="dm-primary" ${d.ready?'disabled':''}>${d.ready?'Hazırsın · Rakibini bekliyoruz':'Hazırım, başlayalım!'}</button></div>`;s.body.querySelector('button').onclick=()=>poll('oyunEslesmeHazir');return;}
   if(d.index<0){s.body.innerHTML='<div class="dm-match-wait"><h3>Hazır ol! 🦜</h3><p>Birkaç saniye içinde başlıyoruz…</p></div>';lastKey='countdown';return;}
   if(!d.question)return;
   const key=d.index+':'+d.answered; if(key!==lastKey){lastKey=key;const q=d.question;s.body.innerHTML=`<div class="dm-live-meta"><span>${d.index+1}/8 soru</span><span class="dm-seconds"></span><span class="dm-score"></span></div><div class="dm-word">${esc(q.word)}</div><div class="dm-flight ${d.game==='rota'?'rota':''}">${q.choices.map((t,i)=>`<button style="--i:${i}" data-choice="${i}" ${d.answered?'disabled':''}>${esc(t)}</button>`).join('')}</div><div class="dm-feedback" role="status">${d.answered?'Doğru anlam: '+esc(d.feedback):'Doğru anlamı seç!'}</div>`;s.body.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{s.body.querySelectorAll('[data-choice]').forEach(x=>x.disabled=true);const answer=()=>{if(stopped)return;if(inflight){setTimeout(answer,40);return;}poll('oyunEslesmeCevap',{index:d.index,choice:Number(b.dataset.choice)});};answer();});}
   const t=s.body.querySelector('.dm-seconds'),p=s.body.querySelector('.dm-score');if(t)t.textContent='⏱ '+d.seconds+' sn';if(p)p.textContent=d.myScore+' puan';
  }await poll();
 };
 window.dmArenaAc=async function(){const s=sheet('Karşılaşmalarım','Kelime Uçuşu ve Cümle Rotası: aynı anda veya farklı zamanlarda oyna.');s.body.innerHTML='<p>Yükleniyor…</p>';try{const d=await api('oyunEslesmelerim');s.body.innerHTML='<p>Yeni bir karşılaşma başlatmak için arkadaşının profiline gir ve “Düelloya çağır” bölümünden oyun seç.</p>'+(!d.liste.length?'<p>Henüz karşılaşman yok. İlk davetini gönder! 🦜</p>':d.liste.map(m=>`<div class="dm-duel-item"><b>${matchLabel(m.game)} · ${esc(m.opponent)}</b><small>${m.mode==='live'?'Aynı anda':'24 saat içinde'} · ${m.status==='finished'?'Tamamlandı':m.status==='expired'?'Süresi doldu':m.status==='cancelled'?'İptal edildi':'Oynamaya hazır'}<br>Sen: ${m.myResult?.puan??'–'} · Rakip: ${m.opponentResult?.puan??'–'}</small><button data-match="${m.id}">Aç</button></div>`).join(''));s.body.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>{s.close();window.dmMatchAc(b.dataset.match);});}catch(e){s.body.innerHTML='';error(s.body,e);}};
 const oldDiscover=window.maKesfetHtml;if(typeof oldDiscover==='function')window.maKesfetHtml=function(){return '<div class="dm-social"><h4>🪽 İki kişilik yeni oyunlar</h4><button onclick="dmArenaAc()">Karşılaşmalarım · Kelime Uçuşu & Cümle Rotası</button></div>'+oldDiscover.apply(this,arguments);};
 function addCards(){const grid=document.querySelector('#tab-aktiviteler .az-grid2x2');if(!grid||$('dmUcusteKart'))return;['ucus','rota'].forEach((g,i)=>{const b=document.createElement('button');b.id=i?'dmRotaKart':'dmUcusteKart';b.type='button';b.className='az-gcard dm-live-card';b.innerHTML=`<div class="az-gcard-badge">2 KİŞİLİK</div><div class="az-gcard-icon">${i?'🧩':'🪽'}</div><div class="az-gcard-title">${i?'Cümle Rotası':'Kelime Uçuşu'}</div>`;b.onclick=window.dmArenaAc;grid.append(b);});}addCards();setTimeout(addCards,1800);
 const seen=new Set();let notifying=false;
 async function notify(){if(!logged()||document.hidden||notifying)return;notifying=true;try{const d=await api('bildirimlerim');const mine=d.liste.filter(b=>['mesaj','oyunDavet','hediye'].includes(b.tur)&&!seen.has(b.sat));for(const b of mine.slice(0,1)){seen.add(b.sat);const k=document.createElement('aside');k.className='dm-notification';k.setAttribute('role','status');k.innerHTML=`<b>${esc(b.gonderen)}</b><small>${esc(b.metin)}</small><button class="dm-notif-close" aria-label="Kapat">×</button>${b.matchId?'<button class="dm-notif-play">Karşılaşmayı aç</button>':''}`;document.body.append(k);k.querySelector('.dm-notif-close').onclick=()=>k.remove();const go=k.querySelector('.dm-notif-play');if(go)go.onclick=()=>{k.remove();window.dmMatchAc(b.matchId);};setTimeout(()=>k.remove(),12000);await api('bildirimOkundu',{satirlar:b.sat});if(b.tur==='hediye')syncYo();}}catch(e){}finally{notifying=false;}}
 setInterval(()=>{if(account!==name()){account=name();states.clear();seen.clear();}notify();},15000);setTimeout(notify,5000);
 const help=`<section class="dm-help-new" data-dm-help><h3>🦜 Yeni özellikler</h3><p><b>Parkur & MeduPro:</b> Öğrenme Parkuru’nda bulunduğun üniteye dokunarak devam et. Sağdaki MeduPro’da Kelime Modu, Papağanla Sohbet ve Kelime Kartları alt alta yer alır.</p><p><b>Hazır mesajlar:</b> Arkadaşının profili › Mesaj gönder. 15 hazır mesajdan seç; serbest yazı yoktur. Mesaj uygulama açıkken bildirim olarak gelir ve 🔔 zilinde saklanır.</p><p><b>Engelle:</b> Profilde Engelle’ye dokun. İki taraf da takip, mesaj, hediye ve düello gönderemez; mevcut takipler kaldırılır ve aktif karşılaşmalar iptal edilir. Aynı düğmeden engeli kaldırabilirsin.</p><p><b>Hediyeler:</b> Profil › Hediye gönder. Günde bir kez 2 enerji veya fiyatını onaylayarak 12 aksesuardan birini altınla hediye et. Aksesuar arkadaşının Dolap’ına kalıcı olarak eklenir. Arkadaşında bulunan aksesuar tekrar alınmaz.</p><p><b>Tüm oyunlarda düello:</b> 12 mevcut oyun ve 2 yeni oyun listede. Klasik davet 24 saat geçerli; kabulden sonra iki oyuncu 24 saat içinde oyunu tamamlar. İkinizin puanı ve süresi sonuçta ve Düellolarım’da görünür; eşit puanda daha hızlı oyuncu kazanır.</p><p><b>Kelime Uçuşu:</b> İngilizce kelimenin Türkçe anlamını uçan 6 seçenekten bul. <b>Cümle Rotası:</b> Cümlenin doğru anlamını seç. İki oyuncu aynı sınıf havuzundan aynı soruları görür; farklı sınıflarda küçük sınıfın havuzu kullanılır.</p><p><b>Aynı anda:</b> İki oyuncu farklı cihazlarda “Hazırım” der; ortak geri sayımla başlar. <b>Farklı zamanda:</b> Herkes 24 saat içinde kendi turunu açar. Sonuç için ikisi de tamamlamalıdır; bağlantı koparsa aynı karşılaşmayı yeniden açabilirsin, süre işlemeye devam eder.</p><p><b>Kurallar & ödüller:</b> 8 soru, 4 enerji, her soruya 12 saniye. Doğru +100, 3/5/8’lik serilere +50/+50/+100; en fazla 1000. 800 puan 3 yıldız, 500 puan 2 yıldız, diğerleri 1 yıldız. Altın/XP: 1 yıldız 4/20, 2 yıldız 7/35, 3 yıldız 10/50; günün ilk 3 oyunu ×2, 12. oyundan sonrası ×½. Yeni oyun davetleri günde en fazla 10, hazır mesajlar saatte en fazla 20.</p></section>`;
 const oldHelp=window.yardimIcerikCiz;if(typeof oldHelp==='function')window.yardimIcerikCiz=function(search){const r=oldHelp.apply(this,arguments),host=$('yardimIcerikAlani');host?.querySelector('[data-dm-help]')?.remove();if(host&&(!search||help.toLocaleLowerCase('tr').includes(String(search).toLocaleLowerCase('tr'))))host.insertAdjacentHTML('afterbegin',help);return r;};
 window.dmMeduPro={presets,games,api};
})();
