/* Papi’s Meteor Duel — local simultaneous play; server-owned isolated scores. */
(()=>{'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}},remove(k){try{localStorage.removeItem(k)}catch{}}};
 let root,state,busy=false,origin,epoch=0,mode=2,grade='',unit='',names=['',''],extra=[],resize,timer;
 const main=()=>root?.querySelector('.mt-body');
 async function request(payload){if(typeof apiURL==='undefined')throw Error('Uygulama bağlantısı bulunamadı.');const controller=new AbortController(),t=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(apiURL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:controller.signal}),d=await r.json();if(!r.ok||!d.ok){const e=Error(d.mesaj||'İşlem tamamlanamadı.');e.status=r.status;throw e}return d;}catch(e){if(e.name==='AbortError')throw Error('Bağlantı gecikti. Tekrar dene.');throw e}finally{clearTimeout(t)}}
 function notice(s){if(root)root.querySelector('.mt-notice').textContent=s}
 function clear(){resize?.disconnect();clearTimeout(timer)}
 function close(){clear();epoch++;root?.remove();root=null;state=null;busy=false;document.body.classList.remove('mt-active');origin?.focus()}
 async function work(fn){if(busy)return;busy=true;const ticket=epoch;root?.classList.add('mt-busy');notice('');try{await fn()}catch(e){if(ticket===epoch){notice(e.message);if(e.status===409&&state){try{state=await request({islem:'meteorDurum',runId:state.runId});draw()}catch{notice('Güncel oyun yüklenemedi. Tekrar dene.')}}}}finally{if(ticket===epoch){busy=false;root?.classList.remove('mt-busy')}}}
 function frame(){origin=document.activeElement;root=document.createElement('section');root.id='meteorGame';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-labelledby','mtTitle');root.innerHTML='<div class="mt-shell"><header class="mt-top"><b class="mt-brand">Diji-<em>Medu</em></b><span class="mt-category">Oyunlar · Serbest Oyunlar</span><span class="mt-scope"></span><button class="mt-exit">Kapat</button></header><h1 id="mtTitle" class="mt-title">Papi’nin <span>Meteor Düellosu</span></h1><main class="mt-body"></main><p class="mt-notice" role="status" aria-live="polite"></p><footer class="mt-footer">İlk doğru cevap +10 · Yanlış −5 · Altın ve XP ödülü yok</footer></div>';root.querySelector('.mt-exit').onclick=()=>state&&!state.finished?finish():close();document.body.append(root);document.body.classList.add('mt-active');root.querySelector('.mt-exit').focus()}
 async function open(){if(root)return;epoch++;state=null;busy=false;frame();main().innerHTML='<p class="mt-loading">Kelime havuzu hazırlanıyor…</p>';const ticket=epoch;await work(async()=>{if(!(window.masterKelimeHavuzu||[]).length&&typeof window.dijiKelimeHavuzunuYukle==='function')await window.dijiKelimeHavuzunuYukle();extra=(await import('./word-wheel-vocabulary.js?v=1')).WHEEL_VOCABULARY;if(ticket===epoch)setup()});if(main()?.querySelector('.mt-loading')){const b=document.createElement('button');b.textContent='Tekrar dene';b.onclick=()=>{close();open()};main().append(b)}}
 function setup(){clear();state=null;root.querySelector('.mt-exit').textContent='Kapat';root.querySelector('.mt-scope').textContent='';const pool=[...(window.masterKelimeHavuzu||[]),...extra],grades=[...new Set(pool.map(w=>Number(w.sinif)).filter(x=>x>=1&&x<=12))].sort((a,b)=>a-b);grade=grades.includes(Number(grade))?grade:String(grades[0]||'');main().innerHTML='<section class="mt-setup"><img src="papi-welcome-v2.png" alt="Papi"><h2>Göktaşlarında doğru kelimeyi yakala!</h2><form><div class="mt-modes"><button type="button" data-mode="1">Tek Kişilik</button><button type="button" data-mode="2">İki Kişilik</button></div><div class="mt-fields"><label>Sınıf<select id="mtGrade">'+grades.map(g=>'<option value="'+g+'" '+(String(g)===grade?'selected':'')+'>'+g+'. Sınıf</option>').join('')+'</select></label><label>Ünite<select id="mtUnit"></select></label><label>1. oyuncunun ismi (isteğe bağlı)<input id="mtName1" maxlength="40" placeholder="İstediğin ismi yaz" autocomplete="off"></label><label class="mt-name2">2. oyuncunun ismi (isteğe bağlı)<input id="mtName2" maxlength="40" placeholder="İstediğin ismi yaz" autocomplete="off"></label></div><p class="mt-count"></p><p class="mt-rules">Alttaki kelimenin anlamını taşıyan göktaşına dokun. İki kişilikte ilk doğru cevap puanı alır ve ortak soru değişir. Yanlış dokunuşta 5 puan düşer. Türkçe ve İngilizce sorular dönüşümlü gelir.</p><button class="mt-start" type="submit">Oyunu Başlat</button><button class="mt-resume" type="button" hidden>Kaldığım Oyuna Dön</button><button class="mt-history" type="button">Ünite Sıralaması</button><p class="mt-rules">Sonuçlar yazdığın isimlerle kaydedilir. Altın, XP, enerji veya hediye verilmez.</p></form></section>';
 const b=main(),g=b.querySelector('#mtGrade'),u=b.querySelector('#mtUnit');b.querySelector('#mtName1').value=names[0];b.querySelector('#mtName2').value=names[1];function count(){unit=u.value;const n=new Set(pool.filter(w=>Number(w.sinif)===Number(grade)&&Number(w.unite)===Number(unit)&&w.ingilizce&&w.turkce).map(w=>String(w.ingilizce).trim().toLowerCase())).size;b.querySelector('.mt-count').textContent=n+' kelime · Ünitenin tamamı, karışık sırayla';b.querySelector('.mt-start').disabled=n<2}function units(){grade=g.value;const all=[...new Set(pool.filter(w=>Number(w.sinif)===Number(grade)).map(w=>Number(w.unite)).filter(x=>x>0))].sort((a,b)=>a-b);unit=all.includes(Number(unit))?unit:String(all[0]||'');u.innerHTML=all.map(x=>'<option value="'+x+'" '+(String(x)===unit?'selected':'')+'>'+x+'. Ünite</option>').join('');count()}function modes(){b.querySelectorAll('[data-mode]').forEach(x=>{const active=Number(x.dataset.mode)===mode;x.classList.toggle('selected',active);x.setAttribute('aria-pressed',String(active))});b.querySelector('.mt-name2').hidden=mode===1}g.onchange=units;u.onchange=count;b.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{mode=Number(x.dataset.mode);modes()});units();modes();b.querySelector('form').onsubmit=e=>{e.preventDefault();if(busy)return;names=[b.querySelector('#mtName1').value.trim(),b.querySelector('#mtName2').value.trim()];work(async()=>{const d=await request({islem:'meteorBaslat',sinif:Number(grade),unite:Number(unit),mode,names});if(!root)return;state=d;storage.set('dm_meteor_active',state.runId);draw()})};const resume=b.querySelector('.mt-resume');resume.hidden=!storage.get('dm_meteor_active');resume.onclick=()=>work(async()=>{state=await request({islem:'meteorDurum',runId:storage.get('dm_meteor_active')});draw()});b.querySelector('.mt-history').onclick=()=>work(async()=>{const d=await request({islem:'meteorSiralama',sinif:Number(grade),unite:Number(unit),mode});let el=b.querySelector('.mt-ranking');if(!el){el=document.createElement('div');el.className='mt-ranking';b.querySelector('form').append(el)}rankingHTML(d,el)})}
 function draw(){if(!root||!state)return;clear();if(state.finished){result();return}const q=state.question,columns=innerWidth<=700&&state.mode===2?2:3;root.querySelector('.mt-exit').textContent='Oyunu Bitir';root.querySelector('.mt-scope').textContent=state.mode+' Kişilik · '+state.sinif+'. Sınıf · '+state.unite+'. Ünite · '+(state.index+1)+'/'+state.total;main().innerHTML='<div class="mt-arenas '+(state.mode===1?'mt-solo':'')+'" style="--columns:'+columns+'">'+state.players.map((p,i)=>'<section class="mt-arena mt-player-'+i+'" aria-label="'+esc(p.name)+' oyun alanı"><div class="mt-score"><img src="papi-welcome-v2.png" alt=""><b>'+esc(p.name)+'</b><strong>'+p.score+'</strong></div><div class="mt-rain">'+q.options.map((x,j)=>'<button type="button" class="mt-meteor" data-player="'+i+'" data-option="'+j+'" style="--lane:'+((j+i)%columns)+';--delay:-'+(1.5+Math.floor(j/columns)*(11/Math.ceil(q.options.length/columns))+(j%columns)*.6)+'s" aria-label="'+esc(x)+'"><span>'+esc(x)+'</span></button>').join('')+'</div><div class="mt-target"><strong>'+esc(q.word)+'</strong><span>Doğru anlamı bul!</span></div><div class="mt-feedback" aria-live="polite"></div></section>').join('')+'</div>';
 main().querySelectorAll('.mt-meteor').forEach(x=>x.onclick=()=>answer(Number(x.dataset.player),Number(x.dataset.option)));const measure=()=>main()?.querySelectorAll('.mt-rain').forEach(el=>el.style.setProperty('--travel',(el.clientHeight+190)+'px'));measure();if(window.ResizeObserver){resize=new ResizeObserver(measure);main().querySelectorAll('.mt-rain').forEach(el=>resize.observe(el))}}
 function answer(player,option){if(busy||!state?.question)return;const round=state.question.round,runId=state.runId,attempt=crypto.randomUUID(),ticket=epoch;work(async()=>{const d=await request({islem:'meteorCevap',runId,round,player,option,attempt});if(ticket!==epoch||!root)return;state=d;const arena=main().querySelector('.mt-player-'+player),feedback=arena?.querySelector('.mt-feedback');if(feedback&&d.last?.attempt===attempt){feedback.textContent=(d.last.delta>0?'+':'')+d.last.delta;feedback.classList.add(d.last.correct?'correct':'wrong');arena.querySelector('[data-option="'+option+'"]')?.classList.add(d.last.correct?'hit':'miss');arena.querySelector('.mt-score strong').textContent=d.players[player].score}await new Promise(resolve=>{timer=setTimeout(resolve,500)});if(ticket===epoch)draw()})}
 function finish(){if(busy)return;if(!state||state.finished){close();return}work(async()=>{const d=await request({islem:'meteorBitir',runId:state.runId});if(!root)return;state=d;draw()})}
 function rankingHTML(d,el){el.innerHTML='<h3>Ünite Sıralaması</h3>'+(d.liste.length?'<ol>'+d.liste.map(x=>'<li><span>'+esc(x.isim)+'</span><b>'+x.puan+' puan</b></li>').join('')+'</ol>':'<p>Henüz sonuç yok.</p>')}
 function result(){storage.remove('dm_meteor_active');root.querySelector('.mt-exit').textContent='Kapat';const best=Math.max(...state.players.map(p=>p.score)),winners=state.players.filter(p=>p.score===best);main().innerHTML='<section class="mt-result"><img src="papi-welcome-v2.png" alt="Papi"><h2>'+ (state.mode===1?'Harika çalışma!':winners.length>1?'Berabere!':esc(winners[0].name)+' kazandı!')+'</h2><p>'+state.index+' / '+state.total+' kelime tamamlandı. Sonuçların kaydedildi.</p><div class="mt-results">'+state.players.map(p=>'<article><h3>'+esc(p.name)+'</h3><strong>'+p.score+' puan</strong><p>'+p.correct+' doğru · '+p.wrong+' yanlış</p></article>').join('')+'</div><div class="mt-ranking" aria-live="polite">Sıralama yükleniyor…</div><button class="mt-new">Yeniden Oyna</button><button class="mt-close">Kapat</button><p>Altın, XP veya hediye verilmez.</p></section>';main().querySelector('.mt-new').onclick=setup;main().querySelector('.mt-close').onclick=close;const s=state,el=main().querySelector('.mt-ranking');request({islem:'meteorSiralama',sinif:s.sinif,unite:s.unite,mode:s.mode}).then(d=>rankingHTML(d,el)).catch(()=>{el.textContent='Sıralama yüklenemedi.'})}
 function mount(){const grid=document.querySelector('#tab-aktiviteler .az-grid2x2');if(!grid||grid.querySelector('#meteorActivity'))return;const b=document.createElement('button');b.type='button';b.id='meteorActivity';b.className='az-gcard dm-toy-card';b.dataset.dmParty='free';b.style.setProperty('--toy-bg','#bde9fa');b.style.setProperty('--toy-edge','#87c6d9');b.innerHTML='<div class="az-gcard-icon"><img src="meteor-sprite.png" alt="" width="90" height="90" style="width:100%;height:100%;object-fit:contain"></div><div class="az-gcard-title">Papi’nin Meteor Düellosu</div><div class="ak-etiket">1 veya 2 kişilik · Ödülsüz</div>';b.onclick=open;grid.append(b)}
 document.addEventListener('keydown',e=>{if(!root)return;if(e.key==='Escape'){e.preventDefault();state&&!state.finished?finish():close()}if(e.key==='Tab'){const items=[...root.querySelectorAll('button:not(:disabled),input,select')].filter(x=>x.getClientRects().length),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});window.dmMeteor={open,close};mount();const host=document.getElementById('tab-aktiviteler');if(host)new MutationObserver(mount).observe(host,{childList:true,subtree:true});
})();
