/* Papi Kartları: self-paced study; separate self-assessment scores, no rewards or energy writes. */
(()=>{'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let root,origin,run=0,loading=false,words=[],grade='',unit='',queue=[],known=new Set(),review=new Set(),revealed=false,position=0,displayName='',first=new Map(),session=null;
 function close(){run++;loading=false;if('speechSynthesis'in window)window.speechSynthesis.cancel();root?.remove();root=null;document.body.classList.remove('pc-active');origin?.focus();}
 function frame(){if(root)close();origin=document.activeElement;root=document.createElement('section');root.id='papiCards';root.className='pc-overlay';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-labelledby','pcTitle');root.innerHTML='<div class="pc-shell"><header class="pc-header"><div><span class="pc-brand">Diji-Medu</span><h1 id="pcTitle">Papi Kartları</h1></div><button class="pc-close" aria-label="Papi Kartlarını kapat">✕</button></header><main class="pc-body"></main></div>';root.querySelector('.pc-close').onclick=close;document.body.append(root);document.body.classList.add('pc-active');root.querySelector('.pc-close').focus();return root.querySelector('.pc-body');}
 function body(){return root?.querySelector('.pc-body');}
 function say(text){if(!('speechSynthesis'in window)){notice('Bu tarayıcıda sesli okuma desteklenmiyor. Anlamı yine çalışabilirsin.');return;}try{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.85;const voice=window.speechSynthesis.getVoices().find(v=>/^en[-_]/i.test(v.lang));if(voice)u.voice=voice;u.onerror=e=>{if(!['canceled','interrupted'].includes(e.error))notice('Ses açılamadı. Hoparlöre dokunarak tekrar deneyebilirsin.');};window.speechSynthesis.speak(u);}catch(e){notice('Ses açılamadı. Hoparlöre dokunarak tekrar deneyebilirsin.');}}
 function notice(text){const n=root?.querySelector('.pc-notice');if(n)n.textContent=text;}
 function scopeWords(pool){const seen=new Set();return pool.filter(k=>String(Number(k.sinif))===grade&&String(Number(k.unite))===unit).map(k=>({en:String(k.ingilizce||k.en||'').trim(),tr:String(k.turkce||k.tr||'').trim()})).filter(k=>{const id=k.en.toLocaleLowerCase('en');if(!k.en||!k.tr||seen.has(id))return false;seen.add(id);return true;});}
 function setup(){const b=body();if(!b)return;const pool=window.masterKelimeHavuzu||[],grades=[...new Set(pool.map(k=>Number(k.sinif)).filter(n=>Number.isInteger(n)&&n>0&&n<=12))].sort((a,b)=>a-b);grade=grades.includes(Number(grade))?grade:String(grades[0]||'');b.innerHTML='<p class="pc-sub">Kendi hızında öğren. Önce sınıfını ve üniteni seç.</p><img class="pc-setup-papi" src="papi-welcome-v2.png" alt="Papi" width="100" height="110"><form class="pc-setup"><label>İsim (isteğe bağlı)<input id="pcName" maxlength="40" autocomplete="off" placeholder="İstediğin ismi yazabilirsin"></label><label>Sınıf<select id="pcGrade">'+grades.map(g=>`<option value="${g}" ${String(g)===grade?'selected':''}>${g}. Sınıf</option>`).join('')+'</select></label><label>Ünite<select id="pcUnit"></select></label><p class="pc-count" role="status"></p><button class="pc-start" type="submit">Kartları aç →</button><button class="pc-change pc-view-ranking" type="button">Bu ünitenin sıralaması</button><div class="pc-ranking" aria-live="polite"></div></form><p class="pc-note">Süre sınırı yok. İlk turdaki değerlendirmen puan olarak kaydedilir. Altın, XP veya hediye verilmez.</p><p class="pc-notice" role="status"></p>';b.querySelector('#pcName').value=displayName;const form=b.querySelector('form'),g=b.querySelector('#pcGrade'),u=b.querySelector('#pcUnit');function updateUnits(){grade=g.value;const units=[...new Set(pool.filter(k=>Number(k.sinif)===Number(grade)).map(k=>Number(k.unite)).filter(n=>Number.isInteger(n)&&n>0))].sort((a,b)=>a-b);unit=units.includes(Number(unit))?unit:String(units[0]||'');u.innerHTML=units.map(n=>`<option value="${n}" ${String(n)===unit?'selected':''}>${n}. Ünite</option>`).join('');updateCount();}function updateCount(){unit=u.value;words=scopeWords(pool);b.querySelector('.pc-count').textContent=words.length?words.length+' kelimelik deste':'Bu ünitede kelime bulunamadı.';b.querySelector('.pc-start').disabled=!words.length;}b.querySelector('.pc-view-ranking').onclick=()=>ranking({grade:Number(grade),unit:Number(unit)},b);g.onchange=updateUnits;u.onchange=updateCount;form.onsubmit=e=>{e.preventDefault();if(!words.length)return;displayName=b.querySelector('#pcName').value.trim();start();};updateUnits();}
 function draw(){const b=body();if(!b)return;if(!queue.length){finish();return;}revealed=false;const word=words[queue[0]];b.innerHTML=`<div class="pc-progress"><span>${esc(grade)}. Sınıf · ${esc(unit)}. Ünite</span><b>${known.size} / ${words.length} öğrendim</b></div><progress max="${words.length}" value="${known.size}" aria-label="Öğrenilen kelimeler"></progress><p class="pc-hint">Dokun, dinle ve anlamını gör</p><div class="pc-deck"><img class="pc-perched" src="papi-welcome-v2.png" alt="Papi" width="90" height="99"><article class="pc-card"><span class="pc-leaf pc-leaf-top" aria-hidden="true">🌿</span><button class="pc-reveal" aria-label="${esc(word.en)}: dinle ve Türkçesini göster"><strong>${esc(word.en)}</strong><span class="pc-speaker" aria-hidden="true">🔊</span></button><div class="pc-answer"><p class="pc-meaning" aria-live="polite">Türkçesini görmek için karta dokun</p><div class="pc-actions"><button class="pc-again" disabled><span aria-hidden="true">✕</span>Tekrar çalış</button><button class="pc-known" disabled><span aria-hidden="true">✓</span>Biliyorum</button></div></div><span class="pc-leaf pc-leaf-bottom" aria-hidden="true">🌿</span></article></div><p class="pc-note">${queue.length} kart kaldı${review.size?' · '+review.size+' kelime tekrar listende':''}</p><button class="pc-change">Sınıf / ünite değiştir</button><p class="pc-notice" role="status"></p>`;b.querySelector('.pc-reveal').onclick=()=>{if(!revealed){revealed=true;b.querySelector('.pc-meaning').textContent=word.tr;b.querySelectorAll('.pc-actions button').forEach(x=>x.disabled=false);b.querySelector('.pc-card').classList.add('pc-revealed');}say(word.en);};b.querySelector('.pc-again').onclick=()=>judge(false);b.querySelector('.pc-known').onclick=()=>judge(true);b.querySelector('.pc-change').onclick=()=>{window.speechSynthesis?.cancel();setup();};}
 function judge(yes){if(!revealed||!queue.length)return;revealed=false;window.speechSynthesis?.cancel();const id=queue.shift();if(!first.has(id))first.set(id,yes);position++;if(yes){known.add(id);review.delete(id);}else{review.add(id);queue.push(id);}draw();}
 function start(){known=new Set();review=new Set();first=new Map();queue=words.map((_,i)=>i);position=0;session={runId:crypto.randomUUID(),name:displayName,grade:Number(grade),unit:Number(unit),total:words.length,started:Date.now(),saved:false,saving:false};draw();}
 async function request(payload){if(typeof apiURL==='undefined')throw Error('Önizlemede sonuç kaydedilmez.');const r=await fetch(apiURL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.mesaj||d.message||'Sunucuya ulaşılamadı.');return d;}
 function finish(){const b=body(),s=session;if(!s)return;const correct=[...first.values()].filter(Boolean).length;s.payload=s.payload||{islem:'papiKartSonucKaydet',runId:s.runId,isim:s.name,sinif:s.grade,unite:s.unit,toplam:s.total,biliyorum:correct,tekrar:s.total-correct,suresaniye:Math.round((Date.now()-s.started)/1000)};b.innerHTML='<img class="pc-finish-papi" src="papi-welcome-v2.png" alt="Mutlu Papi" width="110" height="121"><h2>Desteyi tamamladın!</h2><p class="pc-sub">'+Math.round(correct/s.total*100)+' / 100 puan</p><p class="pc-note">İlk tur: '+correct+' biliyorum · '+(s.total-correct)+' tekrar çalış.<br>Bu, kendi değerlendirmen. Altın, XP veya hediye verilmez.</p><p class="pc-save-status" role="status"></p><button class="pc-start pc-save" hidden>Kaydı tekrar dene</button><div class="pc-ranking" aria-live="polite"></div><button class="pc-start pc-repeat">Aynı desteyi tekrar çalış</button><button class="pc-change">Başka ünite seç</button>';b.querySelector('.pc-repeat').onclick=start;b.querySelector('.pc-change').onclick=setup;b.querySelector('.pc-save').onclick=()=>save(s,b);save(s,b);}
 async function save(s,b){if(s.saving||s.saved)return;s.saving=true;const label=b.querySelector('.pc-save-status'),retry=b.querySelector('.pc-save');label.textContent='Sonucun kaydediliyor…';retry.hidden=true;try{const d=await request(s.payload);s.saved=true;label.textContent='Sonucun kaydedildi: '+d.isim;await ranking(s,b);}catch(e){label.textContent='Kaydedilemedi: '+e.message;retry.hidden=false;}finally{s.saving=false;}}
 async function ranking(s,b){const el=b.querySelector('.pc-ranking');try{const d=await request({islem:'papiKartSiralamaGetir',sinif:s.grade,unite:s.unit});el.innerHTML='<h3>Papi Kartları sıralaması</h3><p class="pc-note">Bu sınıf ve ünite · En iyi öz değerlendirme puanı</p><ol>'+d.liste.map(r=>'<li><span>'+esc(r.isim)+'</span><b>'+esc(r.puan)+' puan</b></li>').join('')+'</ol>';if(!d.liste.length)el.innerHTML+='<p>Henüz sonuç yok.</p>';}catch(e){el.textContent='Sıralama yüklenemedi.';const button=document.createElement('button');button.className='pc-change';button.textContent='Sıralamayı tekrar yükle';button.onclick=()=>ranking(s,b);el.append(button);}}
 async function open(){frame();const b=body(),ticket=++run;b.innerHTML='<p class="pc-sub" role="status">Papi kelime desteni hazırlıyor…</p>';loading=true;try{if(!(window.masterKelimeHavuzu||[]).length&&typeof window.dijiKelimeHavuzunuYukle==='function')await window.dijiKelimeHavuzunuYukle();if(ticket!==run||!root)return;loading=false;if(!(window.masterKelimeHavuzu||[]).length){b.innerHTML='<p class="pc-sub" role="alert">Kelime destesi henüz yüklenemedi. İnternet bağlantını kontrol edip tekrar dene.</p><button class="pc-start">Tekrar dene</button>';b.querySelector('button').onclick=open;return;}setup();}catch(e){if(ticket!==run||!root)return;loading=false;b.innerHTML='<p class="pc-sub" role="alert">Kelimeler yüklenemedi.</p><button class="pc-start">Tekrar dene</button>';b.querySelector('button').onclick=open;}}
 function mount(){const grid=document.querySelector('#tab-aktiviteler .az-grid2x2');if(!grid||grid.querySelector('#papiCardsActivity'))return;const btn=document.createElement('button');btn.id='papiCardsActivity';btn.type='button';btn.className='az-gcard dm-toy-card';btn.dataset.dmParty='solo';btn.style.setProperty('--toy-bg','#e6efdc');btn.style.setProperty('--toy-edge','#afcba4');btn.innerHTML='<div class="az-gcard-icon"><img src="papi-welcome-v2.png" alt="" width="60" height="66" style="max-height:64px;object-fit:contain"></div><div class="az-gcard-title">Papi Kartları</div><div class="ak-acik">Dokun, dinle ve kelimeleri öğren</div><div class="ak-etiket">Kelime ezberi · Süresiz</div>';btn.onclick=open;grid.append(btn);}
 document.addEventListener('keydown',e=>{if(!root)return;if(e.key==='Escape'){e.preventDefault();close();return;}if(e.key==='Tab'){const list=[...root.querySelectorAll('button:not(:disabled),input,select,summary,[tabindex="0"]')].filter(x=>x.getClientRects().length);if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 window.dmPapiCards={open,close};mount();const host=document.getElementById('tab-aktiviteler');if(host)new MutationObserver(mount).observe(host,{childList:true,subtree:true});
})();
