/* Serialize notices around Papi's tour and the first real exercise. */
(()=>{'use strict';
const who=()=>typeof aktifOgrenciAdi==='undefined'?'':String(aktifOgrenciAdi||'');
const noticeSelector='#duyuruOverlay,#duyuruGecmisModal,#dmGoalAnnouncement,#dmWeeklyPanel,#dmLevelUp,#dmNudge,.od-perde,.kr-perde,.dv-perde,.cb-kart,.bk-kart,.yo-toast,.uy-serit,.yo-davet,.tv-kart,.sa-perde,.cog-perde,.kur-perde';
const visible=e=>!!e&&e.isConnected&&!e.classList.contains('dm-papi-held')&&e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden'&&getComputedStyle(e).display!=='none';
let queue=[],actor=who(),pending=false,executing='',nextAt=0,held=[],practice=null;
const exercise=()=>!!document.querySelector('#dmStoryLesson,.bz-oyun,#genelSonucOverlay.acik')||!!practice;
const holding=()=>!!window.dmPapiTour?.active()||exercise();
const shown=()=>[...document.querySelectorAll(noticeSelector)].some(visible);
function blocked(){return document.hidden||holding()||pending||shown()||Date.now()<nextAt;}
function defer(key,run){if(!document.hidden&&!holding()&&!shown()&&(!pending||executing===key)&&Date.now()>=nextAt)return false;const existing=queue.find(x=>x.key===key&&x.owner===who());if(existing)existing.run=run;else queue.push({key,run,owner:who()});return true;}
function suspend(){for(const e of document.querySelectorAll(noticeSelector)){if(e.isConnected&&!e.classList.contains('dm-papi-held')&&e.getClientRects().length>0&&getComputedStyle(e).display!=='none'){e.classList.add('dm-papi-held');if(!held.some(x=>x.el===e))held.push({el:e,owner:who()});}}document.body.classList.toggle('dm-papi-notices-paused',holding());}
function reset(){for(const h of held){if(['duyuruOverlay','duyuruGecmisModal'].includes(h.el.id)){h.el.style.display='none';h.el.classList.remove('dm-papi-held');}else h.el.remove();}held=[];queue=[];pending=false;executing='';nextAt=0;practice=null;document.getElementById('dmPapiFirstStart')?.remove();document.body.classList.remove('dm-papi-notices-paused');}
setInterval(async()=>{if(actor!==who()){reset();actor=who();return;}if(holding()){suspend();return;}document.body.classList.remove('dm-papi-notices-paused');if(blocked())return;const h=held.shift();if(h){if(h.owner===who()&&h.el.isConnected){h.el.classList.remove('dm-papi-held');nextAt=Date.now()+1000;}return;}const item=queue.shift();if(!item||item.owner!==who())return;const turn=actor;pending=true;executing=item.key;try{await item.run();}catch{}finally{if(turn===actor){executing='';pending=false;nextAt=Date.now()+1000;}}},350);
new MutationObserver(()=>{if(holding())suspend();}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['style']});
function later(el,run,delay){let paused=false;function tick(){if(!el.isConnected)return;if(holding()||el.classList.contains('dm-papi-held')){paused=true;setTimeout(tick,500);}else if(paused){paused=false;setTimeout(tick,delay);}else run();}setTimeout(tick,delay);}
window.dmPapiNotices={blocked,defer,suspend,later};
function loading(text){let el=document.getElementById('dmPapiFirstStart');if(!el){el=document.createElement('div');el.id='dmPapiFirstStart';el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.innerHTML='<section><img src="papi-welcome-v2.png" alt="Papi"><h2>İlk keşfin başlıyor!</h2><p role="status"></p><button type="button" hidden>Tekrar dene</button><button type="button" class="papi-first-return" hidden>Parkura dön</button></section>';document.body.append(el);}el.querySelector('p').textContent=text;return el;}
async function start(purpose,route){if(practice)return;const owner=who(),mode=purpose==='school'?'school':'independent';practice={owner,mode,starting:true,locked:false};suspend();const el=loading('Papi ilk çalışmanı hazırlıyor…');const attempt=async()=>{if(owner!==who())return reset();el.querySelectorAll('button').forEach(b=>b.hidden=true);practice.starting=true;practice.locked=false;try{await route();if(owner!==who())return reset();practice.locked=true;const ok=mode==='school'?await window.dmPapiStartAdventure?.():await window.dmStoryPath?.open(0,{intro:true});if(owner!==who())return reset();if(!ok)throw Error('Çalışma açılamadı. Bağlantını, kelime bankasını ve enerjini kontrol edip tekrar dene.');if(practice)practice.starting=false;el.remove();}catch(e){if(owner!==who())return reset();if(practice){practice.starting=false;practice.locked=false;}window.dmStoryPath?.close(true);el.querySelector('p').textContent=e.message||'Çalışma açılamadı. Tekrar dene.';el.querySelectorAll('button').forEach(b=>b.hidden=false);el.querySelector('button').focus();}};el.querySelector('button').onclick=attempt;el.querySelector('.papi-first-return').onclick=()=>{el.remove();practice=null;window.dmStoryPath?.close();nextAt=Date.now()+1000;};await attempt();}
function complete(mode){if(practice?.mode===mode){practice=null;nextAt=Date.now()+1000;}}
const locked=mode=>!!practice?.locked&&practice.mode===mode&&practice.owner===who();
function recover(mode){if(practice?.mode===mode){practice.locked=false;const back=document.querySelector(mode==='independent'?'.ds-back':'#bzCik');if(back)back.disabled=false;}}
window.dmPapiFirstPractice={start,complete,locked,recover};
document.addEventListener('click',e=>{if(!practice?.locked)return;const b=e.target.closest('[data-ekran],[data-dm-tab],[data-path],.ds-back,#bzCik');if(b){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('keydown',e=>{if((practice?.locked||window.dmPapiTour?.active())&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('dm:login',()=>{reset();actor=who();});
})();
