(function(){'use strict';
const C=window.DijiProgressionCatalog,R=window.DijiProgressRules;
let leagueData=[],actor='',status=null,busy=false,lastRefresh=0,baseline=0,pending=null,jokerRun=null,jokerUses=0,wraps=new Map();
const who=()=>typeof aktifOgrenciAdi==='undefined'?'':String(aktifOgrenciAdi||'');
const student=()=>!!who()&&who().toLowerCase()!=='teacher'&&!window.dmGuestMode;
const ready=()=>student()&&typeof yo!=='undefined'&&!!yo&&typeof yoHazirMi==='function'&&yoHazirMi();
const level=()=>ready()?R.progress(R.migrate(yo)).level:1;
const toast=m=>window.yoToast?.(m);
function allowed(code){if(!student())return true;if(!ready())return false;if(code==='akis')return !!status?.feed;return level()>=(C.gates[code]||1);}
function need(code){return code==='akis'?'Ana parkurda 3. durağa ulaşınca açılır.':(C.gates[code]||1)+'. seviyede açılır.';}
function requireFeature(code){if(allowed(code))return true;toast('🔒 '+need(code));return false;}
function itemAllowed(o,quiet=false){const ok=!student()||ready()&&level()>=C.itemLevel(o);if(!ok&&!quiet)toast('🔒 Bu ürün '+C.itemLevel(o)+'. seviyede açılır.');return ok;}
async function api(op,data={}){const r=await fetch(apiURL,{method:'POST',body:JSON.stringify({islem:op,ogrenci:who(),t:localStorage.getItem('ing_token')||'',...data})});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.mesaj||d.message||'İşlem tamamlanamadı');return d;}
async function sync(){if(!ready())throw Error('Öğrenci verisi henüz yüklenmedi.');R.migrate(yo);const d=await api('ekVeriKaydet',{anahtar:'yo',deger:JSON.stringify(yo)});if(d.status==='bekliyor')throw Error('Verilerin yükleniyor, birazdan tekrar dene.');return d;}
async function refresh(force=false){if(document.hidden&&!force||!ready()||busy||!force&&Date.now()-lastRefresh<60000)return;busy=true;const owner=who();try{const d=await api('seviyeDurumu');if(owner===who()){status=d;lastRefresh=Date.now();if(d.level>=5){try{leagueData=(await api('seviyeLigListesi')).liste||[];}catch{}}paint();}}catch(e){}finally{busy=false;}}
function install(){for(const [fn,code] of Object.entries(C.functions)){const old=window[fn];if(typeof old!=='function'||old===wraps.get(fn))continue;const wrapped=function(){if(!requireFeature(code))return;if(student()&&fn.endsWith('Baslat')&&code.startsWith('oyun_')&&typeof window.genelEnerjiKalan==='number'&&window.genelEnerjiKalan<3&&!window.dmOdevEnerjiMuaf?.()){toast('⚡ Oyuna başlamak için 3 enerji gerekli.');return;}return old.apply(this,arguments);};Object.assign(wrapped,old);wraps.set(fn,wrapped);window[fn]=wrapped;}
 for(const fn of ['dcSeviyeSec']){const old=window[fn];if(typeof old==='function'&&old!==wraps.get(fn)){const w=function(kod){if(student()){const code=String(kod).toUpperCase(),idx=['A1','A2','B1','B2'].indexOf(code),n=[2,9,16,23][idx];if(idx<0||level()<n){toast('🔒 '+n+'. seviyede açılır.');return;}if(idx>0&&!status?.lessons?.[code]){toast('🔒 Önce '+['A1','A2','B1'][idx-1]+' derslerinin tamamını bitir.');refresh(true);return;}}return old.apply(this,arguments);};Object.assign(w,old);window[fn]=w;wraps.set(fn,w);}}
 const avatar=window.maAvatar;if(typeof avatar==='function'&&avatar!==wraps.get('maAvatar')){const w=function(o){const name=o?.id==='ben'?who():o?.ad||o?.id;const raw=typeof maSosyalListe!=='undefined'?maSosyalListe.find(x=>String(x.ogrenci).toLowerCase()===String(name).toLowerCase()):null;const n=String(name).toLowerCase()===who().toLowerCase()?level():raw?C.level(raw.totalXp||0):o?.playerLevel;const html=avatar.apply(this,arguments);return Number.isInteger(n)?'<span class="dm-avatar-level">'+html+'<small class="dm-mini-level" aria-label="Seviye '+n+'">Sv. '+n+'</small></span>':html;};window.maAvatar=w;wraps.set('maAvatar',w);}
 const old=window.maSekmeSec;if(typeof old==='function'&&old!==wraps.get('maSekmeSec')){const w=function(s){if(['akis','kesfet','lig','vitrin'].includes(s)&&!requireFeature(s))return;return old.apply(this,arguments);};Object.assign(w,old);window.maSekmeSec=w;wraps.set('maSekmeSec',w);}
 for(const fn of ['maOlayGonder','maBildirimGonder']){const old=window[fn];if(typeof old==='function'&&old!==wraps.get(fn)){const w=function(target,tur){if(!requireFeature(tur==='takip'?'takip':'tebrik'))return;return old.apply(this,arguments);};Object.assign(w,old);window[fn]=w;wraps.set(fn,w);}}
 const use=window.jokerKullan;if(typeof use==='function'&&use!==wraps.get('jokerKullan')){const w=function(){if(!requireFeature('joker'))return;if(typeof jk!=='undefined'&&jokerRun!==jk){jokerRun=jk;jokerUses=0;}const used=jokerUses,q=C.quota(level());const kind=arguments[0],had=typeof jk!=='undefined'&&jk.kullanilan?.has(kind),stock=yo.jokerEnv?.[kind]||0;const succeeded=()=>typeof jk!=='undefined'&&jk.kullanilan?.has(kind)&&(!had||(yo.jokerEnv?.[kind]||0)<stock);if(student()&&used>=q){if(used!==3||level()<30||!(yo.dmExtraJoker>0)){toast('🃏 Bu oyundaki joker hakkın doldu.');return;}const before=used,result=use.apply(this,arguments);if(succeeded()){jokerUses++;yo.dmExtraJoker--;window.yoKaydet?.();}return result;}const result=use.apply(this,arguments);if(succeeded())jokerUses++;return result;};Object.assign(w,use);window.jokerKullan=w;wraps.set('jokerKullan',w);}
}
function mark(el,code){const locked=!allowed(code);el.classList.toggle('dm-level-locked',locked);if(locked){el.dataset.dmLevelLock=code;el.setAttribute('aria-disabled','true');el.title=need(code);}else if(el.dataset.dmLevelLock){delete el.dataset.dmLevelLock;el.removeAttribute('aria-disabled');el.removeAttribute('title');}}
function paint(){if(!student())return;for(const f of C.features)for(const selector of f.selectors)document.querySelectorAll(selector).forEach(e=>mark(e,f.code));
 document.querySelectorAll('[onclick]').forEach(e=>{const match=(e.getAttribute('onclick')||'').match(/\b([A-Za-z_$][\w$]*)\s*\(/);if(match&&C.functions[match[1]])mark(e,C.functions[match[1]]);});
 document.querySelectorAll('[data-dm-goals]').forEach(e=>{const code=e.dataset.dmGoals==='daily'?'gunluk_gorev':'haftalik_hedef';mark(e,code);e.querySelectorAll('button').forEach(b=>mark(b,code));});
 document.querySelectorAll('[data-social]').forEach(e=>{const code={message:'hazir_mesaj',duel:'duello',gift:'enerji_hediye'}[e.dataset.social];if(code)mark(e,code);});
 document.querySelectorAll('[data-k="koleksiyon"],[data-k="karakterler"],#bcKoleksiyon').forEach(e=>mark(e,'koleksiyon'));
 document.querySelectorAll('.ka-cins,#kaKaristir').forEach(e=>mark(e,'karakter'));
 document.querySelectorAll('#dlSekmeler [data-s]').forEach(e=>{const cat={vitrin:15,sac:17,ust:20,dis:20,alt:23,tek:23,ayak:26,aks:29,sapka:32,bas:32,kombin:35,dost:29,cik:38,yuz:15,sandik:5}[e.dataset.s];if(cat){const locked=level()<cat;e.classList.toggle('dm-level-locked',locked);if(locked){e.dataset.dmCategoryLevel=cat;e.setAttribute('aria-disabled','true');}else{delete e.dataset.dmCategoryLevel;e.removeAttribute('aria-disabled');}}});
 const store=document.getElementById('dlSekmeler');if(store&&level()>=30&&!document.getElementById('dmExtraJokerBuy')){const b=document.createElement('button');b.id='dmExtraJokerBuy';b.textContent='🃏 4. joker hakkı · 1200 altın';b.onclick=extraJoker;store.append(b);}
 document.querySelectorAll('.so-hedef button').forEach(e=>mark(e,'haftalik_hedef'));
 document.querySelectorAll('#soPanel [id*="Gorev"],#yoGorevler').forEach(e=>mark(e,'gunluk_gorev'));
 document.querySelectorAll('[data-jm],.jm-oyun-al').forEach(e=>mark(e,'joker_magaza'));
 document.querySelectorAll('#yoDikteKart').forEach(e=>mark(e,'oyun_dikte'));
 document.querySelectorAll('#yoCumleKart').forEach(e=>mark(e,'oyun_cumle'));
 document.querySelectorAll('#dmUcusteKart,#dmRotaKart').forEach(e=>mark(e,'iki_kisilik'));
 document.querySelectorAll('#bottomNavMobile [data-ekran]').forEach(e=>{const code={'tab-derscalis':'ders','tab-aktiviteler':'aktiviteler','tab-meduakis':'akis','tab-magaza':'magaza'}[e.dataset.ekran];if(code)mark(e,code);});
 document.querySelectorAll('#bzJkAl').forEach(e=>mark(e,'joker_magaza'));
 document.querySelectorAll('[data-dm-league-level]').forEach(e=>e.classList.toggle('dm-level-locked',level()<Number(e.dataset.dmLeagueLevel)));
 document.querySelectorAll('#jkBar button').forEach(e=>{if(level()<15)mark(e,'joker');});
}
document.addEventListener('click',e=>{if(!student())return;const b=e.target.closest('[data-dm-level-lock],[data-dm-category-level],[data-dm-league-level],[data-s],[data-nav],[data-social]');if(!b)return;if(b.dataset.dmLeagueLevel&&level()<Number(b.dataset.dmLeagueLevel)){e.preventDefault();e.stopImmediatePropagation();toast('🔒 Bu lig '+b.dataset.dmLeagueLevel+'. seviyede açılır.');return;}if(b.dataset.dmCategoryLevel&&level()<Number(b.dataset.dmCategoryLevel)){e.preventDefault();e.stopImmediatePropagation();toast('🔒 Bu kategori '+b.dataset.dmCategoryLevel+'. seviyede açılır.');return;}const code=b.dataset.dmLevelLock||({meduakis:'akis',ders:'ders',aktiviteler:'aktiviteler',magaza:'magaza'}[b.dataset.nav])||(['akis','kesfet','lig','vitrin'].includes(b.dataset.s)?b.dataset.s:null);if(code&&!allowed(code)){e.preventDefault();e.stopImmediatePropagation();requireFeature(code);}},true);
function sprite(l){const stage=l<=5?'baby':l<=14?'reader':l<=29?'explorer':'master';return '<div class="dm-papi-stage '+stage+'"><i role="img" aria-label="Papi papağan"></i><span class="dm-papi-prop">'+C.levels[l-1].prop+'</span></div>';}
async function extraJoker(){if(!requireFeature('iki_kisilik'))return;try{await sync();const d=await api('seviyeEkJokerAl');Object.assign(yo,d.yo);toast('🃏 Bir oyun için 4. joker hakkı çantanda!');}catch(e){toast(e.message);}}
function badges(l){return C.levels.slice(0,l).filter(x=>x.benefits.some(b=>b.includes('rozeti')));}
function panel(){if(!ready()){toast('Seviye bilgilerin yükleniyor. Birazdan tekrar dene.');return;}document.getElementById('dmProgressOverlay')?.remove();const p=R.progress(R.migrate(yo)),info=C.levels[p.level-1],el=document.createElement('div');el.id='dmProgressOverlay';el.className='dm-progress-overlay';el.innerHTML='<section class="dm-progress-sheet" role="dialog" aria-modal="true" aria-labelledby="dmProgressTitle"><button class="dm-progress-close" aria-label="Kapat">×</button>'+sprite(p.level)+'<h2 id="dmProgressTitle">'+info.name+'</h2><p class="dm-progress-caption-v2">Kalıcı seviyen öğrenme yolculuğunu gösterir. XP biriktirdikçe yeni özellikler açılır.</p><b>Seviye '+p.level+' · '+p.xp.toLocaleString('tr-TR')+' XP</b><div class="dm-progress-numbers"><span><b>'+p.xp.toLocaleString('tr-TR')+'</b>Toplam kazanılan XP</span><span><b>'+(p.next===null?'✓':p.remaining)+'</b>Sonraki seviyeye kalan XP</span></div><div class="dm-progress-track"><i style="width:'+p.ratio*100+'%"></i></div><p>'+(p.next===null?'Yolculuğun zirvesindesin!':p.remaining+' XP sonra '+(p.level+1)+'. seviye')+'</p><div class="dm-next-unlocks">'+(p.next===null?'🏆 Efsane Papağan':['Bir sonraki seviyede açılacaklar'].concat(C.levels[p.level].benefits).map(x=>'<p>🔓 '+x+'</p>').join(''))+'</div><details class="dm-earned-badges"><summary>🪶 Kazandığın seviye rozetleri</summary><small>Tüyler, ulaştığın özel seviyelerin hatıra rozetleridir. Harcanmaz ve XP yerine geçmez.</small>'+badges(p.level).map(x=>'<p>'+x.prop+' '+x.name+'</p>').join('')+'</details><p class="dm-mystery">'+(p.next===null?'':Array.from({length:Math.min(4,39-p.level)},()=>'<span>🔒 ?</span>').join(''))+'</p><p class="dm-mystery-caption">Daha sonraki seviyelerin sürprizleri şimdilik gizli.</p><button class="dm-progress-go">Sandıklarım</button></section>';document.body.append(el);const prior=document.activeElement;const close=()=>{el.remove();prior?.focus?.();};el.querySelector('.dm-progress-close').onclick=close;el.querySelector('.dm-progress-go').onclick=()=>{close();chests();};dialogKeys(el,close);el.querySelector('button').focus();}
function dialogKeys(el,close){el.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const b=[...el.querySelectorAll('button:not([hidden]):not(:disabled)')],i=b.indexOf(document.activeElement);e.preventDefault();b[(i+(e.shiftKey?-1:1)+b.length)%b.length].focus();}});}
function celebrate(from,to){const el=document.createElement('div');el.id='dmLevelUp';el.className='dm-level-up';el.innerHTML='<section role="dialog" aria-modal="true" aria-labelledby="dmLevelUpTitle"><div class="dm-papi-sparks">✦ · ✧ · ✦ · ✧</div><small>YENİ BİR KANAT, YENİ BİR KEŞİF</small><h2 id="dmLevelUpTitle">'+C.levels[to-1].name+'</h2><b class="dm-level-number">SEVİYE '+to+'</b><button class="dm-papi-reveal" aria-label="Papi’ye dokun, açılan özellikleri gör">'+sprite(to)+'</button><p class="dm-reveal-hint">Papi’ye dokun, yeni özelliklerini keşfet!</p><div class="dm-unlock-cards" hidden></div><button class="dm-level-continue" hidden>Yolculuğa devam et</button></section>';document.body.append(el);const prior=document.activeElement,reveal=()=>{const cards=el.querySelector('.dm-unlock-cards');if(!cards.hidden)return;cards.hidden=false;cards.innerHTML=C.levels.slice(from,to).map(x=>'<article><span>'+x.prop+'</span><div><b>'+x.level+'. seviye · '+x.name+'</b><p>'+x.benefits.join(' · ')+'</p></div></article>').join('');el.querySelector('.dm-reveal-hint').hidden=true;el.querySelector('.dm-level-continue').hidden=false;el.classList.add('revealed');el.querySelector('.dm-level-continue').focus();};const close=()=>{if(el.querySelector('.dm-unlock-cards').hidden){reveal();return;}el.remove();prior?.focus?.();};el.querySelector('.dm-papi-reveal').onclick=reveal;el.querySelector('.dm-level-continue').onclick=close;dialogKeys(el,close);el.querySelector('.dm-papi-reveal').focus();}
async function chests(){if(!requireFeature('sandik'))return;await refresh(true);const el=document.createElement('div');el.className='dm-progress-overlay';el.id='dmChestPanel';el.innerHTML='<section class="dm-progress-sheet" role="dialog" aria-modal="true" aria-labelledby="dmChestTitle"><button class="dm-progress-close" aria-label="Kapat">×</button><h2 id="dmChestTitle">Parkur sandıkları</h2><p>Her sandık bir kez açılır. Seviyen ve parkur ilerlemen birlikte değerlendirilir.</p>'+C.chests.map(c=>{const state=status?.chests?.[c.id];return '<article class="dm-chest-row"><span>🧰</span><div><b>'+c.name+'</b><small>Seviye '+c.level+' · '+({bronze:'Ana parkurda ilk 3 durak',silver:'Ana parkurun yarısı',gold:'İlk 2 parkur tamam',crystal:'İlk 3 parkur tamam',legend:'Tüm parkurlar tamam'}[c.id])+'</small></div><button data-chest="'+c.id+'" '+(state==='ready'?'':'disabled')+'>'+(state==='claimed'?'Alındı':state==='ready'?'Aç':'Kilitli')+'</button></article>';}).join('')+'</section>';document.body.append(el);const close=()=>el.remove();el.querySelector('.dm-progress-close').onclick=close;dialogKeys(el,close);el.querySelectorAll('[data-chest]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await sync();const d=await api('seviyeSandikAc',{sandik:b.dataset.chest});if(d.yo){Object.assign(yo,d.yo);window.yoKaydet?.();window.yoGoster?.();}toast('🎁 '+d.gold+' altın!');status=null;lastRefresh=0;await refresh(true);b.textContent='Alındı';}catch(e){toast(e.message);b.disabled=false;}});el.querySelector('button').focus();}
window.maLigSiralama=function(){const liste=leagueData.map(o=>({ad:o.name,sinif:String(o.class||''),puan:0,xp:o.xp,sira:o.rank,kod:o.league,benMi:o.name.toLowerCase()===who().toLowerCase()}));return {liste,harita:Object.fromEntries(liste.map(x=>[x.ad.toLowerCase(),x]))};};
window.dmProgression={paint,allowed,require:requireFeature,level,itemAllowed,refresh,chests,status:()=>status,parkur:(b)=>!student()||level()>=[1,10,20,30][b],quota:()=>C.quota(level()),sync,buyExtraJoker:extraJoker,previewAnimation:()=>celebrate(Math.max(0,level()-1),level())};
window.dolapSandikAc=window.bcSandikAc=window.sandikTorenAc=chests;
const progressOpen=()=>{const b=document.getElementById('dmLevelBadge');if(b)b.onclick=panel;window.dmProgressPanel=Object.assign(window.dmProgressPanel||{},{open:panel});};
const originalFetch=window.fetch;window.fetch=async function(url,opt){const owner=who(),r=await originalFetch.apply(this,arguments);if(opt?.body&&typeof opt.body==='string'&&opt.body.includes('"dersTestSonucKaydet"')&&r.ok){r.clone().json().then(d=>{if(owner!==who())return;if(d.eklenenEnerji>0){window.headerEnerjiGoster?.(d.enerjiKalan,d.enerjiMax);toast('📘 İlk başarılı ders: +'+d.eklenenEnerji+' enerji');}refresh(true);}).catch(()=>{});}return r;};
setInterval(()=>{install();progressOpen();const name=ready()?who():'';if(name!==actor){leagueData=[];document.getElementById('dmLevelUp')?.remove();document.getElementById('dmChestPanel')?.remove();actor=name;status=null;lastRefresh=0;baseline=name?level():0;pending=null;}paint();if(!name)return;refresh();const now=level();if([5,10,14].includes(now)){const k='dm_store_hint:'+actor+':'+now;if(!localStorage.getItem(k)){localStorage.setItem(k,'1');toast('🪙 Altınların birikiyor! Mağaza 15. seviyede açılacak.');}}if(now>baseline){pending={from:pending?.from??baseline,to:now};baseline=now;}if(pending&&!document.hidden&&!document.getElementById('dmLevelUp')&&!Array.from(document.querySelectorAll('#genelSonucOverlay,#dmGoalAnnouncement,#dmWeeklyPanel')).some(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden')){const p=pending;pending=null;celebrate(p.from,p.to);}},700);
install();paint();progressOpen();
})();
