/* Papi's story route: independent account-owned learning progression. */
(()=>{'use strict';
const curriculum=()=>window.DMStoryCurriculum||[],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const account=()=>{let token='';try{token=sessionStorage.getItem('ing_ogr_token')||localStorage.getItem('ing_token')||''}catch{}let hash=0;for(const c of token)hash=(hash*31+c.charCodeAt(0))>>>0;return (typeof aktifOgrenciAdi!=='undefined'?String(aktifOgrenciAdi):'teacher')+':'+hash};
const gender=()=>typeof yo!=='undefined'&&yo?.karakter?.cins==='k'?'girl':typeof yo!=='undefined'&&yo?.karakter?.cins==='e'?'boy':'neutral';
let modal=null,ownerAtOpen=null,session=null,chapter=null,displayCursor=0,busy=false,accepted=false,replay=false,built=[],selectedCards=new Set(),translation=false,origin=null,requestEpoch=0,voiceOn=storage.get('dm_story_voice')!=='off';
let summary=[],summaryAccount='',summaryLoaded=false,summaryPromise=null;
const hosts=new WeakMap();
async function api(op,data={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(apiURL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({islem:op,...data}),signal:controller.signal}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.mesaj||'İşlem tamamlanamadı.');return d;}catch(e){if(e.name==='AbortError')throw Error('Bağlantı gecikti. İlerlemen korunuyor; tekrar dene.');throw e}finally{clearTimeout(timeout)}}
function loadSummary(force=false){const a=account();if(summaryAccount!==a){summary=[];summaryLoaded=false;summaryPromise=null;summaryAccount=a}if(!force&&summaryLoaded)return Promise.resolve(summary);if(summaryPromise)return summaryPromise;summaryPromise=api('storyStatus').then(d=>{if(account()===a){summary=d.progress;summaryLoaded=true}return summary}).finally(()=>{summaryPromise=null});return summaryPromise}
function nextChapter(){return curriculum().findIndex(c=>!summary.some(s=>s.chapter===c.id&&s.completed))}
function updateSummary(r){summary=summary.filter(x=>x.chapter!==r.chapter);summary.push({chapter:r.chapter,cursor:r.cursor,completed:r.completed,version:r.version});summaryLoaded=true;summaryAccount=account();document.querySelectorAll('.dm-story-map').forEach(x=>renderMap(x))}
function mapMarkup(){return '<div class="dm-story-map"><div class="ds-map-status" role="status"></div><div class="ds-map-track" aria-label="Öğrenme durakları"></div><img class="ds-map-papi" src="parkur-map-papi-v1.svg" alt="Papi"><button type="button" class="ds-map-continue">Devam et ›</button></div>'}
function renderMap(map){const track=map.querySelector('.ds-map-track'),next=nextChapter(),all=curriculum();track.innerHTML='<div class="ds-map-route">'+all.map((c,i)=>{const r=summary.find(s=>s.chapter===i),done=!!r?.completed,available=done||i===next,offset=[42,68,43,66][i%4];return (i%10===0?'<div class="ds-world" style="top:'+(i*118+18)+'px">'+esc(c.world)+' · '+c.cefr+'</div>':'')+'<button type="button" class="ds-node '+(done?'done':available?'current':'locked')+'" style="left:'+offset+'%;top:'+(i*118+100)+'px" data-chapter="'+i+'" '+(!available?'disabled':'')+' aria-label="'+esc(c.title)+(done?', tamamlandı':available?', sıradaki':', kilitli')+'"'+(i===next?' aria-current="step"':'')+'><span class="ds-medallion">'+(done?'✓':available?'🌱':'🔒')+'</span><span class="ds-cefr">'+c.cefr+'</span><b>'+esc(c.title)+'</b></button>'}).join('')+'</div>';track.querySelector('.ds-map-route').style.height=(all.length*118+90)+'px';map.querySelector('.ds-map-status').textContent='🌿 '+summary.filter(x=>x.completed).length+'/'+all.length+' öğrenme yaprağı';const button=map.querySelector('.ds-map-continue');button.textContent=next<0?'Yolculuğu tekrar keşfet ›':'Devam et ›';button.onclick=()=>open(next<0?0:next);track.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>open(Number(b.dataset.chapter)));if(!map.dataset.scrolled){track.scrollTop=Math.max(0,(next<0?0:next)*118-30);map.dataset.scrolled='yes'}}
function mount(host){if(!host||hosts.has(host)||!host.querySelector('.dm-parchment-map'))return;const game=host.querySelector('.dm-parchment-map'),m=document.createElement('div');m.className='dm-story-mode';m.setAttribute('role','group');m.setAttribute('aria-label','Parkur türü');m.innerHTML='<button type="button" data-path="game">🎮 Oyun Parkuru</button><button type="button" data-path="learn">📖 Öğrenme Yolu</button>';host.classList.add('ds-host');host.prepend(m);host.insertAdjacentHTML('beforeend',mapMarkup());const map=host.querySelector('.dm-story-map');hosts.set(host,{game,map,m});async function select(mode){if(mode==='learn'&&modal)close();storage.set('dm_story_path_'+account(),mode);m.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.path===mode)));game.hidden=mode==='learn';map.hidden=mode!=='learn';host.classList.toggle('ds-learning',mode==='learn');if(mode==='game'){return}map.querySelector('.ds-map-status').textContent='Papi öğrenme yolunu hazırlıyor…';try{await loadSummary();if(map.isConnected)renderMap(map)}catch(e){map.querySelector('.ds-map-status').textContent=e.message;map.querySelector('.ds-map-continue').textContent='Yeniden yükle';map.querySelector('.ds-map-continue').onclick=()=>select('learn')}}m.querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.path));select(storage.get('dm_story_path_'+account())||'game')}
function speak(text){if(!voiceOn)return;try{if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;const voices=speechSynthesis.getVoices(),v=voices.find(x=>x.lang==='en-US')||voices.find(x=>x.lang.startsWith('en'));if(v)u.voice=v;u.onerror=()=>{if(modal)note('Ses açılamadı. Yazılı örnek ve Türkçesiyle devam edebilirsin.')};speechSynthesis.speak(u)}catch{}}
function note(text,correct=false){const el=modal?.querySelector('.ds-feedback');if(el){el.textContent=text;el.classList.toggle('correct',correct)}}
function close(){requestEpoch++;try{window.speechSynthesis?.cancel()}catch{}modal?.remove();modal=null;document.body.classList.remove('dm-story-open');busy=false;accepted=false;origin?.focus();origin=null}
function shell(){const g=gender();modal.innerHTML='<div class="ds-lesson-shell"><header class="ds-lesson-header"><button type="button" class="ds-back" aria-label="Bahçeye dön">‹</button><div><small>'+chapter.cefr+' · '+esc(chapter.world)+'</small><h2>'+esc(chapter.title)+'</h2><div class="ds-progress" role="progressbar" aria-label="Durak ilerlemesi" aria-valuemin="0" aria-valuemax="'+chapter.steps.length+'" aria-valuenow="'+displayCursor+'"><i style="width:'+displayCursor/chapter.steps.length*100+'%"></i></div></div><button type="button" class="ds-voice" aria-pressed="'+voiceOn+'" aria-label="Sesli okumayı aç veya kapat">'+(voiceOn?'🔊':'🔇')+'</button></header><div class="ds-scene '+g+'" role="img" aria-label="Papi ve '+(g==='girl'?'kız öğrenci':g==='boy'?'erkek öğrenci':'bahçe')+'"><div class="ds-speech"></div>'+(g==='neutral'?'<img class="ds-neutral-papi" src="parkur-map-papi-v1.svg" alt="Papi">':'')+'</div><section class="ds-panel"><div class="ds-step-label"></div><div class="ds-task"></div><div class="ds-feedback" role="status" aria-live="polite"></div><div class="ds-actions"></div><small class="ds-save-note">'+(replay?'Tekrar turu · yeni yaprak verilmez':'İlerlemen hesabına kaydedilir · yanlışta ceza yok')+'</small></section></div>';modal.querySelector('.ds-back').onclick=close;modal.querySelector('.ds-voice').onclick=()=>{voiceOn=!voiceOn;storage.set('dm_story_voice',voiceOn?'on':'off');modal.querySelector('.ds-voice').textContent=voiceOn?'🔊':'🔇';modal.querySelector('.ds-voice').setAttribute('aria-pressed',String(voiceOn));if(voiceOn)speak(chapter.steps[displayCursor]?.en||'');else window.speechSynthesis?.cancel()}}
async function open(id){if(busy||!curriculum()[id])return;close();origin=document.activeElement;ownerAtOpen=account();chapter=curriculum()[id];modal=document.createElement('div');modal.id='dmStoryLesson';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label',chapter.title);document.body.append(modal);document.body.classList.add('dm-story-open');modal.innerHTML='<div class="ds-loading"><p>Papi hikâyeni hazırlıyor…</p><button type="button">Bahçeye dön</button></div>';modal.querySelector('button').onclick=close;const epoch=requestEpoch;busy=true;try{const r=await api('storyOpen',{chapter:id});if(epoch!==requestEpoch||!modal)return;if(account()!==ownerAtOpen){close();return}session=r;replay=r.completed;displayCursor=replay?0:r.cursor;busy=false;render();modal.querySelector('.ds-back').focus();speak(chapter.steps[displayCursor]?.en||'')}catch(e){if(epoch===requestEpoch&&modal){busy=false;modal.querySelector('p').textContent=e.message}}}
const button=(t,a,cls='')=>'<button type="button" class="'+cls+'" data-action="'+a+'">'+t+'</button>';
function render(){if(!modal)return;accepted=false;built=[];selectedCards.clear();translation=false;if(displayCursor>=chapter.steps.length){finish();return}shell();const task=chapter.steps[displayCursor],area=modal.querySelector('.ds-task'),actions=modal.querySelector('.ds-actions'),speech=modal.querySelector('.ds-speech');speech.textContent=task.kind==='listen'?'🎧 Papi’yi dinle':task.en||'Birlikte öğrenelim!';speech.lang=task.kind==='listen'?'tr':'en';modal.querySelector('.ds-step-label').textContent=(displayCursor+1)+'/'+chapter.steps.length+' · '+task.label;
const audio='<div class="ds-audio">'+button('🎧 Dinle','listen')+button('Türkçesi','translate')+'</div><p class="ds-translation" hidden>'+esc(task.tr||'')+'</p>';
if(task.kind==='scene')area.innerHTML='<p class="ds-story-text">'+esc(task.text)+'</p>'+audio;
if(task.kind==='teach'){area.innerHTML='<p>'+esc(task.text)+'</p><div class="ds-cards">'+task.cards.map((x,i)=>'<button type="button" data-card="'+i+'"><b lang="en">'+esc(x.en)+'</b><span hidden>'+esc(x.tr)+'</span><small>Dinle ve keşfet</small></button>').join('')+'</div>';}
if(['choice','listen'].includes(task.kind))area.innerHTML='<p>'+esc(task.instruction)+'</p>'+(task.kind==='listen'?audio:'<h3>'+esc(task.prompt)+'</h3>'+audio)+'<div class="ds-options">'+task.options.map((x,i)=>'<button type="button" data-answer="'+i+'">'+esc(x)+'</button>').join('')+'</div>';
if(task.kind==='order')area.innerHTML='<p>“'+esc(task.tr)+'” demek için taşları sırala.</p><div class="ds-sentence" aria-live="polite">Cümlen burada oluşacak…</div><div class="ds-tokens">'+task.tokens.map((x,i)=>({x,i})).sort(()=>Math.random()-.5).map(({x,i})=>'<button type="button" data-token="'+i+'">'+esc(x)+'</button>').join('')+'</div>'+audio;
if(task.kind==='speak')area.innerHTML='<p>'+esc(task.text)+'</p>'+audio;
if(task.kind==='write')area.innerHTML='<p>'+esc(task.text)+'</p><label for="dsWriting">Kendi sözlerin<textarea id="dsWriting" maxlength="2000" placeholder="İngilizce yaz…" lang="en">'+esc(session.writing||'')+'</textarea></label>'+audio;
actions.innerHTML=task.kind==='order'?button('Yeniden sırala','clear')+button('Kontrol et','submit','ds-primary'):['choice','listen'].includes(task.kind)?'':button(task.kind==='speak'?'Yüksek sesle tekrar ettim ›':task.kind==='write'?'Yazımı kaydet ve ilerle ›':'Devam et ›','submit','ds-primary');
modal.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));modal.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>advance(Number(b.dataset.answer),b));modal.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.card);selectedCards.add(i);b.querySelector('span').hidden=false;b.classList.add('discovered');speak(task.cards[i].en)});modal.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{if(busy||accepted||b.disabled)return;b.disabled=true;built.push(Number(b.dataset.token));modal.querySelector('.ds-sentence').textContent=built.map(i=>task.tokens[i]).join(' ')});
}
function action(a){const task=chapter.steps[displayCursor];if(a==='listen')speak(task.en||'');if(a==='translate'){translation=!translation;modal.querySelector('.ds-translation').hidden=!translation;modal.querySelector('.ds-speech').textContent=task.en||''}if(a==='clear'&&!busy&&!accepted){built=[];modal.querySelectorAll('[data-token]').forEach(b=>b.disabled=false);modal.querySelector('.ds-sentence').textContent='Cümlen burada oluşacak…'}if(a==='submit'){if(task.kind==='teach'&&selectedCards.size<task.cards.length){note('Önce dört karta dokunup ifadeleri keşfet.');return}let value=task.kind==='order'?built.map(i=>task.tokens[i]).join(' '):task.kind==='write'?modal.querySelector('textarea').value:true;if(task.kind==='write'&&String(value).trim().length<2){note('Kendi İngilizce cümleni yaz; örnekten yararlanabilirsin.');return}advance(value)}}
const norm=s=>String(s).normalize('NFKC').trim().toLowerCase().replace(/[.!?,;:]/g,'').replace(/\s+/g,' ');
async function advance(answer,clicked){if(busy||accepted||!modal)return;busy=true;const epoch=requestEpoch,task=chapter.steps[displayCursor],old=displayCursor;modal.setAttribute('aria-busy','true');note('Kaydediliyor…');try{let r;if(replay){const correct=['choice','listen'].includes(task.kind)?answer===task.answer:task.kind==='order'?norm(answer)===norm(task.answer):true;r={...session,cursor:correct?displayCursor+1:displayCursor,correct,hint:task.hint,completed:correct&&displayCursor+1>=chapter.steps.length};}else r=await api('storyAdvance',{chapter:chapter.id,cursor:session.cursor,version:session.version,answer});if(epoch!==requestEpoch||!modal)return;if(account()!==ownerAtOpen){close();return}session=r;busy=false;modal.removeAttribute('aria-busy');if(!replay)updateSummary(r);if(r.stale){displayCursor=r.cursor;if(r.completed)finish();else render();note('Başka bir ekrandaki ilerlemen yüklendi.');return}if(!r.correct){note('Birlikte tekrar deneyelim: '+(r.hint||chapter.rule));clicked?.classList.add('ds-wrong');return}accepted=true;modal.querySelectorAll('[data-answer],[data-token]').forEach(b=>b.disabled=true);clicked?.classList.add('ds-correct');if(['scene','teach','speak','write'].includes(task.kind)){displayCursor=r.cursor;render();return}note('✓ Güzel! '+(task.tr||''),true);modal.querySelector('.ds-actions').innerHTML=button('Devam et ›','next','ds-primary');modal.querySelector('[data-action=next]').onclick=()=>{if(busy||displayCursor!==old||!accepted)return;displayCursor=r.cursor;render();speak(chapter.steps[displayCursor]?.en||'')}}catch(e){if(epoch===requestEpoch&&modal){busy=false;modal.removeAttribute('aria-busy');note(e.message)}}}
function finish(){shell();modal.querySelector('.ds-speech').textContent='Well done!';modal.querySelector('.ds-step-label').textContent='Durak tamamlandı';modal.querySelector('.ds-task').innerHTML='<div class="ds-complete"><span>🌿</span><h3>'+esc(chapter.title)+' tamamlandı!</h3><p>'+ (replay?'Bildiklerini yeniden pekiştirdin.': 'İlk tamamlamada bir öğrenme yaprağı kazandın. Bahçede yeni durak açıldı.')+'</p><p>'+esc(chapter.cards.map(x=>x.en).slice(0,3).join(' · '))+'</p></div>';modal.querySelector('.ds-actions').innerHTML=button('Bahçeye dön','garden','ds-primary')+(chapter.id<39?button('Sonraki durak ›','nextchapter'):'');modal.querySelector('[data-action=garden]').onclick=close;const next=modal.querySelector('[data-action=nextchapter]');if(next)next.onclick=()=>open(chapter.id+1);modal.querySelector('.ds-save-note').textContent='Öğrenme yolu · '+chapter.cefr+' içerikleri';}
document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape'){close();return}if(e.key==='Tab'){const all=[...modal.querySelectorAll('button:not(:disabled),textarea')].filter(x=>x.offsetParent!==null),first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
window.dmStoryPath={mount,open,close,gender};
const initial=document.getElementById('dmParkurScroll');if(initial)mount(initial);
})();
