(() => {
'use strict';
const catalog=window.DM_FEATURE_CATALOG||[], esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id), who=()=>typeof aktifOgrenciAdi!=='undefined'?aktifOgrenciAdi:'', token=()=>window.dmWeeklyPreview?'preview':localStorage.getItem('ing_token')||'';
let flags=Object.fromEntries(catalog.map(f=>[f.code,true])),admin=false,refreshing=false,weeklyBusy=false,weeklyAccount='',lastWeekly=0;
async function api(op,args={}){const r=await fetch(apiURL,{method:'POST',body:JSON.stringify({islem:op,t:token(),...args})}),d=await r.json();if(!r.ok||d.ok===false)throw Error(d.mesaj||d.message||'İşlem tamamlanamadı.');return d;}
const enabled=(code,depth=0)=>{if(flags[code]===false)return false;const f=catalog.find(f=>f.code===code);return f?.parent&&depth<6?enabled(f.parent,depth+1):true;};
window.dmFeatureEnabled=enabled;
function unavailable(){window.yoToast?.('Bu özellik yakında yayında! 🦜');}
const navCodes={'tab-dunya':'parkur','tab-meduakis':'akis','tab-sanaozel':'sana_ozel','tab-aktiviteler':'aktiviteler','tab-derscalis':'ders','tab-magaza':'magaza'};
function apply(){
 catalog.forEach(f=>{
  const closed=!enabled(f.code)&&!admin;
  f.functions.forEach(fn=>{const original=window[fn];if(typeof original!=='function'||original._dmRelease)return;const wrap=function(...args){if(!admin&&!enabled(f.code)){unavailable();return;}return original.apply(this,args);};Object.assign(wrap,original);wrap._dmRelease=true;window[fn]=wrap;});
  f.selectors.forEach(sel=>document.querySelectorAll(sel).forEach(el=>el.classList.toggle('dm-feature-hidden',closed)));
 });
 document.querySelectorAll('[onclick]').forEach(el=>{const raw=el.getAttribute('onclick')||'',matches=catalog.filter(f=>f.functions.some(fn=>new RegExp('\\b'+fn+'\\s*\\(').test(raw)));if(matches.length)el.classList.toggle('dm-feature-hidden',!admin&&matches.some(f=>!enabled(f.code)));});
 Object.entries(navCodes).forEach(([id,code])=>document.querySelectorAll('#bottomNavMobile [data-ekran="'+id+'"]').forEach(el=>el.classList.toggle('dm-feature-hidden',!admin&&!enabled(code))));
 document.querySelectorAll('[data-social="gift"]').forEach(el=>el.classList.toggle('dm-feature-hidden',!admin&&!enabled('enerji_hediye')&&!enabled('aksesuar_hediye')));
 document.querySelectorAll('#yoDikteKart').forEach(el=>el.classList.toggle('dm-feature-hidden',!admin&&!enabled('oyun_dikte')));
 const single=$('dmSoloTab'),duo=$('dmDuoTab');if(!admin){if(!enabled('tek_kisilik')&&enabled('iki_kisilik')&&duo?.getAttribute('aria-selected')!=='true')duo?.click();if(!enabled('iki_kisilik')&&enabled('tek_kisilik')&&single?.getAttribute('aria-selected')!=='true')single?.click();}
 const menu=document.querySelector('#ogretmenMenuModal .rubric-content');if(menu&&admin&&!$('dmReleaseMenu')){const b=document.createElement('button');b.id='dmReleaseMenu';b.className='ogretmen-menu-btn';b.innerHTML='<span>🎛️ Özellikleri yayına aç / kapat</span>';b.onclick=window.dmReleasePanelAc;menu.append(b);}
 if(!admin)$('dmReleaseMenu')?.remove();
 document.querySelectorAll('.dm-game option').forEach(o=>{const map={Kelime_Liderlik:'kelime',Jeopardy_Liderlik:'jeopardy',Hafiza_Liderlik:'hafiza',Yagmur_Liderlik:'yagmur',Asmaca_Liderlik:'asmaca',KelimeBul_Liderlik:'kelimebul',Eslesme_Liderlik:'eslestirme',Tren_Liderlik:'tren',Dikte_Liderlik:'dikte',Cumle_Liderlik:'cumle',ucus:'ucus',rota:'rota'};o.disabled=!admin&&map[o.value]&&!enabled('oyun_'+map[o.value]);o.hidden=o.disabled;});
}
async function refresh(){if(refreshing)return;refreshing=true;try{const d=await api('yayinOzellikleri');flags=d.flags;admin=d.admin===true;apply();}catch(e){}finally{refreshing=false;}}
window.dmReleasePanelAc=async function(){
 if(!admin){await refresh();if(!admin)return unavailable();}
 $('ogretmenMenuModal').style.display='none';
 const m=window.dmMeduPro.sheet('Özelliklerin yayın takvimi','Yalnızca yönetici görür. Kapalı özellikler öğrencilerden gizlenir; kayıtlı ilerlemeleri korunur.');
 m.body.innerHTML='<div class="dm-release-intro"><img src="mascot-welcome.webp" alt="Papağan"><div><h3>Yenilikler senin elinde</h3><p>İstediğin özelliği hazır olduğunda aç. Açık öğrencinin ekranında görünür, kapalı görünmez.</p></div></div><input class="dm-release-search" type="search" placeholder="Özellik ara…" aria-label="Özellik ara"><div class="dm-release-tools"><button data-all="false">Tümünü kapat</button><button data-all="true">Tümünü aç</button></div><p class="dm-release-status" role="status"></p><div class="dm-release-list"></div>';
 const status=m.body.querySelector('.dm-release-status'),list=m.body.querySelector('.dm-release-list'),search=m.body.querySelector('input');
 function render(){const term=search.value.toLocaleLowerCase('tr');list.innerHTML=[...new Set(catalog.map(f=>f.group))].map(g=>{const l=catalog.filter(f=>f.group===g&&f.name.toLocaleLowerCase('tr').includes(term));return l.length?'<h3 class="dm-feature-group">'+esc(g)+'</h3>'+l.map(f=>`<div class="dm-feature-row"><span>${esc(f.name)}${f.parent&&!enabled(f.parent)?'<small>Üst bölüm kapalı · açıldığında görünür</small>':''}</span><button class="dm-feature-toggle" data-code="${f.code}" aria-label="${esc(f.name)}" aria-pressed="${flags[f.code]!==false}">${flags[f.code]!==false?'Açık ✓':'Kapalı'}</button></div>`).join(''):'';}).join('');}
 let saving=false;async function save(changes){if(saving)return;saving=true;m.body.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='Kaydediliyor…';try{const d=await api('yayinOzellikKaydet',{degisiklikler:changes});flags=d.flags;apply();render();status.textContent='Kaydedildi. Açık uygulamalar en geç 1 dakika içinde güncellenir.';}catch(e){status.textContent=e.message;}finally{saving=false;m.body.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 search.oninput=render;list.onclick=e=>{const b=e.target.closest('[data-code]');if(b)save([{code:b.dataset.code,enabled:flags[b.dataset.code]===false}]);};m.body.querySelectorAll('[data-all]').forEach(b=>b.onclick=()=>save(catalog.map(f=>({code:f.code,enabled:b.dataset.all==='true'}))));render();
};
const gameNames={harfbahcesi:'Harf Bahçesi',kelime:'Kelime Laboratuvarı',jeopardy:'Risk Balonları',bosluk:'Eksik Harf',hafiza:'Hafıza Sandığı',yagmur:'Hız Fırtınası',asmaca:'Harf Avı',kelimebul:'Şifre Kırıcı',konusma:'Kelime Modu',eslestirme:'Eş Bul',tren:'Kelime Treni',dikte:'Kulak Dedektifi',cumle:'Cümle Ustası',ucus:'Kelime Uçuşu',rota:'Cümle Rotası'};
const n=x=>Number.isFinite(Number(x))?Number(x):0,date=x=>x?new Date(x).toLocaleDateString('tr-TR',{timeZone:'Europe/Istanbul'}):'—';
function parentText(r){
 const m=r.metrics||{},lines=['🦜 Diji-Medu Haftalık Veli Raporu',`${r.name} · ${r.class||''}. sınıf ${r.branch||''}`,`Dönem: ${date(r.weekStart)} – bugün`,'','BU HAFTA',`📅 ${r.activeDays} gün çalıştı · ${r.weekXP} XP`, `🎮 ${m.games} oyun · ${m.correct} doğru / ${m.wrong} yanlış`];
 if(n(m.correct)+n(m.wrong)>0)lines.push(`🎯 Oyun doğruluk oranı: %${Math.round(100*n(m.correct)/(n(m.correct)+n(m.wrong)))}`);
 lines.push(`⏱️ Kayıtlı oyun süresi: ${Math.round(n(m.gameSeconds)/60)} dakika`, `📚 ${m.topics} başarılı konu testi · ${m.levels} tamamlanan seviye`, `🎬 ${m.videos} video · ${m.activities} etkinlik · ${m.homework} ödev`, `📖 ${m.reading} okuma çalışması · ${m.matches} iki kişilik oyun`);
 if(r.gameDetails?.length){lines.push('','OYUN AYRINTILARI');r.gameDetails.forEach(g=>lines.push(`• ${gameNames[g.game_key]||g.game_key}: ${g.games} tur, ${g.correct||0} doğru / ${g.wrong||0} yanlış, ortalama ${g.avg_score||0}, en iyi ${g.best_score||0} puan`));}
 lines.push('','TOPLAM İLERLEME',`⭐ Toplam XP: ${r.totalXP} · Genel puan: ${r.points}`,`🔥 Güncel seri: ${r.streak} gün · 🪙 ${r.gold} altın`,`⏱️ Uygulamada kayıtlı toplam süre: ${Math.round(n(r.totalSeconds)/60)} dakika`,`🎮 ${r.totalGames} oyun · 📚 ${r.totalTopics} başarılı konu · 🗺️ ${r.totalLevels} seviye`,`📆 Tamamlanan plan haftası: ${r.planCompleted} · Son giriş: ${date(r.lastLogin)}`);
 if(r.level)lines.push(`📋 Seviye tespit: ${r.level.sonuc||r.level.seviye||'Sonuç kayıtlı'}${r.level.tarih?' ('+date(r.level.tarih)+')':''}`);
 if(r.target){lines.push(`🎯 Günlük XP hedefi: ${r.target}`);const days=Object.entries(r.dailyLog||{}).filter(([d])=>d>=r.weekStart).sort(([a],[b])=>a.localeCompare(b));if(days.length){lines.push('📅 Günlük çalışma: '+days.map(([d,x])=>`${date(d)}: ${x} XP`).join(' · '));lines.push('🎯 Hedefe ulaşılan gün: '+days.filter(([,x])=>n(x)>=n(r.target)).length);}}
 const sh=Object.values(r.conversation||{});if(sh.length)lines.push(`🦜 Papağan sohbeti: ${sh.filter(x=>n(x)>0).length} bölüm, ${sh.reduce((a,x)=>a+n(x),0)} yıldız`);
 if(r.badges?.length)lines.push('🏅 Kazanılan rozetler: '+r.badges.map(b=>(b.emoji||'🏅')+' '+b.name).join(', '));
 lines.push('','KELİME GELİŞİMİ',`🧠 Zor kelime tekrar havuzunda ustalaşılan: ${r.learnedWords}`);
 if(r.difficultWords?.length)lines.push('🔁 Tekrar önerisi: '+r.difficultWords.map(w=>`${w.en||''}${w.tr?' — '+w.tr:''} (${w.yanlis||0} yanlış)`).join('; '));else lines.push('Tekrar havuzunda zor kelime kaydı yok.');
 if(r.reports?.length){const t=r.reports[0];lines.push('','SON ÖĞRETMEN DEĞERLENDİRMESİ',`📅 ${date(t.report_date)}`,`Okuma: ${t.reading_score??'—'} · Yazma: ${t.writing_score??'—'} · Kelime: ${t.vocabulary_score??'—'}`,`Konuşma: ${t.speaking_score??'—'} · Dil bilgisi: ${t.grammar_score??'—'}`);if(t.genel_score!=null)lines.push('Genel: '+t.genel_score);if(t.exam_score!=null)lines.push('Deneme: '+t.exam_score);if(t.book_name)lines.push('📖 Kitap: '+t.book_name+(t.page_no?' · '+t.page_no+'. sayfa':''));if(t.read_count)lines.push('📚 Okuma sayısı: '+t.read_count);if(t.target)lines.push('🎯 Öğretmen hedefi: '+t.target);if(t.homework_feedback)lines.push('💬 Öğretmen geri bildirimi: '+t.homework_feedback);if(t.next_homework)lines.push('🎯 Sonraki ödev: '+t.next_homework);if(t.next_report_date)lines.push('Sonraki ders: '+date(t.next_report_date));}
 if(r.reports?.length>1){lines.push('','SON DEĞERLENDİRME TRENDİ');r.reports.forEach(t=>{const values=[t.reading_score,t.writing_score,t.vocabulary_score,t.speaking_score,t.grammar_score].filter(x=>x!=null);const avg=t.genel_score??(values.length?Math.round(values.reduce((a,x)=>a+n(x),0)/values.length*10)/10:'—');lines.push(`${date(t.report_date)}: Genel ${avg}${t.exam_score!=null?' · Deneme '+t.exam_score:''}`);});}
 if(r.levels?.length)lines.push('','SON PARKUR İLERLEMESİ',...r.levels.slice(0,8).map(l=>`• ${l.mode==='buyu'?'Büyü Parkuru':l.mode==='konusma'?'Kelime Modu':l.mode}: ${l.class_no||''}. sınıf, ${l.unit_no||''}. ünite, ${l.level_no}. seviye · ${date(l.completed_at)}`));
 if(r.topics?.length){lines.push('','SON KONU ÇALIŞMALARI');r.topics.slice(0,12).forEach(t=>lines.push(`• ${t.level||''} ${t.topic_name}: ${t.test_success?'test başarılı':'çalışma/tekrar kaydı'} · ${date(t.completed_at)}`));}
 if(r.homeworks?.length){lines.push('','ÖDEVLER');r.homeworks.forEach(h=>lines.push(`• ${h.title}: ${h.done_at?'tamamlandı':'bekliyor'}${h.score!=null?' · '+h.score+' puan':''}${h.due_date?' · son gün '+date(h.due_date):''}`));}
 if(r.reading?.length){const t=r.reading[0];lines.push('','SON OKUMA ÇALIŞMASI',`${t.text_title||'Okuma'} · ${t.words_read} kelime · ${t.wpm} kelime/dk · ${date(t.created_at)}`);}
 if(r.videos?.length)lines.push('','VİDEOLAR',...r.videos.slice(0,10).map(v=>`• ${v.title}: ${v.watched_at?'izlendi ('+date(v.watched_at)+')':'bekliyor'}`));
 if(r.activities?.length)lines.push('','ETKİNLİKLER',...r.activities.slice(0,10).map(a=>`• ${a.display_name}: ${a.status==='completed'?'tamamlandı':'bekliyor'}`));
 if(r.latestLeague){const l=r.latestLeague;lines.push('','SON TAMAMLANAN LİG HAFTASI',`${date(l.week_start)} · ${l.rank_no}. sıra · ${l.xp} XP`,l.gold||l.energy?`🎁 Kazanılan: ${l.gold} altın + ${l.energy} enerji`:'Bu hafta lig hediyesi kazanılmadı.');}
 lines.push('',r.activeDays>=4?'🌟 Düzenli çalışma alışkanlığı çok güzel ilerliyor! Kısa tekrarlarla bu ritmi sürdürelim.':r.activeDays>0?'🌱 Güzel bir başlangıç! Her gün 10 dakikalık tekrar gelişimini destekleyecektir.':'🌱 Bu hafta henüz çalışma kaydı yok. Birlikte küçük bir günlük hedefle yeniden başlayabiliriz.','Destekleriniz için teşekkür ederiz. 🌻','Not: Haftalık sayılar yalnızca bu döneme aittir. Toplam ilerleme ve son değerlendirmeler geçmiş kayıtları da içerir.');return lines.join('\n');
}
window.dmParentReportText=parentText;
window.dmVeliRaporYukle=async function(cl,area){area.innerHTML='<div class="yo-bos">Zengin rapor hazırlanıyor…</div>';try{const d=await api('haftalikVeliRaporu',{sinif:Number(cl)});if(!area.isConnected)return;area.innerHTML=d.liste.map((r,i)=>`<article class="dm-report-card"><h3>${esc(r.name)}</h3><small>${date(r.weekStart)} – bugün</small><div class="dm-report-stats"><span><b>${r.activeDays}</b>aktif gün</span><span><b>${r.weekXP}</b>haftalık XP</span><span><b>${r.metrics.games}</b>oyun</span></div><details><summary>Raporun tamamını gör</summary><pre>${esc(parentText(r))}</pre></details><div class="dm-report-actions"><button data-copy="${i}">Raporu kopyala</button>${r.phone?`<a target="_blank" rel="noopener" href="https://wa.me/${esc(('90'+r.phone.replace(/\D/g,'').slice(-10)))}?text=${encodeURIComponent(parentText(r))}">WhatsApp ile paylaş</a>`:''}<button data-mail="${i}">E-posta gönder</button></div><small class="dm-report-status" role="status"></small></article>`).join('')||'<div class="yo-bos">Bu sınıfta öğrenci bulunamadı.</div>';area.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(parentText(d.liste[Number(b.dataset.copy)]));b.textContent='Kopyalandı ✓';}catch(e){b.closest('article').querySelector('.dm-report-status').textContent='Raporu açıp metni seçerek kopyalayabilirsin.';}});area.querySelectorAll('[data-mail]').forEach(b=>b.onclick=async()=>{const r=d.liste[Number(b.dataset.mail)],status=b.closest('article').querySelector('.dm-report-status');b.disabled=true;try{const g=await api('raporMail',{ogrenci:r.name,metin:parentText(r)});status.textContent=g.mesaj||'Gönderildi.';}catch(e){status.textContent=e.message;}finally{b.disabled=false;}});}catch(e){area.innerHTML='<div class="yo-bos">'+esc(e.message)+'</div>';}};
const gold=[100,75,50,35,25,20,15,10,8,5],energy=[15,12,10,8,6,5,4,3,2,1];
const oldLeague=window.maLigHtml;if(typeof oldLeague==='function')window.maLigHtml=function(){return oldLeague.apply(this,arguments)+`<section class="dm-league-prizes"><details><summary>🎁 Şampiyonlar Ligi haftalık ödülleri</summary><p>Yalnızca haftayı ilk 10’da tamamlayan ve o hafta XP kazanan öğrenciler hediye alır. Süper ve Yerel Lig’de hediye yoktur. Her pazartesi yeni hafta başlar; sonuçlar 00.05’te kesinleşir. Kazandığın hediye ilk girişinde hesabına bir kez eklenir.</p><table><thead><tr><th>Sıra</th><th>Altın</th><th>Enerji</th></tr></thead><tbody>${gold.map((g,i)=>`<tr><td>${i+1}.</td><td>${g} 🪙</td><td>${energy[i]} ⚡</td></tr>`).join('')}</tbody></table></details></section>`;};
async function weekly(){
 if(!token()||!who()||who().toLowerCase()==='teacher'||document.hidden||weeklyBusy||$('dmWeeklyPanel')||Date.now()-lastWeekly<60000)return;
 const blocking=[...document.querySelectorAll('.rubric-modal,.game-overlay,.dm-perde')].some(e=>getComputedStyle(e).display!=='none');if(blocking)return;
 weeklyBusy=true;lastWeekly=Date.now();const owner=who();
 try{const d=await api('haftalikPerformans');if(owner!==who()||!d.rapor)return;const r=d.rapor;
 if(r.yo){if(typeof yo!=='undefined'&&yo){yo=Object.assign(yo,r.yo);localStorage.setItem('ing_yo_'+owner,JSON.stringify(yo));}window.yoSunucudanAl?.();}
 if(r.energyBalance!=null)window.headerEnerjiGoster?.(r.energyBalance,typeof genelEnerjiMax!=='undefined'?genelEnerjiMax:30);
 if(!enabled('haftalik_ozet'))return;
 const m=r.summary||{},league={sampiyon:'Şampiyonlar Ligi',super:'Süper Lig',yerel:'Yerel Lig'}[r.league],panel=document.createElement('div');panel.id='dmWeeklyPanel';panel.className='dm-weekly-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-labelledby','dmWeeklyTitle');
 const motivation=r.xp>=500?'Harika bir hafta! Bu enerjiyi yeni haftaya taşı, Papi seninle!':r.xp>0?'Her küçük adım seni ileri taşıyor. Bu hafta kendi rekorunu kırmaya var mısın?':'Yeni hafta, yeni fırsat! Bugün kısa bir oyunla başlayalım; Papi seni bekliyor.';
 panel.innerHTML=`<div class="dm-weekly-card"><img src="${r.gold?'mascot-reward.webp':'mascot-welcome.webp'}" alt="Papağan maskot"><h2 id="dmWeeklyTitle">Haftan nasıl geçti?</h2><p>${date(r.week_start)} haftası · ${esc(league)}<br><b>${r.rank_no}. sıra</b></p><div class="dm-report-stats"><span><b>${r.active_days}</b>aktif gün</span><span><b>${r.xp}</b>XP</span><span><b>${m.games||0}</b>oyun</span></div><p>${m.correct||0} doğru · ${m.topics||0} konu testi · ${m.levels||0} seviye<br>${m.activities||0} etkinlik · ${m.homework||0} ödev · ${m.videos||0} video</p>${r.gold||r.energy?`<div class="dm-weekly-prize">🎁 +${r.gold} altın · +${r.energy} enerji<br><small>Hediyen hesabına eklendi!</small></div>`:'<p>Bu hafta lig hediyesi kazanmadın. Yeni haftada şansını yeniden dene! 🌱</p>'}<p>${motivation}</p><button>Yeni haftaya hazırım! 🦜</button></div>`;document.body.append(panel);const button=panel.querySelector('button'),prev=document.activeElement;button.focus();button.onclick=()=>{panel.remove();prev?.focus?.();api('haftalikPerformansGoruldu',{hafta:r.week_start}).catch(()=>{});};panel.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();button.focus();}if(e.key==='Escape')button.click();});
 }catch(e){}finally{weeklyBusy=false;}
}
// Block direct tab/function entry as well as hiding buttons; existing user records remain intact.
document.addEventListener('click',e=>{if(admin)return;const b=e.target.closest('[data-s],[data-ekran],[data-mode],[data-social]');if(!b)return;const code=b.dataset.s==='lig'?'lig':b.dataset.s==='kesfet'?'kesfet':b.dataset.s==='vitrin'?'vitrin':b.dataset.s==='akis'?'akis':navCodes[b.dataset.ekran];if(code&&!enabled(code)){e.preventDefault();e.stopImmediatePropagation();unavailable();}},true);
let queue;new MutationObserver(()=>{clearTimeout(queue);queue=setTimeout(apply,150);}).observe(document.body,{childList:true,subtree:true});
setInterval(()=>{if(weeklyAccount!==who()){weeklyAccount=who();lastWeekly=0;admin=false;refresh();}apply();weekly();},15000);
setInterval(refresh,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refresh();weekly();}});refresh();setTimeout(weekly,10000);
})();
