/* Papi'nin Kelime Çarkı: server-authoritative turns; isolated scores, no rewards. */
(()=>{'use strict';
 const POINTS=[50,100,150,200,250,300,400,500,600,750,900,1000],COLORS=['#5ead85','#f0c55b','#e88362','#9b80b7','#579eac','#9ac87d','#eab07a','#83bcb7','#dca6bd','#c7ce70','#e5ad52','#7badd1'];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let root,state=null,busy=false,origin,angle=0,epoch=0,setupGrade='',setupUnit='',setupMode=1,names=['',''],audio=null,soundTimer=null,soundOn=true,extraWords=[];
 const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}},remove(k){try{localStorage.removeItem(k);}catch{}}};

 function stopSound(){if(soundTimer!==null){clearTimeout(soundTimer);soundTimer=null;}}
 function unlockSound(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;if(!audio)audio=new Audio();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
 function spinSound(duration){stopSound();if(!soundOn||!audio||!duration)return;const started=Date.now();function tick(){if(!root||!soundOn||Date.now()-started>=duration){stopSound();return;}try{const osc=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;osc.type='triangle';osc.frequency.setValueAtTime(950,now);osc.frequency.exponentialRampToValueAtTime(180,now+.035);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.08,now+.003);gain.gain.exponentialRampToValueAtTime(.0001,now+.045);osc.connect(gain);gain.connect(audio.destination);osc.start(now);osc.stop(now+.05);}catch{}soundTimer=setTimeout(tick,35+125*(Date.now()-started)/duration);}tick();}

 function body(){return root?.querySelector('.ww-body');}
 function close(){stopSound();epoch++;root?.remove();root=null;document.body.classList.remove('ww-active');origin?.focus();}
 function frame(){origin=document.activeElement;root=document.createElement('section');root.id='wordWheel';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-labelledby','wwTitle');root.innerHTML='<div class="ww-shell"><header><div><small>Diji-Medu</small><h1 id="wwTitle">Papi’nin Kelime Çarkı</h1></div><img class="ww-header-papi" src="papi-welcome-v2.png" alt=""><button class="ww-close" aria-label="Kapat">✕</button></header><main class="ww-body"></main><p class="ww-notice" role="status"></p></div>';root.querySelector('.ww-close').onclick=()=>state&&!state.finished?finish():close();document.body.append(root);document.body.classList.add('ww-active');root.querySelector('.ww-close').focus();}
 function notice(s){if(root)root.querySelector('.ww-notice').textContent=s;}
 async function request(payload){if(typeof apiURL==='undefined')throw Error('Uygulama bağlantısı bulunamadı.');const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),15000);try{const r=await fetch(apiURL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:ctrl.signal});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.mesaj||'İşlem tamamlanamadı.');return d;}catch(e){throw Error(e.name==='AbortError'?'Bağlantı gecikti. Tekrar dene.':e.message);}finally{clearTimeout(t);}}
 async function work(action){if(busy)return;busy=true;const ticket=epoch;root?.querySelectorAll('button').forEach(b=>b.disabled=true);notice('');try{await action();}catch(e){if(ticket===epoch)notice(e.message);}finally{if(ticket===epoch){busy=false;root?.querySelectorAll('button').forEach(b=>b.disabled=false);}}}
 async function open(){if(root)return;epoch++;state=null;busy=false;frame();body().innerHTML='<p>Kelime havuzu hazırlanıyor…</p>';await work(async()=>{if(!(window.masterKelimeHavuzu||[]).length&&typeof window.dijiKelimeHavuzunuYukle==='function')await window.dijiKelimeHavuzunuYukle();extraWords=(await import('./word-wheel-vocabulary.js?v=1')).WHEEL_VOCABULARY;setup();});if(body()?.textContent==='Kelime havuzu hazırlanıyor…'){body().innerHTML='<button class="ww-main">Tekrar dene</button>';body().querySelector('button').onclick=()=>{close();open();};}}
 function setup(){state=null;const pool=[...(window.masterKelimeHavuzu||[]),...extraWords],grades=[...new Set(pool.map(w=>Number(w.sinif)).filter(n=>n>0&&n<=12))].sort((a,b)=>a-b);setupGrade=grades.includes(Number(setupGrade))?setupGrade:String(grades[0]||'');body().innerHTML='<img class="ww-papi" src="papi-welcome-v2.png" alt="Papi"><p>Sınıfını, üniteni ve oyuncu sayısını seç.</p><form class="ww-setup"><div class="ww-mode"><button type="button" data-mode="1">1 Kişilik</button><button type="button" data-mode="2">2 Kişilik</button></div><label>Sınıf<select id="wwGrade">'+grades.map(g=>'<option value="'+g+'" '+(String(g)===setupGrade?'selected':'')+'>'+g+'. Sınıf</option>').join('')+'</select></label><label>Ünite<select id="wwUnit"></select></label><label>1. oyuncunun ismi (isteğe bağlı)<input id="wwName1" maxlength="40" placeholder="İstediğin ismi yaz"></label><label class="ww-name2">2. oyuncunun ismi (isteğe bağlı)<input id="wwName2" maxlength="40" placeholder="İstediğin ismi yaz"></label><p class="ww-deck-count"></p><button class="ww-main" type="submit">Oyunu başlat</button><button class="ww-resume" type="button" hidden>Kaldığım oyuna dön</button></form><p class="ww-note">Doğru cevapta çarkın puanı eklenir, yanlışta düşülür. Altın, XP veya hediye verilmez.</p>';
 const b=body(),g=b.querySelector('#wwGrade'),u=b.querySelector('#wwUnit');b.querySelector('#wwName1').value=names[0];b.querySelector('#wwName2').value=names[1];function count(){setupUnit=u.value;const rows=pool.filter(w=>Number(w.sinif)===Number(g.value)&&Number(w.unite)===Number(u.value)&&w.ingilizce&&w.turkce),n=new Set(rows.map(w=>String(w.ingilizce).trim().toLocaleLowerCase('en'))).size;b.querySelector('.ww-deck-count').textContent=n?n+' kelime · Ünitenin tamamı':'Bu ünitede kelime yok.';b.querySelector('.ww-main').disabled=!n;}function units(){setupGrade=g.value;const all=[...new Set(pool.filter(w=>Number(w.sinif)===Number(g.value)).map(w=>Number(w.unite)).filter(n=>n>0))].sort((a,b)=>a-b);setupUnit=all.includes(Number(setupUnit))?setupUnit:String(all[0]||'');u.innerHTML=all.map(n=>'<option value="'+n+'" '+(String(n)===setupUnit?'selected':'')+'>'+n+'. Ünite</option>').join('');count();}function mode(){b.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('selected',Number(x.dataset.mode)===setupMode));b.querySelector('.ww-name2').hidden=setupMode===1;}b.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{setupMode=Number(x.dataset.mode);mode();});g.onchange=units;u.onchange=count;mode();units();b.querySelector('form').onsubmit=e=>{e.preventDefault();names=[b.querySelector('#wwName1').value.trim(),b.querySelector('#wwName2').value.trim()];work(async()=>{const previousFirst=storage.get('dm_wheel_first:'+setupGrade+':'+setupUnit)||'';state=await request({islem:'kelimeCarkiBaslat',sinif:Number(setupGrade),unite:Number(setupUnit),mode:setupMode,names,previousFirst});storage.set('dm_wheel_active',state.runId);angle=0;draw();});};const resume=b.querySelector('.ww-resume');resume.hidden=!storage.get('dm_wheel_active');resume.onclick=()=>work(async()=>{state=await request({islem:'kelimeCarkiDurum',runId:storage.get('dm_wheel_active')});draw();});}
 function wheel(){const points=state?.wheelPoints||POINTS,radius=100,c=110;const step=360/points.length;let paths='',labels='';for(let i=0;i<points.length;i++){const a=(i*step-step/2-90)*Math.PI/180,z=(i*step+step/2-90)*Math.PI/180,m=(i*step-90)*Math.PI/180;paths+='<path d="M110 110 L'+(c+radius*Math.cos(a))+' '+(c+radius*Math.sin(a))+' A100 100 0 0 1 '+(c+radius*Math.cos(z))+' '+(c+radius*Math.sin(z))+' Z" fill="'+COLORS[i]+'" stroke="#f8e4b8" stroke-width="2"/>';labels+='<text x="'+(c+70*Math.cos(m))+'" y="'+(c+70*Math.sin(m)+5)+'" text-anchor="middle">'+points[i]+'</text>';}return '<div class="ww-wheel-box"><div class="ww-pointer" aria-hidden="true">▼</div><svg class="ww-wheel" viewBox="0 0 220 220" role="img" aria-label="Puan çarkı" style="transform:rotate('+angle+'deg)"><circle cx="110" cy="110" r="108" fill="#b78844"/>'+paths+labels+'<circle cx="110" cy="110" r="17" fill="#c08b41" stroke="#f5db9d" stroke-width="5"/></svg></div>';}
 function draw(){if(!root||!state)return;if(state.finished){result();return;}const p=state.pending,b=body();if(p){const target=(360-p.slot*(360/(state.wheelPoints||POINTS).length))%360;angle+=(target-angle%360+360)%360;}b.innerHTML='<div class="ww-scope">'+state.mode+' Kişilik · '+state.sinif+'. Sınıf · '+state.unite+'. Ünite</div><div class="ww-players">'+state.players.map((x,i)=>'<div class="ww-player '+(i===state.turn?'turn':'')+'"><span>'+esc(x.name)+'</span><b>'+x.score+'</b></div>').join('')+'</div><div class="ww-turn">Sıra: '+esc(state.players[state.turn].name)+' · '+state.index+' / '+state.total+' soru</div>'+wheel()+(p?'<div class="ww-value">Çark: '+p.points+' puan</div><section class="ww-question"><h2>“'+esc(p.word)+'” ne demek?</h2>'+(p.options.length>1?'<div class="ww-answers">'+p.options.map((x,i)=>'<button data-answer="'+i+'">'+esc(x)+'</button>').join('')+'</div>':'<form class="ww-typed"><input aria-label="Türkçesini yaz" placeholder="Türkçesini yaz" maxlength="500" required><button class="ww-main">Cevapla</button></form>')+'<p class="ww-rule">+'+p.points+' doğru · −'+p.points+' yanlış</p></section>':'<div class="ww-feedback" aria-live="polite">'+(state.last?(state.last.correct?'✅':'❌')+' '+(state.last.delta>0?'+':'')+state.last.delta+' puan · '+esc(state.last.word)+': '+esc(state.last.answer):'Önce çarkı çevir, ardından soruyu cevapla.')+'</div><button class="ww-main ww-spin">Çarkı çevir</button>')+'<button class="ww-sound" type="button" aria-pressed="'+soundOn+'">'+(soundOn?'🔊 Ses açık':'🔇 Ses kapalı')+'</button><button class="ww-end">Oyunu sonlandır</button><p class="ww-note">Mevcut puanlar geçerli olur. Altın, XP veya hediye verilmez.</p>';b.querySelector('.ww-spin')?.addEventListener('click',spin);b.querySelector('.ww-end').onclick=finish;b.querySelector('.ww-sound').onclick=()=>{soundOn=!soundOn;if(!soundOn)stopSound();else unlockSound();const button=b.querySelector('.ww-sound');button.textContent=soundOn?'🔊 Ses açık':'🔇 Ses kapalı';button.setAttribute('aria-pressed',String(soundOn));};b.querySelectorAll('[data-answer]').forEach(x=>x.onclick=()=>answer(p.options[Number(x.dataset.answer)]));b.querySelector('.ww-typed')?.addEventListener('submit',e=>{e.preventDefault();answer(b.querySelector('.ww-typed input').value);});}
 function spin(){if(busy)return;unlockSound();work(async()=>{state=await request({islem:'kelimeCarkiCevir',runId:state.runId});if(state.finished){draw();return;}const slot=state.pending.slot,target=(360-slot*(360/(state.wheelPoints||POINTS).length))%360;angle+=1080+((target-angle%360+360)%360);const el=root?.querySelector('.ww-wheel');if(el)el.style.transform='rotate('+angle+'deg)';const duration=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?0:1250;spinSound(duration);await new Promise(resolve=>setTimeout(resolve,duration));stopSound();if(state.index===0)storage.set('dm_wheel_first:'+state.sinif+':'+state.unite,state.pending.word);draw();});}
 function answer(value){work(async()=>{state=await request({islem:'kelimeCarkiCevap',runId:state.runId,round:state.pending.round,answer:value});draw();});}
 function finish(){if(!state||state.finished){close();return;}work(async()=>{state=await request({islem:'kelimeCarkiBitir',runId:state.runId});draw();});}
 function result(){storage.remove('dm_wheel_active');const b=body();b.innerHTML='<img class="ww-papi" src="papi-welcome-v2.png" alt="Papi"><h2>Oyun tamamlandı!</h2><p class="ww-note">'+state.index+' / '+state.total+' soru cevaplandı. Son puanlar kaydedildi.</p><div class="ww-results">'+state.players.map(p=>'<article><h3>'+esc(p.name)+'</h3><strong>'+p.score+' puan</strong><p>'+p.correct+' doğru · '+p.wrong+' yanlış</p></article>').join('')+'</div>'+(state.last?'<p>'+ (state.last.correct?'✅':'❌')+' Son cevap: '+esc(state.last.word)+' · '+esc(state.last.answer)+' ('+(state.last.delta>0?'+':'')+state.last.delta+')</p>':'')+'<p class="ww-note">Altın, XP veya hediye verilmez.</p><div class="ww-ranking" aria-live="polite">Sıralama yükleniyor…</div><button class="ww-main ww-new">Yeni oyun</button><button class="ww-exit">Kapat</button>';b.querySelector('.ww-new').onclick=setup;b.querySelector('.ww-exit').onclick=close;ranking(state,b.querySelector('.ww-ranking'));}
 async function ranking(s,el){try{const d=await request({islem:'kelimeCarkiSiralama',sinif:s.sinif,unite:s.unite,mode:s.mode});el.innerHTML='<h3>'+s.mode+' kişilik · Ünite sıralaması</h3><ol>'+d.liste.map(x=>'<li><span>'+esc(x.isim)+'</span><b>'+x.puan+' puan</b></li>').join('')+'</ol>';if(!d.liste.length)el.innerHTML+='<p>Henüz sonuç yok.</p>';}catch(e){el.textContent='Sıralama yüklenemedi.';const b=document.createElement('button');b.textContent='Tekrar dene';b.onclick=()=>ranking(s,el);el.append(b);}}
 function mount(){const grid=document.querySelector('#tab-aktiviteler .az-grid2x2');if(!grid||grid.querySelector('#wordWheelActivity'))return;const b=document.createElement('button');b.id='wordWheelActivity';b.className='az-gcard dm-toy-card';b.type='button';b.dataset.dmParty='free';b.style.setProperty('--toy-bg','#f6e4ba');b.style.setProperty('--toy-edge','#cda85d');b.innerHTML='<div class="az-gcard-icon">🎡</div><div class="az-gcard-title">Papi’nin Kelime Çarkı</div><div class="ak-acik">Çevir, cevapla, puanını kazan</div><div class="ak-etiket">1 veya 2 kişilik · Ödülsüz</div>';b.onclick=()=>{setupMode=grid.closest('[data-dm-party]')?.dataset.dmParty==='duo'?2:1;open();};grid.append(b);}
 document.addEventListener('keydown',e=>{if(!root)return;if(e.key==='Escape'){e.preventDefault();state&&!state.finished?finish():close();}if(e.key==='Tab'){const items=[...root.querySelectorAll('button:not(:disabled),input,select')].filter(x=>x.getClientRects().length),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});window.dmWordWheel={open,close};mount();const host=document.getElementById('tab-aktiviteler');if(host)new MutationObserver(mount).observe(host,{childList:true,subtree:true});
})();
