import json
from pathlib import Path
# Original authored story and a shared deterministic activity deck for client/server.
rows = [
('Papi ile Tanış','A1','Bahçenin kapısında renkli bir papağan seni bekliyor. Papi konuştuğunda kapıdaki ilk yaprak ışıldıyor. İlk görevin ona selam vermek.','Hello ve Hi selam vermek için, Goodbye ayrılırken kullanılır. I’m, I am ifadesinin kısa biçimidir.','Hello!','Merhaba!','Hi! I am Papi.','Selam! Ben Papi.','Goodbye!','Hoşça kal!','Thank you!','Teşekkür ederim!'),
('İsim Yaprağı','A1','Papi, bahçenin seni tanıması için isim yaprağını buluyor. Yaprağa adını söyleyerek ilk izini bırakacaksın.','My name is… ifadesinden sonra adını söyle. What is your name? birinin adını sorar.','My name is Papi.','Benim adım Papi.','What is your name?','Senin adın ne?','Nice to meet you.','Tanıştığımıza memnun oldum.','I am hungry.','Ben açım.'),
('Sayı Köprüsü','A1','Köprüde üç taş eksik. Papi ile taşları sayıp köprüyü tamamlayacaksın.','One bir, two iki, three üç demektir. I am… years old yaşını söyler.','One, two, three.','Bir, iki, üç.','I am ten years old.','Ben on yaşındayım.','How old are you?','Kaç yaşındasın?','I am from Turkey.','Ben Türkiye’denim.'),
('Harf Feneri','A1','Gece olmadan fenerin üzerine Papi’nin adını yazmalısın. Harfleri tek tek söylemek kayıp yazıyı geri getiriyor.','İngilizce harf adları kelimelerin okunuşuyla aynı değildir. Papi: P /piː/, A /eɪ/, P /piː/, I /aɪ/. Spell, harf harf söyle demektir.','My name is Papi.','Benim adım Papi.','Please spell your name.','Lütfen adını harf harf söyle.','Thank you.','Teşekkür ederim.','Good night.','İyi geceler.'),
('Renkli Yapraklar','A1','Bahçenin yaprakları renklerini kaybetmiş. Papi doğru renkleri söylediğinde yapraklar yeniden canlanıyor.','Red kırmızı, blue mavi, green yeşil demektir. İngilizcede renk genellikle nesneden önce gelir: a green leaf.','This is a green leaf.','Bu yeşil bir yaprak.','The sky is blue.','Gökyüzü mavi.','I have a red flower.','Benim kırmızı bir çiçeğim var.','The leaf is yellow.','Yaprak sarı.'),
('Çantadaki Sır','A1','Papi’nin çantasında bir harita, kitap ve anahtar var. Bir nesneyi seçip tanıtarak patikanın yönünü bulacaksın.','A ve an tek bir nesneden söz eder. Sesli bir sesle başlayan sözcükten önce an kullanılır: an apple. This is… yakındaki bir şeyi tanıtır.','This is a book.','Bu bir kitap.','It is an apple.','O bir elma.','I have a key.','Benim bir anahtarım var.','This is a river.','Bu bir nehir.'),
('Papi’nin Ailesi','A1','Aile ağacındaki üç fotoğrafı Papi ile yerlerine as. Her fotoğrafta birini tanıtmayı öğreneceksin.','I am, you are, he/she/it is kullanılır. He erkek, she kadın veya kız, it nesne ya da hayvan için kullanılabilir.','She is my sister.','O benim kız kardeşim.','He is my brother.','O benim erkek kardeşim.','We are a family.','Biz bir aileyiz.','She is my teacher.','O benim öğretmenim.'),
('Bahçe Evi','A1','Papi küçük bahçe evinin kapısını açıyor. Anahtarı bulmak için nesnelerin nerede olduğunu söylemelisin.','In içinde, on üstünde, under altında demektir. There is tek, there are birden fazla şeyin varlığını söyler.','The key is under the table.','Anahtar masanın altında.','There is a book on the chair.','Sandalyenin üstünde bir kitap var.','There are two flowers.','İki çiçek var.','The key is in the bag.','Anahtar çantanın içinde.'),
('Güneşli Sabah','A1','Bahçeyi uyandırma zamanı. Papi ile sabah yaptıklarını anlatıp çiçekleri sula.','Günlük alışkanlıklarda geniş zaman kullanılır. I/you/we/they ile fiilin temel biçimi; he/she/it ile çoğu fiile -s eklenir.','I get up at seven.','Ben saat yedide kalkarım.','Papi likes apples.','Papi elmaları sever.','I can help you.','Sana yardım edebilirim.','I go to bed at nine.','Ben saat dokuzda yatarım.'),
('İlk Bahçe Şenliği','A1','Bahçedeki ilk şenliği hazırlıyorsunuz. Selam ver, kendini tanıt ve bir arkadaşına yiyecek teklif et. İlk dünya burada tamamlanıyor.','I like… sevdiğin şeyleri, I would like… nazikçe istediğin bir şeyi söyler. Can I have…? bir şey isterken kullanılır.','I would like some water.','Biraz su istiyorum.','Can I have an apple, please?','Bir elma alabilir miyim, lütfen?','Welcome to our garden!','Bahçemize hoş geldin!','I do not like apples.','Ben elmaları sevmem.'),
('Kuzeye Yolculuk','A2','Şenlikte gelen bir mektup kuzeydeki bahçenin yardım istediğini söylüyor. Papi ile yolculuk çantanı hazırlıyorsun.','Be going to planlanmış niyetleri anlatır: am/is/are going to + fiil.','We are going to visit the north.','Kuzeyi ziyaret edeceğiz.','I am going to pack my bag.','Çantamı hazırlayacağım.','Are you going to come with us?','Bizimle gelecek misin?','We visited the north.','Kuzeyi ziyaret ettik.'),
('Yoldaki İşaretler','A2','Karlı patikada iki yön tabelası var. Papi ile yol sorup kulübeyi bulacaksın.','Turn left sola dön, go straight düz git demektir. Could you…? nazik bir istektir.','Go straight and turn left.','Düz git ve sola dön.','The station is next to the shop.','İstasyon dükkânın yanında.','Could you help me, please?','Bana yardım edebilir misiniz, lütfen?','Turn right at the bridge.','Köprüde sağa dön.'),
('Karlı Pazar','A2','Pazarda sıcak eldiven ve yol için yiyecek alıyorsunuz. Satıcıya miktar ve fiyat sor.','How much sayılamayan miktar veya fiyat; how many sayılabilen nesne sayısı için kullanılır.','How much is this scarf?','Bu atkı ne kadar?','How many apples do we need?','Kaç elmaya ihtiyacımız var?','We need some bread.','Biraz ekmeğe ihtiyacımız var.','We do not need any bread.','Hiç ekmeğe ihtiyacımız yok.'),
('Dün Ne Oldu?','A2','Kulübeye vardığınızda Papi dün kaybolan fenerin hikâyesini anlatıyor. Geçmişte olanları sıralayın.','Geçmiş zamanda düzenli fiiller -ed alır; go → went gibi düzensiz fiiller de vardır. Did ile soruda temel fiil kullanılır.','We walked to the bridge yesterday.','Dün köprüye yürüdük.','Papi went to the market.','Papi pazara gitti.','Did you see the lantern?','Feneri gördün mü?','We walk to the bridge every day.','Her gün köprüye yürürüz.'),
('Fırtına Başlarken','A2','Feneri ararken kar fırtınası başlıyor. O sırada kimin ne yaptığını anlatarak izleri birleştir.','Was/were + fiil-ing geçmişte sürmekte olan eylemi anlatır. When ile araya giren kısa olay eklenebilir.','I was reading when Papi arrived.','Papi geldiğinde kitap okuyordum.','They were walking in the snow.','Onlar karda yürüyorlardı.','It started to snow.','Kar yağmaya başladı.','It snows in winter.','Kışın kar yağar.'),
('Sıcak Kulübe','A2','Üşüyen bir arkadaş kulübeye geliyor. Ona tavsiye verip bahçenin güvenlik kurallarını anlat.','Should tavsiye, must güçlü gereklilik, must not yasak belirtir. Ardından fiilin temel biçimi gelir.','You should drink warm water.','Ilık su içmelisin.','We must stay together.','Birlikte kalmalıyız.','You must not walk on the ice.','Buzun üzerinde yürümemelisin.','You can walk on the ice.','Buzun üzerinde yürüyebilirsin.'),
('İki Patika','A2','Fenerin izleri iki yola ayrılıyor. Daha güvenli yolu karşılaştırarak seç.','Kısa sıfatlarda çoğunlukla -er/-est; uzun sıfatlarda more/most kullanılır. Good → better → best.','This path is shorter than that one.','Bu patika ötekinden daha kısa.','The forest is more beautiful in spring.','Orman ilkbaharda daha güzel.','This is the safest bridge.','Bu en güvenli köprü.','That path is longer than this one.','O patika bundan daha uzun.'),
('Kayıp Fener Bulundu','A2','Fener bulundu fakat daha önce kimse bu mağaraya girmemiş. Deneyimlerinizi paylaşın.','Have/has + fiilin üçüncü biçimi geçmiş deneyimi anlatabilir. Kesin geçmiş zaman söylediğinde past simple kullanılır.','I have never seen this cave before.','Bu mağarayı daha önce hiç görmedim.','Papi has found the lantern.','Papi feneri buldu.','Have you ever visited a cave?','Hiç bir mağarayı ziyaret ettin mi?','I saw this cave yesterday.','Bu mağarayı dün gördüm.'),
('Kuzeyden Mektup','A2','Kuzey bahçesi yeniden aydınlandı. Evdekilere yaptıklarınızı anlatan kısa bir mesaj gönder.','Because neden, so sonuç, but karşıtlık belirtir. Bir mesajda başlangıç, haber ve kapanış bulunabilir.','We stayed inside because it was cold.','Hava soğuk olduğu için içeride kaldık.','We found the lantern, so everyone was happy.','Feneri bulduk, bu yüzden herkes mutluydu.','See you soon!','Yakında görüşürüz!','We stayed outside because it was warm.','Hava sıcak olduğu için dışarıda kaldık.'),
('Dönüş Planı','A2','Yola çıkmadan hava durumunu kontrol edin. Yolculuk planını ve olası bir değişikliği anlatın.','If + geniş zaman, will + temel fiil gerçekçi bir gelecek koşulunu anlatır.','If it snows, we will stay here.','Kar yağarsa burada kalacağız.','We will leave tomorrow morning.','Yarın sabah ayrılacağız.','I think the weather will be better.','Havanın daha iyi olacağını düşünüyorum.','We left yesterday morning.','Dün sabah ayrıldık.'),
('Kristal Şehrin Sırrı','B1','Eve dönerken kristal şehirden bir mesaj geliyor: şehrin nehri kararmış. Papi ile araştırmaya başlıyorsunuz.','Present perfect geçmişten şimdiye bağlı durumlarda, past simple bitmiş ve zamanı belirli olaylarda kullanılır.','The river has changed since our last visit.','Nehir son ziyaretimizden beri değişti.','We noticed the problem yesterday.','Sorunu dün fark ettik.','We have lived here for three years.','Üç yıldır burada yaşıyoruz.','We lived here three years ago.','Üç yıl önce burada yaşıyorduk.'),
('Kütüphanedeki İpucu','B1','Uçan kütüphanede şehrin eski planını arayın. Kitabı ve onu bilen kişiyi tarif edin.','Who kişiler, which nesneler için ilgi cümlesi başlatabilir. Tanımlayıcı cümlelerde that de kullanılabilir.','This is the book that explains the river.','Nehri açıklayan kitap bu.','The person who owns the shop can help us.','Dükkânın sahibi olan kişi bize yardım edebilir.','I found a map which shows the old bridge.','Eski köprüyü gösteren bir harita buldum.','This book does not explain the river.','Bu kitap nehri açıklamıyor.'),
('Eski Köprü','B1','Eski köprünün kim tarafından yapıldığını ve nasıl onarıldığını öğrenin.','Edilgen yapıda be + fiilin üçüncü biçimi kullanılır. Eylemi yapan bilinmiyorsa ya da önemli değilse işe yarar.','The bridge was built a hundred years ago.','Köprü yüz yıl önce inşa edildi.','The water is tested every week.','Su her hafta test edilir.','The gate has been repaired.','Kapı onarıldı.','They will build a new bridge.','Yeni bir köprü inşa edecekler.'),
('Baykuşun Sözü','B1','Bilge baykuş dün gördüklerini anlatıyor. Söylediklerini diğer arkadaşlarına aktar.','Geçmiş zamanda aktarılan sözlerde zaman çoğu kez geriye kayar: is → was, will → would. Say ve tell kullanımına dikkat et.','The owl said that the water was clean.','Baykuş suyun temiz olduğunu söyledi.','Papi told me that he would help.','Papi bana yardım edeceğini söyledi.','She asked where the bridge was.','Köprünün nerede olduğunu sordu.','The owl said that the water was dirty.','Baykuş suyun kirli olduğunu söyledi.'),
('Birlikte Çözüm','B1','Nehri kurtarmak için herkesin fikrini dinleyin. Öneri sunup nazikçe karşılık verin.','Why don’t we…? ve How about + fiil-ing öneri sunar. Let’s + temel fiil ortak eylem önerir.','Why don’t we test the water first?','Neden önce suyu test etmiyoruz?','How about asking the gardener?','Bahçıvana sormaya ne dersin?','That sounds like a good idea.','Bu iyi bir fikir gibi görünüyor.','I do not think that will work.','Bunun işe yarayacağını düşünmüyorum.'),
('Hayal Edilen Şehir','B1','Papi herkesin temiz bir nehirle nasıl yaşayacağını hayal ediyor. Varsayımsal fikirlerini anlat.','If + geçmiş zaman, would + temel fiil şimdi veya gelecekle ilgili hayali koşul anlatır. If I were… yaygın bir biçimdir.','If I were the mayor, I would protect the river.','Belediye başkanı olsaydım nehri korurdum.','We would build a garden if we had more space.','Daha fazla alanımız olsaydı bir bahçe yapardık.','What would you do?','Sen ne yapardın?','We will build a garden tomorrow.','Yarın bir bahçe yapacağız.'),
('İpuçlarını Tart','B1','Topladığınız izlere bakıp kesin bildiklerinizi tahminlerden ayırın.','Must güçlü çıkarım, might olasılık, can’t güçlü olumsuz çıkarım anlatabilir. Bu kullanımlar bağlama bağlıdır.','The gardener might know the answer.','Bahçıvan cevabı biliyor olabilir.','This must be the missing key.','Bu kayıp anahtar olmalı.','It cannot be the same bridge.','Bu aynı köprü olamaz.','The gardener knows the answer.','Bahçıvan cevabı biliyor.'),
('Bahçenin Eski Günleri','B1','Şehirde eskiden yaşayan bir arkadaş değişen alışkanlıkları anlatıyor.','Used to + temel fiil artık sürmeyen geçmiş alışkanlığı veya durumu anlatır. Be used to farklıdır: alışkın olmak.','We used to swim in this river.','Eskiden bu nehirde yüzerdik.','Papi is used to travelling.','Papi seyahat etmeye alışkın.','The city used to be quieter.','Şehir eskiden daha sakindi.','We swim in this river every day.','Her gün bu nehirde yüzeriz.'),
('Şehre Mesaj','B1','Araştırmanızın sonucunu şehre anlatan kısa bir rapor yazın. Bulguyu, nedeni ve öneriyi sıraya koyun.','First, however, therefore ve finally bir metindeki düşünceleri bağlar. İddia ile onu destekleyen örneği ayır.','The river is polluted; therefore, we need to act.','Nehir kirlenmiş; bu nedenle harekete geçmeliyiz.','However, the bridge is still safe.','Ancak köprü hâlâ güvenli.','In my opinion, we should start today.','Bence bugün başlamalıyız.','The river is clean, so no action is needed.','Nehir temiz, bu yüzden bir şey yapmaya gerek yok.'),
('Kristal Şehir Meclisi','B1','Mecliste çözümünü sun. Bir görüş bildir, nedenini açıkla ve arkadaşının sorusuna cevap ver.','Bir görüşü because ile gerekçelendir; örnek ekle. Karşı görüşe katılmasan bile nazikçe cevap verebilirsin.','I agree because clean water is essential.','Katılıyorum çünkü temiz su çok önemli.','I understand your point, but I have a concern.','Ne demek istediğini anlıyorum ama bir kaygım var.','Could you explain your suggestion?','Önerini açıklayabilir misin?','I agree without any concerns.','Hiçbir kaygım olmadan katılıyorum.'),
('Orman Konseyi','B2','Kristal şehrin çözümü başka bahçelere örnek oluyor. Orman konseyi seni ve Papi’yi farklı önerileri değerlendirmeye çağırıyor.','Although ve even though karşıtlığı yan cümleyle; despite ve in spite of isim veya fiil-ing ile anlatır.','Although the plan is expensive, it could help everyone.','Plan pahalı olsa da herkese yardımcı olabilir.','Despite the cost, the project is worthwhile.','Maliyetine rağmen proje yapılmaya değer.','On the other hand, we must consider the risks.','Öte yandan riskleri göz önünde bulundurmalıyız.','The plan is cheap and has no risks.','Plan ucuz ve risksiz.'),
('Kaçırılan Fırsat','B2','Eski bir kararın neyi değiştirebileceğini konuşun. Papi geçmişten ders çıkarmak istiyor.','If + had + üçüncü biçim, would have + üçüncü biçim gerçekleşmemiş geçmiş koşulu anlatır.','If we had acted sooner, we would have saved the trees.','Daha erken harekete geçseydik ağaçları kurtarırdık.','We could have asked for help.','Yardım isteyebilirdik.','If I had known, I would have called you.','Bilseydim seni arardım.','We will ask for help tomorrow.','Yarın yardım isteyeceğiz.'),
('Bugünü Değiştiren Dün','B2','Geçmişteki bir seçim bugün konseyi etkiliyor. Sebep ile bugünkü sonucu ilişkilendir.','Karma koşul geçmiş koşul ile şimdiki sonucu bağlayabilir: if + had + üçüncü biçim, would + temel fiil.','If we had planted more trees, the garden would be cooler now.','Daha fazla ağaç dikmiş olsaydık bahçe şimdi daha serin olurdu.','I wish we had listened to the gardener.','Keşke bahçıvanı dinleseydik.','I wish the river were cleaner.','Keşke nehir daha temiz olsaydı.','The garden was cooler yesterday.','Bahçe dün daha serindi.'),
('Kanıt mı Tahmin mi?','B2','Eski kayıtlarda boşluklar var. Geçmiş hakkında çıkarım yaparken kesinlik dereceni belirt.','Must have güçlü geçmiş çıkarımı, might have olasılığı, can’t have güçlü olumsuz çıkarımı belirtir.','The storm might have damaged the bridge.','Fırtına köprüye zarar vermiş olabilir.','They must have taken another route.','Başka bir yoldan gitmiş olmalılar.','Papi cannot have forgotten the map.','Papi haritayı unutmuş olamaz.','The storm definitely damaged the bridge.','Fırtına köprüye kesinlikle zarar verdi.'),
('Dolaylı ve Nazik','B2','Konseye gelen bir ziyaretçinin sorularını nazik ve açık biçimde yanıtla.','Dolaylı sorularda soru bölümünde düz cümle sırası kullanılır: Could you tell me where it is?','Could you tell me where the meeting is?','Toplantının nerede olduğunu söyleyebilir misiniz?','I was wondering whether you could help us.','Bize yardım edip edemeyeceğinizi merak ediyordum.','Would you mind opening the window?','Pencereyi açmanızın sakıncası var mı?','Where is the meeting?','Toplantı nerede?'),
('Görüşün Dayanağı','B2','İki plan için verilen kanıtları incele. İddiayı gerekçeyle destekleyip sınırlılıkları belirt.','Appears to ve is likely to kesin olmayan değerlendirmeler sunar. Bir iddiaya kanıt, örnek ve sınırlılık ekle.','The evidence suggests that the new plan is more effective.','Kanıtlar yeni planın daha etkili olduğunu gösteriyor.','This approach is likely to reduce waste.','Bu yaklaşımın atığı azaltması muhtemel.','However, further research is needed.','Ancak daha fazla araştırmaya ihtiyaç var.','The plan is certainly perfect.','Plan kesinlikle kusursuz.'),
('İki Metin Bir Karar','B2','Konseyin iki mektubunu karşılaştır. Ortak görüşü ve ayrıldıkları noktayı özetle.','Whereas karşılaştırma, both ortaklık belirtir. Özetlerken ana fikri kendi kelimelerinle aktar.','Both reports recommend protecting the river.','Her iki rapor da nehrin korunmasını öneriyor.','The first plan is cheaper, whereas the second is faster.','İlk plan daha ucuz, oysa ikinci plan daha hızlı.','The main difference concerns the timeline.','Temel fark zaman çizelgesiyle ilgili.','Neither report recommends protecting the river.','İki rapor da nehrin korunmasını önermiyor.'),
('Resmî Başvuru','B2','Bahçeler için destek isteyen bir e-posta hazırla. Amaç, gerekçe ve isteği uygun bir dille ifade et.','Resmî yazıda açık amaç, ilgili ayrıntı ve nazik kapanış kullanılır. I would appreciate… isteği yumuşatır.','I am writing to request support for our project.','Projemiz için destek istemek amacıyla yazıyorum.','I would appreciate it if you could provide further information.','Daha fazla bilgi verebilirseniz memnun olurum.','I look forward to hearing from you.','Yanıtınızı bekliyorum.','Hey, send us everything now!','Hey, her şeyi bize hemen gönder!'),
('Uzlaşma Masası','B2','Arkadaşların farklı öncelikleri var. Bir görüşü açıklayıp ortak çözüm için pazarlık et.','Bir noktayı kabul etmek, ardından kaygını açıklamak ve koşullu öneri sunmak uzlaşmayı kolaylaştırır.','I see your point; nevertheless, we need a safer option.','Ne demek istediğini anlıyorum; yine de daha güvenli bir seçeneğe ihtiyacımız var.','We could agree, provided that the river is protected.','Nehrin korunması koşuluyla anlaşabiliriz.','Let us find a solution that works for everyone.','Herkes için işe yarayan bir çözüm bulalım.','Your opinion does not matter.','Senin görüşünün önemi yok.'),
('Papi’nin Büyük Hikâyesi','B2','Dört dünyada öğrendiklerini kullanarak bahçelerin geleceği için bir öneri sun. Papi artık seni yeni gelenlere rehberlik eden bir arkadaş olarak görüyor.','Bir sunuşta amaç, gerekçe, karşı görüş, cevap ve sonuç düzeni kullanılabilir. Öğrendiklerini yeni bağlamlarda kullanmaya devam et.','Our journey has shown us why cooperation matters.','Yolculuğumuz bize iş birliğinin neden önemli olduğunu gösterdi.','By working together, we can protect these gardens.','Birlikte çalışarak bu bahçeleri koruyabiliriz.','I recommend this plan because it balances cost and safety.','Bu planı öneriyorum çünkü maliyet ve güvenliği dengeliyor.','We should ignore the risks.','Riskleri görmezden gelmeliyiz.')
]
chapters=[]
for i,r in enumerate(rows):
 title,cefr,story,rule,e1,t1,e2,t2,e3,t3,bad,badtr=r
 cards=[{'en':e1,'tr':t1},{'en':e2,'tr':t2},{'en':e3,'tr':t3},{'en':bad,'tr':badtr}]
 steps=[{'kind':'scene','label':'Hikâyeye gir','text':story,'en':e1,'tr':t1},{'kind':'teach','label':'Papi’den öğren','text':rule,'cards':cards}, {'kind':'choice','label':'Anlamı keşfet','prompt':e1,'en':e1,'tr':t1,'instruction':'Papi’nin söylediği ifadenin anlamını seç.','options':[badtr,t1,t2],'answer':1,'hint':rule}, {'kind':'listen','label':'Dinle ve bul','prompt':'Papi ne söylüyor?','en':e2,'tr':t2,'instruction':'Önce dinle, sonra duyduğun ifadeyi seç.','options':[e1,bad,e2],'answer':2,'hint':t2}, {'kind':'order','label':'Cümle kur','prompt':t1,'en':e1,'tr':t1,'tokens':e1.split(),'answer':e1,'hint':e1}, {'kind':'speak','label':'Konuşma provası','en':e2,'tr':t2,'text':'Dinle, sonra yüksek sesle tekrar et. Kendi sesini duymaya ve kelimeleri açık söylemeye odaklan. Bu adımda otomatik telaffuz puanı verilmez.'}, {'kind':'choice','label':'Hikâyede kullan','prompt':t3,'en':e3,'tr':t3,'instruction':'Bu durumda hangi ifadeyi kullanırsın?','options':[e3,e1,bad],'answer':0,'hint':rule}]
 if i:
  p=chapters[i-1]['cards'][0];steps.append({'kind':'choice','label':'Hatırlama yaprağı','prompt':p['en'],'en':p['en'],'tr':p['tr'],'instruction':'Önceki duraktan bir ifade: anlamını hatırlıyor musun?','options':[badtr,t2,p['tr']],'answer':2,'hint':p['tr']})
 steps += [{'kind':'write','label':'Kendi sözlerin','en':e3,'tr':t3,'text': 'Bu duraktaki ifadelerden yararlanarak kendinle veya hikâyeyle ilgili '+('bir kısa cümle' if cefr=='A1' else 'iki kısa cümle' if cefr=='A2' else 'bir görüş ve gerekçesini' if cefr=='B1' else 'bir öneri, gerekçe ve karşı görüş içeren kısa bir paragraf')+' yaz. Papi örneği rehber olsun. Bu açık uçlu çalışma kaydedilir; otomatik doğru/yanlış puanı verilmez.'}, {'kind':'choice','label':'Kapı görevi','prompt':t2,'en':e2,'tr':t2,'instruction':'Son görev: Papi’ye söylemek istediğin ifadeyi seç.','options':[bad,e2,e3],'answer':1,'hint':rule}]
 chapters.append({'id':i,'title':title,'cefr':cefr,'world':['Saklı Bahçe','Kuzey Bahçesi','Kristal Şehir','Orman Konseyi'][i//10],'story':story,'rule':rule,'cards':cards,'steps':steps})
text=json.dumps(chapters,ensure_ascii=False,separators=(',',':'))
Path('ingilizce/story-curriculum.js').write_text('/* Original Diji-Medu learning stories; educational stages, not language certification. */\nwindow.DMStoryCurriculum='+text+';\n')
Path('supabase/functions/diji-api/story-curriculum.js').write_text('export const STORY_CHAPTERS='+text+';\n')
print(len(chapters),'chapters',sum(len(x['steps']) for x in chapters),'activities')
