import assert from 'node:assert/strict';
import {buildDialogue,buildCloze,prepareActivity,evaluateActivity,getSpeechRequest,normalizeAnswer} from './papi-v2-activity-engine.mjs';
const chapter={phrases:[{en:'May I borrow a pencil?',tr:'Bir kalem ödünç alabilir miyim?'},{en:'Here is your pencil.',tr:'İşte kalemin.'}],curatedDialogue:{prompt:'May I borrow a pencil?',reply:'Here is your pencil.',translation:'İşte kalemin.',distractors:['I have a cat.','It is raining.']},curatedCloze:{prompt:'May I _____ a pencil?',correctText:'borrow',translation:'Ödünç almak',fullSentence:'May I borrow a pencil?',distractors:['borrows','borrowing']}};
const dlg=buildDialogue(chapter,7);
assert.equal(dlg.options.length,3);
assert.equal(evaluateActivity(dlg,'Here is your pencil.').correct,true);
assert.equal(evaluateActivity(dlg,'May I borrow a pencil?').correct,false);
assert.equal(dlg.speakingAssessment,false);
const cloze=buildCloze(chapter,3);
assert.ok(cloze&&cloze.prompt.includes('_____'));
assert.equal(evaluateActivity(cloze,cloze.correctText).correct,true);
assert.equal(evaluateActivity(cloze,'banana').correct,false);
assert.equal(getSpeechRequest(dlg,'slow').rate,.75);
assert.equal(getSpeechRequest({},'slow'),null);
assert.equal(normalizeAnswer('  HELLO! '),'hello');
const choice=prepareActivity({kind:'choice',options:['wrong','right'],answer:1},44);
assert.equal(choice.options[choice.answer],'right');
assert.equal(evaluateActivity(choice,choice.answer).correct,true);
assert.equal(evaluateActivity({kind:'order',answer:'I like apples.'},['I','like','apples.']).correct,true);
assert.deepEqual(evaluateActivity({kind:'teach'},null),{graded:false,correct:null,explanation:null});
console.log('Papi V2 dialogue, cloze, evaluation and speech request tests passed');
